### ISSUE TITLE
Direct3D

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-related#101]
"Since Direct3D is in the picture, the scenario is necessarily narrowed to C++ applications" - Why? Now that SharpDX isn't accepting pull requests anymore, is there no way forward for C# developers to use DirectX? So sad that there's such narrow support for DirectX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro#feedback)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams, thanks for the issue and the feedback. For Direct2D, I don't know whether you know about [Win2D](https://github.com/Microsoft/Win2D) (which *is* accessible from C#). I'm not aware of a similar 3D API, however. 

In terms of giving feedback around what APIs, and language projections, you prefer, there is the the [Windows developer feedback site](https://wpdev.uservoice.com). If there are issues with the documentation itself, this would be the right place to raise those. I'm sorry I couldn't be of more direct help with this issue.

~Steve

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams, I'll go ahead and close this issue now. ~Steve
