### ISSUE TITLE
Step by Step of how to use it with WinForm.

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/winrt-related#102]
Example to references via WinForm project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started#feedback)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by Karl-Bridge-Microsoft** [comment]
@marb2000 - can you let me know if you resolved this issue?

**Comment by Karl-Bridge-Microsoft** [comment]
Closing due to age of original issue and evolution of WinUI and supporting docs. Please re-open if issue persists.
