### ISSUE TITLE
Provide contract version number in addition to SDK version

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-related#103]
It'd be great for the list here to have the API contract version number (1-7) called out here in addition to the existing SDK version number.  That's useful when using conditional XAML to match contract version numbers with sdk version numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afdf49d-a4d3-2c25-5146-a74b31e45819
* Version Independent ID: 658615f6-b07b-3186-d042-6fb4b52e0640
* Content: [Windows Universal Platform SDK API contracts - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk)
* Content Source: [winrt-related-src/extension-sdks/windows-universal-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-universal-sdk.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by knicholasa** [comment]
Hi Michael, thanks for the feedback. We're currently in the process of figuring out the best way to provide the information on these pages to users. I'll make note of your feedback.

**Comment by michael-hawker** [comment]
@knicholasa in the meantime, could we at least in the headers next to the version number put the contract number as well for easy reference? Thanks!

**Comment by knicholasa** [comment]
Hi @michael-hawker , I no longer own this content set, so I'll let @GrantMeStrength respond.
