### ISSUE TITLE
Document guid_of

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-related#105]
Is there any reason why winrt::guid_of&lt;T&gt;() is not documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b3f5b-e729-300a-eb81-402648520ff3
* Version Independent ID: 40daa692-e9a1-2e27-0c10-c6baf69bc453
* Content: [winrt namespace (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/winrt#feedback)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/winrt.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/winrt.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @benstevens48, thanks for filing the issue. I've added the missing topic, and it's now live. I'll go ahead and close this issue now, but please reopen it if necessary. ~Steve
