### ISSUE TITLE
Alternative for Windows 8.

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/winrt-related#106]
Please help me listed down any UI technology could deliver to Windows Store for Windows 8 above as General Public

- WinForms/WPF desktop app with allowElevation (We don't recommend that you declare this capability in applications that you submit to the Microsoft Store.)
- Subset of UWP Xaml? (Documentation that List of the subset?)
- WebView (One of the best, certainly some use case but heavy memory choice, if Microsoft Edge chromium, ever implemented as New WebView)
- Any examples. Thanks for helping deliver better Windows Ecosystem for Public

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jesbis** [comment]
Hi meteorsnows,

You can find the developer documentation for Windows 8 Store apps under the "previous versions" section of the docs:  

Windows 8 development overview:   
https://docs.microsoft.com/en-us/previous-versions/windows/apps/mt244353(v=win.10)
Windows 8 SDK:   
https://docs.microsoft.com/en-us/previous-versions/visualstudio/windows-sdk/ms717358(v=vs.110)

It has information on the different options, documentation on the Windows 8 Xaml SDK, and links to samples.
