### ISSUE TITLE
More documentation is needed

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#108]
please describe why winrt directory in windows kit has different syntax.
There are all kinds of attributes.
Writing code as described in the articles simply refuses to compile.
It is just not clear what is a new midl syntax, what is old midl syntax.

Example:
        [contract(Windows.Foundation.UniversalApiContract, 3.0)]
        [marshaling_behavior(agile)]
        [threading(both)]
        runtimeclass PackageStagingEventArgs
        {
            [default] interface Windows.ApplicationModel.IPackageStagingEventArgs;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by kingofthebongo2008** [comment]
Example:
I have this interface

       [uuid(CD38D0C5-743A-43C2-889F-2EA3A14082DF)]
        [version(1.0)]
        interface ISwapChainResources : IInspectable
        {
            HRESULT Resize( UInt32 width, UInt32 height );
            HRESULT WaitForGpu();
            HRESULT WaitForFence(IFenceHandle v );
            HRESULT InsertWaitOn(IFenceHandle v );
            HRESULT Present();
            HRESULT Sync();
            HRESULT MoveToNextFrame();
            HRESULT SetSourceSize(UInt32 width, UInt32 height);

            IDirectGpuCommandContext CreateDirectCommandContext();
        };

If i change it to this:

namespace UniqueCreator
{
    namespace Graphics
    {
        [uuid(CD38D0C5-743A-43C2-889F-2EA3A14082DF)]
        [version(1.0)]
        interface ISwapChainResources : IInspectable
        {
            HRESULT Resize( UInt32 width, UInt32 height );
            HRESULT WaitForGpu();
            HRESULT WaitForFence(IFenceHandle v );
            HRESULT InsertWaitOn(IFenceHandle v );
            HRESULT Present();
            HRESULT Sync();
            HRESULT MoveToNextFrame();
            HRESULT SetSourceSize(UInt32 width, UInt32 height);

            HRESULT CreateDirectCommandContext([out, retval] IDirectGpuCommandContext** value);
        };
    }
}

I get:

..\src\idl\SwapChainResources.idl(22): error MIDL5148: [msg]Classic WinRT IDL constructs cannot be used in Modern WinRT IDL types [context]: [ Procedure 'CreateDirectCommandContext' ( Interface 'UniqueCreator.Graphics.ISwapChainResources' ) ]

and winrt directory is all modified this way, so usually one looks there for examples of interface and runtime classes design.

My point is, it is not clear what is old, what is new.

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, the Windows SDK folder `%WindowsSdkDir%Include<WindowsTargetPlatformVersion>\winrt` contains `.idl` files that are written with the MIDL 2.0 syntax. These are first-party Windows Runtime APIs, declared in their application binary interface (ABI) form. These files exist primarily for tooling to use&mdash;you won't author nor consume these APIs in this form.

The same APIs in MIDL 3.0 syntax can be found in `%WindowsSdkDir%Include<WindowsTargetPlatformVersion>\cppwinrt\winrt`.

I'm currently updating the docs to cover this info. Thanks for filing the issue!

~Steve

**Comment by stevewhims** [comment]
The new section is now live here: [MIDL 1.0, 2.0, and 3.0](https://docs.microsoft.com/uwp/midl-3/intro#midl-10-20-and-30). That discusses the generations of MIDL, and covers the folder that you mentioned and why we don't recommend that you look there for examples of MIDL 3.0 (but rather in the other folder that I mentioned, or in the documentation. ~Steve

**Comment by stevewhims** [comment]
Hi, I'll go ahead and close this issue now since it feels resolved. ~Steve
