### ISSUE TITLE
Documenation not clear about midl versions that one encounters when tries to use midl with cppwinrt

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#109]
When using cppwinrt, the midl compiler on this interface returns.

namespace UniqueCreator
{
    namespace Graphics
    {
        //[uuid(CD38D0C5-743A-43C2-889F-2EA3A14082DF)]
        //[version(1.0)]
        interface ISwapChainResources// : IInspectable
        {
            void Resize( unsigned int width, unsigned int height );
            void WaitForGpu();
            void WaitForFence(IFenceHandle v );
            void InsertWaitOn(IFenceHandle v );
            void Present();
            void Sync();
            void MoveToNextFrame();
            void SetSourceSize(UInt32 width, UInt32 height);

            IDirectGpuCommandContext CreateDirectCommandContext();
        };
    }
}
1&gt;..\src\idl\SwapChainResources.idl(14): error MIDL5146: [msg]Modern WinRT IDL constructs cannot be included in classic WinRT IDL types [context]: [ Procedure 'WaitForGpu' ( Interface 'UniqueCreator.Graphics.ISwapChainResources' ) ]

It is just not clear what is classic what is modern,

If i change the functions to return HRESULT everything is fine, however this is not described in the documentation.

What if someone wants to define an interface

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dc10e0-781d-367d-bc47-eef1a4abac87
* Version Independent ID: 4750ae98-e82e-15b7-5f70-c677e051e7ae
* Content: [Synthesizing interfaces (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/synthesizing-interfaces)
* Content Source: [winrt-related-src/midl-3/synthesizing-interfaces.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/synthesizing-interfaces.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, that error message is because you're using **unsigned int**, which is not a MIDL 3.0 type. **UInt32** is a MIDL 3.0 type. See [Introduction to Microsoft Interface Definition Language 3.0](https://docs.microsoft.com/uwp/midl-3/intro#types) for a list of MIDL 3.0 types.

**void** is valid as a MIDL 3.0 return type, so that's not a problem. The following is valid MIDL 3.0, and it's the equivalent of your listing, but there's a simpler way to do this after this code.

```idl
namespace UniqueCreator
{
    namespace Graphics
    {
        interface IDirectGpuCommandContext
        {
            UInt32 Property;
        }
        interface IFenceHandle
        {
            UInt32 Property;
        }
        interface ISwapChainResources
        {
            void Resize(UInt32 width, UInt32 height);
            void WaitForGpu();
            void WaitForFence(IFenceHandle v);
            void InsertWaitOn(IFenceHandle v);
            void Present();
            void Sync();
            void MoveToNextFrame();
            void SetSourceSize(UInt32 width, UInt32 height);
            IDirectGpuCommandContext CreateDirectCommandContext();
        }
    }
}
```

If you can avoid declaring your own interfaces, then that's simpler. The [Synthesizing interfaces (MIDL 3.0)](https://docs.microsoft.com/uwp/midl-3/synthesizing-interfaces) topic talks about how MIDL 3.0 generates interfaces for you by default. So, just for interest, here's another version of your types, but this time allowing MIDL 3.0 to generate any necessary interfaces.

```idl
namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass DirectGpuCommandContext
        {
            DirectGpuCommandContext();
            UInt32 Property;
        }

        runtimeclass FenceHandle
        {
            FenceHandle();
            UInt32 Property;
        }

        runtimeclass SwapChainResources
        {
            SwapChainResources();
            void Resize(UInt32 width, UInt32 height);
            void WaitForGpu();
            void WaitForFence(FenceHandle v);
            void InsertWaitOn(FenceHandle v);
            void Present();
            void Sync();
            void MoveToNextFrame();
            void SetSourceSize(UInt32 width, UInt32 height);
            DirectGpuCommandContext CreateDirectCommandContext();
        }
    }
}
```

**Comment by stevewhims** [comment]
Hi, I'll go ahead and close this issue now since it feels resolved. ~Steve
