### ISSUE TITLE
%WindowsSdkDir%Include<WindowsTargetPlatformVersion>\cppwinrt\winrt not correct

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#110]
There is no idl here, just cppwinrt generated code,
One usually wants to write idl and then invoke cppwinrt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro#midl-10-20-and-30)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008! You're right--thank you for pointing that out, that's my mistake. I'll go ahead and fix that error.

~Steve

**Comment by stevewhims** [comment]
Thanks again, @kingofthebongo2008, I've fixed the issue you pointed out. I'll close this one now. ~Steve
