### ISSUE TITLE
No examples how functions are supposed to return interfaces or other classes 

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#111]
The examples here only provide information void and value types.
More complex relationships like retvals, what happens in cppwinrt is not described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dc10e0-781d-367d-bc47-eef1a4abac87
* Version Independent ID: 4750ae98-e82e-15b7-5f70-c677e051e7ae
* Content: [Synthesizing interfaces (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/synthesizing-interfaces)
* Content Source: [winrt-related-src/midl-3/synthesizing-interfaces.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/synthesizing-interfaces.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, you make a good point. The answer, FYI, is that if a method can't fail then return void; if it can fail then return an HRESULT. Each language projection will do the appropriate thing with that HRESULT. More info here: [Error handling with C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/error-handling#throwing-exceptions-when-authoring-an-api).

If I were to add more info, it'd be to that topic above. I'm hoping to keep the MIDL 3.0 docs as language-projection-agnostic as possible. Those docs say "MIDL 3.0 is specifically and solely designed for declaring types. You'll use a different programming language to implement those types."

~Steve

**Comment by stevewhims** [comment]
Hi, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
