### ISSUE TITLE
Arrays examples

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#112]
hello,
I need to do
struct MyStruct
{
   UInt8 m_array[3];
};

i get

error MIDL4000: [msg]A structure field cannot be a type of pointer. [context]: m_array [ Field 'm_array' of Struct 'UniqueCreator.Graphics.MyStruct'  ]

How one can declare arrays ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, you can pass an array to a method, or have one as a property of a runtime class.

```idl
runtimeclass FenceHandle
{
    FenceHandle();
    void Method(Int32[] array);
    UInt32[] Property;
}
```

But, [a data member of a struct type must either be a value type or a nullable type](https://docs.microsoft.com/en-us/uwp/midl-3/intro#types). So unfortunately you can't have a struct field that's an array. And note that the `[3]` is not valid. Just the brackets. "Array types are constructed by following a type name with square brackets. For example, Int32[] is a single-dimensional array of Int32"--see the same link as above.

~Steve

**Comment by stevewhims** [comment]
Hi, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
