### ISSUE TITLE
Adding resources to App.xaml doesn't work.

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/winrt-related#113]
XamlControlResources does not seem to be a recognized type in the xaml editor. Compilation of the app also fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started#feedback)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
@Arush-Agarampur can you provide more details about your app? Which version of the nuget package did you add? What is the contents of your app.xaml? What is the compilation error you encounter?

**Comment by AzAgarampur** [comment]
Sorry, I don't know why this got posted now. This was an issue I had a long time ago and is working now.

Sorry again.

**Comment by jevansaks** [comment]
No worries, thanks for following up!
