### ISSUE TITLE
Update for 19H1, 19H2, and 20H1

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#114]
I would appreciate it if the uap8: and desktop6: schemas were documented here. Once 19H1 is released, I want to be able to use these schemas for my apps, but I would prefer proper documentation as compared to raw XSD schemas and Googling. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c20a74-18a7-a0a3-b828-6d2749151255
* Version Independent ID: 1ac0dc95-48ec-4a3b-4455-b8a0b6f094b2
* Content: [Package manifest schema reference for Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by wjk** [comment]
And now we need documentation for the 19H2 ("Vibranium") and 20H1 ("Manganese") schemas as well! I can see the raw XSD schema data by dumping `AppxPackaging.dll`, but I have no clue as to the function of the elements described in those schemas. (Add to that many of the new features in 20H1 appear to be duplicating features already extant in other MSIX manifest schemas — namely, packaged COM support — leaving me even more confused.) There has not been any updates to this ticket in almost a year now. Could someone please take a look at this? Thanks!

**Comment by mcleanbyron** [comment]
Thanks for reporting this. I am in the process of documenting the new schema elements up through Windows 10, version 2004 (code-named Vibranium) right now, and I hope to have them published in the next couple of weeks (note that the OS release is not final yet). I will be documenting the missing schema items from Windows 10, version 1903 at the same time.

**Comment by wjk** [comment]
@mcleanbyron Any updates?

**Comment by mcleanbyron** [comment]
Thanks for following up. The following schema items are now documented: 

* Windows 10, version 1903: The desktop6 namespace elements are now documented. A few uap8 elements from this release are now also published, but the remaining are still in progress.
* Windows 10, version 2004 ("Vibranium"): The uap10 and com3 namespace elements are now documented.

The schema updates for any future versions of of Windows 10 will be published closer to the release dates for those versions.

**Comment by wjk** [comment]
@mcleanbyron I compared the docs available as of this writing to what's currently in Windows and, unfortunately, there are still gaps in coverage. The desktop6 elements that have to do with services are documented, but the rest are not. There is no discussion of the desktop6 elements related to custom install actions, or desktop6:InstalledLocationVirtualization. uap10:FileType, uap10:Tools, and uap10:Workspaces are also undocumented.

**Comment by wjk** [comment]
@mcleanbyron I have noted one rather annoying issue with the AppX docs, however: The three lists of elements that I know of ([here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root) and [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/root-elements), plus the TOC navigation sidebar) currently show different subsets of the AppX schema corpus. Certain elements may very well be documented, but if I they’re not in the list I’m looking at, I usually assume that they aren’t. My mistaken post above (marked as outdated) was due to this issue. If you could ensure that those lists are kept in sync, we can avoid this problem in the future. Thanks so much!

**Comment by mcleanbyron** [comment]
Hi @wjk. Thanks for reporting that the [schema reference](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root) article was missing entries for some of the new desktop6 and uap10 elements. I just published an update to this article that adds entries for these elements. 

As you might have already guessed, this (and the other schema pages) are currently written manually, and unfortunately sometimes items like these slip through the cracks. We have plans to move all of the schema docs to an automated process, but it will be some time before we have time to implement that.

Regarding your earlier (outdated) comment, I don't see a desktop6:InstalledLocationVirtualization element in the latest release schema, but there is a uap10:InstalledLocationVirtualization. This and uap8::Tools, uap8::Workspaces, and more will be documented in the next round of schema doc work planned for early next month.

Thanks for your feedback!
