### ISSUE TITLE
Minor typo the title for a link

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/winrt-related#115]
The first paragraph of the article instructs the following to search for the package: **Enter one of the package names below to search for it online**. But one of the package name given is `Microsoft.UI.Xaml.Controls`. And when you search for such a name in `VS2017` package Manager, a package with this name does not exist. I think, the title should read as `Microsoft.UI.Xaml`. However, the link for the title is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716795b6-2bcc-8ff5-f999-5e1de88a04e0
* Version Independent ID: 590dd55a-a259-e6dc-972e-531dda080cd9
* Content: [NuGet package list for the Windows UI Library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/nuget-packages)
* Content Source: [winrt-related-src/toolkits/winui/nuget-packages.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/nuget-packages.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you, @saf-itpro! I checked in a fix, it should be live later today.
