### ISSUE TITLE
Clarify usage of FileExplorerContextMenus

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-related#117]
Please provide a sample on how we are supposed to use FileExplorerContextMenus with
* ExeServer
* SurrogateServer

Please extend which interfaces are available for consumption here.
* Is IShellExtInit supported?
* Is IContextMenu supported?
* If not, when will this functionality be available?

How are we supposed to register COM Objects consumable by Windows Explorer Shell to extend the file explorer context menu?
I tried several variants of DllMain, Main(), registering my COM objects with C++, C++/CX, C# on UWP and Packaging Project without any success.

My latest failing attempt looks like this:
```
<Applications>
	<Application Id="App"
		Executable="$targetnametoken$.exe"
		EntryPoint="$targetentrypoint$">
		<uap:VisualElements
			DisplayName="ShellApp.Package"
			Description="ShellApp.Package"
			BackgroundColor="transparent"
			Square150x150Logo="Images\Square150x150Logo.png"
			Square44x44Logo="Images\Square44x44Logo.png">
			<uap:DefaultTile Wide310x150Logo="Images\Wide310x150Logo.png" />
		</uap:VisualElements>
		<Extensions>
			<desktop4:Extension Category="windows.fileExplorerContextMenus">
				<desktop4:FileExplorerContextMenus>
					<desktop5:ItemType Type="*">
						<desktop5:Verb Id="ShellApp" Clsid="840C5236-4B3F-4320-8CD6-79B8CA95FCC0" />
					</desktop5:ItemType>
					<desktop5:ItemType Type="Directory">
						<desktop5:Verb Id="ShellApp" Clsid="840C5236-4B3F-4320-8CD6-79B8CA95FCC0" />
					</desktop5:ItemType>
					<desktop5:ItemType Type="Directory\Background">
						<desktop5:Verb Id="ShellApp" Clsid="840C5236-4B3F-4320-8CD6-79B8CA95FCC0" />
					</desktop5:ItemType>
				</desktop4:FileExplorerContextMenus>
			</desktop4:Extension>

			<com:Extension Category="windows.comServer">
				<com:ComServer>
					<!--<com:SurrogateServer>
						<com:Class Id="840C5236-4B3F-4320-8CD6-79B8CA95FCC0" Path="ShellApp\ShellApp.exe" ThreadingModel="Neutral" />
					</com:SurrogateServer>-->
					<com:ExeServer Executable="ShellApp\ShellApp.exe">
						<com:Class Id="840C5236-4B3F-4320-8CD6-79B8CA95FCC0" />
					</com:ExeServer>
				</com:ComServer>
			</com:Extension>
		</Extensions>
	</Application>
</Applications>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b210b6b-7d08-6ac7-ab8c-07920a3eee39
* Version Independent ID: 100c17d9-debc-f7c5-048f-68770b2da884
* Content: [desktop4:FileExplorerContextMenus - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop4-fileexplorercontextmenus)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop4-fileexplorercontextmenus.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop4-fileexplorercontextmenus.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by constant-arapov** [comment]
Have You found a solution ? If  You've found, tell me please. I've got the same prolbem. I just want to add a reference to winodws context menu. But using similar solution as You also have no success.

**Comment by mcleanbyron** [comment]
Hello - We recently added some related packaging examples to [this article](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#context-menu) that demonstrate how to use this packaging extension to register a context menu implemented via IExplorerCommand and/or IExplorerCommandState. I updated the remarks to this article to point to those examples. I hope this helps!

**Comment by AliveDevil** [comment]
Thanks for those examples. Just a quick question here: Is it possible to somehow get an example in a managed-language instead of relying on C++ (C++/CX)?

**Comment by vors** [comment]
@AliveDevil where did you find the `<desktop5:ItemType Type="Directory">` documentation ? My understanding is that `desktop4:ItemType` is limited only to the files, not folders. But the MS documentation about `desktop5:ItemType` doesn't mention it. (opened #142)

**Comment by AliveDevil** [comment]
See https://github.com/MicrosoftDocs/winrt-related/issues/142#issuecomment-534898692.

**Comment by DineshSolanki** [comment]
> 
> 
> Thanks for those examples. Just a quick question here: Is it possible to somehow get an example in a managed-language instead of relying on C++ (C++/CX)?

also looking for same.

**Comment by sanjayssk** [comment]
I have included that same DLL in my appx exactly according to the article with guid matching. But it doesn't work. Also, externally using regsvr32 on that DLL given in the sample also does not work, saying DllRegisterServer entry point not found.
