### ISSUE TITLE
Unclear ownership semantics

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-related#118]
It's difficult to infer the ownership semantics from the documentation. The class template is introduced with the following statement

> `winrt::com_array` *is a* `winrt::array_view`, so it's important to see the [winrt::array_view](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/array-view) struct template topic [...]

With `winrt::array_view` being a non-owning view into, or span over, a contiguous sequence, the [com_array::com_array constructor](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-array#com_arraycom_array-constructor) documentation is confusing:

> Initializes a new instance of the `com_array` struct with a **copy** of the input data.

If this is accurate, then `com_array` is the owner of the copied data, and thus deviates from the semantics of the `array_view` which it references. If, on the other hand, `com_array` is indeed a non-owning view, then I'm having difficulty making sense out of the constructor with the signature `com_array(uint32_t const count)`. No resource is given at all, making me wonder, what data the `com_array` is viewing.

This gets even more confusing when the free function template [detach_abi](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-array#detach_abi-function) is introduced:

> Detaches a `com_array` object from its raw values **without decrementing their reference counts** [...]

If `com_array` is non-owning, why would it even attempt to do any resource management? And if it does own the copy, what would *"decrementing [the] reference count"* amount to, when instantiated with a `std::vector<int>`, for example?

As currently written, I cannot make out, what the `com_array` class template really is, what it does, and when to use it. Could we get the documentation updated and/or fixed, to help us make judicious decisions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b59458db-7f7b-f2ff-6e69-75e028a37489
* Version Independent ID: e1f08202-a573-118e-85b2-69981611df16
* Content: [winrt::com_array struct template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-array)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/com-array.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/com-array.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tim-weis, thanks for raising this issue. You're right, the topic and the relationship between the types is unclear. I'm currently updating the topic to add clarification. **winrt::com_array** does own its data (unlike **winrt::array_view**). The constructor that takes just a uint32_t creates that number of default-initialized elements of type T. Thanks for letting me know. ~Steve

**Comment by stevewhims** [comment]
The topic is now updated. I'll go ahead and optimistically close the issue. Thanks again for pointing this out, @tim-weis! ~Steve

**Comment by tim-weis** [comment]
The update clarifies most of the ownership semantics, thanks for that Steve!

Although I'm not entirely sure, the documentation is completely accurate now. `com_array` can apparently be used with non-COM objects, as well (which is in conflict with the documentation). And when used with COM-objects, it looks like it doesn't copy the input, but rather stores references to the source objects, and increments the reference counts on them.

I'd usually use a different container for my non-COM needs, except that the C++/WinRT projection generates `com_array`s from arrays in IDL (e.g. `UInt8[]`), so I do come across those class template instantiations with non-COM type parameters.

**Comment by stevewhims** [comment]
Thanks for looking closely, and you're right. I did some more digging and in fact I had misinterpreted the connection between com_array and COM. I've just published an update. You're right that it's perfectly normal for com_array to contain primitives. com_array is implemented in <winrt/base.h>.
