### ISSUE TITLE
Missing info() function in 18362

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/winrt-related#119]
This page documents hresult_error as having a method called info() to get a pointer to the restricted error info, but I can't see such method in either the 18362 or the 17763 sdk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85cd8df-94c9-b859-5158-7f99d0da0b48
* Version Independent ID: 24b7584f-9612-1e3c-18bd-66975fc69671
* Content: [winrt::hresult_error struct (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/error-handling/hresult-error#hresult_errorinfo-function)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/error-handling/hresult-error.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/error-handling/hresult-error.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @sylveon, thanks for pointing this out. Yes, 10.0.17134.0 was the last version of base.h containing this member function. You can do this to obtain an IRestrictedErrorInfo instead:

```cppwinrt
#include <unknwn.h>
#include <restrictederrorinfo.h>
// include other cppwinrt headers here.

    winrt::hresult_error err;
    // ...
    auto p{ err.try_as<::IRestrictedErrorInfo>() };
    p->... // call IRestrictedErrorInfo methods.
```

I'll update the docs now.

~Steve

**Comment by sylveon** [comment]
Awesome, thanks
