### ISSUE TITLE
Its a great overview to get an overview whats possible in which version

### ISSUE THREAD

**Issue by AndreasLuebbers** [MicrosoftDocs/winrt-related#121]
please update this in future versions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afdf49d-a4d3-2c25-5146-a74b31e45819
* Version Independent ID: 658615f6-b07b-3186-d042-6fb4b52e0640
* Content: [Windows Universal Platform SDK API contracts - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk#feedback)
* Content Source: [winrt-related-src/extension-sdks/windows-universal-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-universal-sdk.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for your feedback. I've updated the page with the latest information and the changes should show up soon.
