### ISSUE TITLE
Hyperlink issue FlowLayout

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/winrt-related#123]
FlowLayout hyperlink refers to the LayoutPanel page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86134b1e-18c2-4945-287c-0aec08e1db21
* Version Independent ID: dc12a423-16f3-0c19-d433-b0e5f4002733
* Content: [WinUI 2.2 Release Notes - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.2)
* Content Source: [winrt-related-src/toolkits/winui/release-notes/winui-2.2.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/release-notes/winui-2.2.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @predavid
* Microsoft Alias: **mijacobs**

**Comment by predavid-zz** [comment]
Accidentally assigned to me.  @mijacobs  and @micahl - since you co-own the FlowLayout docs, could you please help address this issue?

**Comment by micahl** [comment]
Mike fixed the issue a while back with (fc152df0fa832b33394f426c34c47176df7a4a8d).  I verified the link is already working so closing this out.
