### ISSUE TITLE
`multiSelectModel` attribute of AppXManifest <uap2:Verb> is undocumented

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/winrt-related#124]
It is described here in general guidance: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions
and its effects are discussed in the context of regular desktop applications registering ShellExecute verbs here: https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-employ-the-verb-selection-model

but is missing from this reference. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 772f7682-8d22-f944-968b-32dfc43e7091
* Version Independent ID: f6571ee5-9a5f-19f1-063b-e84c9b8fb7ef
* Content: [uap2:Verb - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap2-verb)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap2-verb.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap2-verb.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by metathinker** [comment]
Actually, it may not be possible to document this attribute properly; after experimenting, it seems that either I'm doing something wrong (more likely), or the attribute doesn't have the same meaning its non-packaged-app variant would have.

---------------

Edit: Indeed, I was doing something wrong! The attribute works just like its non-packaged-app variant Registry value would.

**Comment by metathinker** [comment]
This is interesting - actually, the `MultiSelectModel` attribute does work differently than the corresponding `MultiSelectModel` registry value for non-packaged apps.

I played around with registering 2 programs for the same context-menu action (verb) on the same file extension, one of them being a non-packaged classic desktop app, and one of them being an AppX-packaged classic app. Then I tried selecting multiple files with that extension and choosing that context-menu action.

When `MultiSelectModel=Single`:
- AppX packaged app: the app is launched only once, and is given the path of exactly one selected file in its command line.
- Non-packaged app: same

When `MultiSelectModel=Document`:
- AppX packaged app: the app is launched N times, where N is the number of files. Each run of the app is given the path of a different one of the N files.
- Non-packaged app: same

When `MultiSelectModel=Player`:
- AppX packaged app: the app is launched only once. In its command line, it gets the paths of every selected file, separated by spaces.
- Non-packaged app: the app is launched N times, where N is the number of files. Each run of the app is given the path of a different one of the N files.

Notice how `MultiSelectModel=Player` has different behavior! This difference is very surprising.

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. With regards to documenting the MultiSelectModel attribute, this is actually part of the uap3:Verb element (which extends the uap2:Verb element). We unfortunately never documented the uap3:Verb element previously, but I just published a new article for it [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-verb).

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. With regards to documenting the MultiSelectModel attribute, this is actually part of the uap3:Verb element (which extends the uap2:Verb element). We unfortunately never documented the uap3:Verb element previously, but I just published a new article for it [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-verb).
