### ISSUE TITLE
How do I actually reference the theme styles in `XamlControlsResources` with `{ThemeResources}`?

### ISSUE THREAD

**Issue by Palatis** [MicrosoftDocs/winrt-related#125]
I already have `&lt;controls:XamlControlsResources /&gt;` in my 'App.xaml`.

However, it unable to resolve the style when I reference them (for instance `HeaderToggleButtonStyle` defined in `Microsoft.UI.Xaml.Controls/Expander.xaml`)

What should I do?
or
How do I correctly style a WinUI control?

What should I do?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - Windows UWP applications](https://docs.microsoft.com/zh-tw/uwp/toolkits/winui/getting-started#feedback)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
Sorry, I don't see a HeaderToggleButtonStyle or Expander.xaml in the https://github.com/microsoft/microsoft-ui-xaml project anywhere. Where did you find this particular style documented?

**Comment by Palatis** [comment]
> 
> 
> Sorry, I don't see a HeaderToggleButtonStyle or Expander.xaml in the https://github.com/microsoft/microsoft-ui-xaml project anywhere. Where did you find this particular style documented?

sorry I messed up with Windows Community Toolkit...
