### ISSUE TITLE
Missing a lot of newer UWP APIs

### ISSUE THREAD

**Issue by contextfree** [MicrosoftDocs/winrt-related#126]
For example:
Console -&gt; could point to newer UWP Console apps approach in https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp

DWM -&gt; Windows.UI.Composition

MDI -&gt; Windows Community Toolkit Tabs control, AppWindow

IPC mechanisms like named pipes -&gt; point to general IPC approach with App Services, etc.

Some of these aren't 1:1 replacements and won't work for some uses of those APIs, but would still be worth pointing people towards them (maybe with caveats)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4b0781-eddc-d60c-db62-5e2e50ffad6a
* Version Independent ID: 0c885553-52a1-a380-e6be-adeeab59d367
* Content: [Alternatives to Windows APIs in Universal Windows Platform (UWP) apps - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/win32-and-com/alternatives-to-windows-apis-uwp)
* Content Source: [winrt-related-src/win32-and-com/alternatives-to-windows-apis-uwp.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/win32-and-com/alternatives-to-windows-apis-uwp.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by MatchaMatch** [comment]
Thanks for your suggestions - they've been integrated into the referenced document and you should see them live within 24 hours.
