### ISSUE TITLE
Inverse to `winrt::get_abi()`?

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-related#13]
I wanted to investigate ABI – C++/WinRT interop and found the [`get_abi`](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/get-abi.md) documentation.

I also know of an [interoperability page](https://github.com/Microsoft/cppwinrt/blob/master/Docs/Interoperability%20Helper%20Functions.md) in the C++/WinRT GitHub docs (that I think may be outdated?)

I would expect a **related link** on the `get_abi` page that would show the converse: converting ABI classes into C++/WinRT classes (just like we have [for CX](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/cx-to-winrt)).

Is there a page explaining this interop? I could not find one. Thanks!

**Comment by stevewhims** [comment]
Hi, Gina, these are all great questions and observations, and I have a task (which I'll work on next) assigned to me to take care of this. As you know, C++/WinRT has been in a pre-release state for a while, and as we get ready to release it we're working to fill gaps in the documentation. Gaps such as the ones you're noticing. I'll get on with my task now, and I'll publish the docs just as soon as I can. Thanks again! ~Steve

**Comment by stevewhims** [comment]
Sorry, Ben (not Gina). My bad! :)
~Steve

**Comment by citelao** [comment]
Happy to help! I appreciate the quick response 😁

**Comment by stevewhims** [comment]
@citelao, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
