### ISSUE TITLE
Clarify difference

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/winrt-related#133]
What's the difference between &lt;AutomaticBackgroundTask /&gt; and &lt;OnLaunch HoursBetweenUpdateChecks="8" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75720026-9ca5-4eb3-0446-ff3a8f192b3f
* Version Independent ID: c13637f9-268e-0c2e-ea57-3436f25d3657
* Content: [AutomaticBackgroundTask - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-automatic-background-task)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-automatic-background-task.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-automatic-background-task.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The engineering team has confirmed the differences as follows:
* AutomaticBackgroundTask will check every 8 hours whether or not the app is running.
* OnLaunch HoursBetweenUpdateChecks=”8” will check only on app launch, and only if it hasn’t previously checked within the last 8 hours. 

I am updating the description for HoursBetweenUpdateChecks to clarify this behavior.
