### ISSUE TITLE
Port is 1-65535 for FirewallRule

### ISSUE THREAD

**Issue by TimMisiak** [MicrosoftDocs/winrt-related#134]
The text ```An integer value between 0 and 65535.``` should actually be ```An integer value between 1 and 65535.``` on the page for desktop2:Rule of appxmanifest. In other words, 0 is not valid, 1 is valid, 65535 is valid, 65536 is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6302b4-8abf-52de-a469-27a02cb8738a
* Version Independent ID: e7599bda-aca8-7f2c-29dd-70e78f2f04ca
* Content: [desktop2:Rule - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-rule#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-rule.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-rule.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Thanks for your contribution! I've updated the content with your suggestion; the changes should be live soon.
