### ISSUE TITLE
Cannot use both AutomaticBackgroundTask and OnLaunch

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/winrt-related#135]
I have an .appinstaller with both children in the UpdateSettings element. OnLaunch has HoursBetweenUpdateChecks="0".
The .appinstaller namespace is http://schemas.microsoft.com/appx/appinstaller/2017/2.

Installation fails when I open the .appinstaller and I update with the App Installer UI with the following error message, on a Windows 10 1803 device:

Deployment Add operation with target volume C: on Package [package name] from:  [appname.appxbundle]  failed with error 0x80070005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7ce943-631c-600e-c5ef-7ecd95f70aeb
* Version Independent ID: 95c6d06d-92c3-8900-e44f-8300644f12ee
* Content: [UpdateSettings - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-update-settings.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-update-settings.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by julienshepherd** [comment]
<UpdateSettings>
	<OnLaunch HoursBetweenUpdateChecks="0" />
	<AutomaticBackgroundTask/>
    </UpdateSettings>

**Comment by julienshepherd** [comment]
0x80070005 is the HRESULT for Access denied. My account is administrator, but there can be group policies that could affect this. What policies are required for AutomaticBackgroundTask ?

**Comment by julienshepherd** [comment]
The issue persists when I keep just AutomaticBackgroundTask within UpdateSettings.

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
