### ISSUE TITLE
Formatting of member function section is broken.

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-related#137]
More broken in production than the github preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6b0a68-57da-adf4-6d4c-d2140808e55c
* Version Independent ID: 92255e0b-929a-261f-978a-5eecd8417896
* Content: [winrt::handle_type struct template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/handle-type)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/handle-type.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/handle-type.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rpavlik, thanks for finding this issue. I've just published a fix to the topic, so I'll go ahead and close this issue now.

Thanks!
Steve
