### ISSUE TITLE
method name generation algorithm is incorrect

### ISSUE THREAD

**Issue by LarryOsterman** [MicrosoftDocs/winrt-related#14]
It's <base method name> for the first entry. Subsequent entries are the first numeric value which has not already been used.

So you have LineHeightProperty, then LineHeightProperty2, LineHeightProperty3, etc.

If you have LineHeightProperty and LineHeightProperty3, then the overloads of LineHeightProperty will be named: LineHeightProperty, LineHeightProperty2, and LineHeightProperty4 (since LineHeightProperty3 already exists).

The same algorithm applies to interface names.

**Comment by stevewhims** [comment]
Hi, Larry, thanks for the feedback/info. I'll work with you via email to make this correction and have it reviewed. In the meantime, I'll close this issue work item. Thanks! ~Steve

**Comment by stevewhims** [comment]
Removing link to topic now that this has been fixed.
