### ISSUE TITLE
Data type field is incorrect

### ISSUE THREAD

**Issue by vors** [MicrosoftDocs/winrt-related#142]
This Data type also allows things like "Directory", which does not conform to the * or extension pattern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2976c996-a467-d177-d477-123070d6cef9
* Version Independent ID: b98d70a2-4b7f-e984-fdae-d3c78f30b20e
* Content: [desktop5:ItemType - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop5-itemtype#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop5-itemtype.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop5-itemtype.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by AliveDevil** [comment]
This is documented in the msix-packaging-Repo (https://github.com/microsoft/msix-packaging, `Resources/AppxPackaging/Manifest/Schema`) (or F12 (Go To Definition) from within Visual Studio) following way:
* In 2017 / DesktopManifestSchema_v4.xsd the FileExplorerContextMenus is defined with
```
<xs:complexType name="CT_FileExplorerContextMenus">
  <xs:sequence minOccurs="0" maxOccurs="10000">
    <xs:element name="ItemType" type="CT_ItemType" minOccurs="0"/>
    <xs:element ref="desktop5:ItemType" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
```
Source https://github.com/microsoft/msix-packaging/blob/master/resources/AppxPackaging/Manifest/Schema/2017/DesktopManifestSchema_v4.xsd#L42-L47
* The `desktop5:ItemType` is defined in `2018 / DesktopManifestSchema_v5.xsd` with following attribute:
```
<xs:attribute name="Type" type="ST_FileTypeOrStarWithDirectory" use="required"/>
```
Source: https://github.com/microsoft/msix-packaging/blob/master/resources/AppxPackaging/Manifest/Schema/2018/DesktopManifestSchema_v5.xsd#L41
* This refers to `ST_FileTypeOrStarWithDirectory` in the same manifest being defined as
```
<xs:simpleType name="ST_FileTypeOrStarWithDirectory">
  <xs:restriction base="t:ST_NonEmptyString">
    <xs:pattern value="(\*|(\.[^.\\]+))"/>
    <xs:pattern value="Directory"/>
    <xs:pattern value="Directory\\Background"/>
    <xs:maxLength value="64"/>
  </xs:restriction>
</xs:simpleType>
```

So: 2017 desktop4-Schema has been updated to reflect 2018 desktop5-Schema with `desktop5:ItemType` handling `*`, any combination of `*.<Extension>` as well as `Directory` and `Directory\\Background`.

**Comment by vors** [comment]
@AliveDevil thank you for the references!

I will keep the issue open because I think the https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop5-itemtype.md still needs to be updated.

**Comment by mcleanbyron** [comment]
Thanks for bringing these issues to our attention. I updated the [desktop5:ItemType](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop5-itemtype#attributes) with info about the supported "Directory" and "Directory\Background" values, and I fixed several other related minor issues. If you see additional problems with this content, please feel free to reopen this issue or open a new one.
