### ISSUE TITLE
Document AddRef call

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-related#144]
It's not clear from the documentation whether this function has the effect of calling AddRef on the com object. According to my testing, it does indeed call AddRef. Perhaps this cold be added to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 917008b0-6ab2-5553-7951-7f05f26f97c2
* Version Independent ID: 94698784-6290-796c-f952-c9c3e86cf7aa
* Content: [winrt::copy_from_abi function (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/copy-from-abi)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/copy-from-abi.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/copy-from-abi.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing the issue, @benstevens48, I've published additional info in the topic (in the main description and in the description for the *value* parm. You're right, AddRef is called for pointers. Note that you can also hit F12 on a function and you'll be taken to the implementation right in winrt/base.h, if you're curious about any details.

I'll go ahead and close this issue now.

Thanks again!
Steve
