### ISSUE TITLE
Update screenshot to display new WinUI logo

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-related#145]
Since WinUIs logo was refreshed, this change should also be displayed in the screenshot of the nuget list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716795b6-2bcc-8ff5-f999-5e1de88a04e0
* Version Independent ID: 590dd55a-a259-e6dc-972e-531dda080cd9
* Content: [NuGet package list for the Windows UI Library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/nuget-packages)
* Content Source: [winrt-related-src/toolkits/winui/nuget-packages.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/nuget-packages.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jesbis** [comment]
Great suggestion! We just updated the screenshot.
