### ISSUE TITLE
Update screenshot to display new WinUI logo

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-related#146]
Since WinUIs logo was refreshed, this change should also be displayed in the screenshot of the nuget list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jesbis** [comment]
Great suggestion! We just updated the screenshot.
