### ISSUE TITLE
How to return an array async

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-related#147]
In the final section of this page, it says that returning `Windows.Foundation.IAsyncOperation<Int32[]>` is invalid. It then says see `IReferenceArray<T>`, but if I try to use this type it says it can only be used within a `declare` block, and I have no idea what that is. I would like to asynchronously return a byte array, but I have no idea how to do it. Is it possible? Currently I have to create a simple wrapper class to hold the bytes with a DetachBytes method to get the bytes synchronously (via a swap operation so it doesn't make a copy). If this is really the only way, it would be useful if there was a generic `ArrayWrapper<T>` class that had a `DetachArray()` method or something.
 
**Edit**
Actually, I am really trying to return an array of some non-primitive type - in my case Windows.UI.Color. I realise that I can actually return a byte array inside a PropertyValue, so what I'm looking for is the same functionality for an array of arbitrary values, or at least structs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @benstevens48, thanks for raising the issue. I'm currently researching the answer, and also seeking help internally. :) I'll get back to you when I have something. ~Steve

**Comment by stevewhims** [comment]
@benstevens48, I've updated the topic with a link to [Returning an array asynchronously](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency-2#returning-an-array-asynchronously), which shows a technique that doesn't involve **IReferenceArray**.

**Comment by benstevens48** [comment]
Thanks for the update. However, I think this is a bit inefficient for large arrays because, according to my testing, both boxing and unboxing the array creates a copy of it. Also, it doesn't cover the case of arrays of non-primitive types, like the case I mentioned with `Windows.UI.Color` as the array entry type. Do you think the best solution is the one I mentioned, i.e. to create simple wrapper class to hold the bytes with a DetachBytes method to get the bytes synchronously (via a swap operation so it doesn't make a copy)? If so, it might be nice to have a built in version of this like an `ArrayWrapper<T>` class. Maybe that's what `IReferenceArray` was meant to do (I still have no idea how to use that)?

**Comment by stevewhims** [comment]
Hi, @benstevens48. For the remaining questions, it might be a good idea to seek support/advice from the feature team, and you can find them monitoring questions here: https://stackoverflow.com/questions/tagged/c%2b%2b-winrt. But feel free to come back here any time, with updates or corrections that you feel need to be made to the docs.

Sorry I can't offer more direct help with your specific questions here.

~Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve
