### ISSUE TITLE
Developers who are not in the Windows organization should never use the [contract] attribute. 

### ISSUE THREAD

**Issue by LarryOsterman** [MicrosoftDocs/winrt-related#15]
The [contract] attribute is an artifact of the mechanisms that the Windows organization uses to implement our versioning story and manage the process of creating multiple editions of Windows. There is no scenario for a user outside the Windows organization to use contract attributes. The reason you see this in the auto-converted IDL files is because the base IDL files for those are from the internal-to-windows sources.

**Comment by stevewhims** [comment]
Hi, Larry, thanks for the feedback/info. I'll work with you via email to make this correction and have it reviewed. In the meantime, I'll close this issue work item. Thanks! ~Steve

**Comment by stevewhims** [comment]
Removing link to topic now that this has been fixed.
