### ISSUE TITLE
The appearance of some the controls has become worse.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [MicrosoftDocs/winrt-related#152]
<!DOCTYPE html>
<html>
	<body>
		<p>
			Except for the ticks in the check-boxes being smaller, the "_CheckBox and RadioButton Visual Update_" has caused the appearance of the previously mentioned elements to be significantly less pleasant.
		</p>
	</body>
</html>

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86134b1e-18c2-4945-287c-0aec08e1db21
* Version Independent ID: dc12a423-16f3-0c19-d433-b0e5f4002733
* Content: [WinUI 2.2 Release Notes - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.2#feedback)
* Content Source: [winrt-related-src/toolkits/winui/release-notes/winui-2.2.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/release-notes/winui-2.2.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @predavid
* Microsoft Alias: **mijacobs**

**Comment by stamminator** [comment]
Agreed. The contrast of checked boxes is worse, the indeterminate checkbox is confusing and non-standard, and that selected radio button looks confusing. It looks like the `:hover` or `:active` state in HTML/CSS, not an item that's already selected. More pretty, but less intuitive, which is a net loss in my book.

**Comment by RokeJulianLockhart** [comment]
<!DOCTYPE html>
<html>
	<body>
		<blockquote cite="http://github.com/flathub/backend/issues/26#issue-776424623">
			Agreed. The contrast of checked boxes is worse, the indeterminate checkbox is confusing and non-standard, and that selected radio button looks confusing. It looks like the :hover or :active state in HTML/CSS, not an item that's already selected. More pretty, but less intuitive, which is a net loss in my book.
		</blockquote>
		<p>
			<a href="http://github.com/BEEDELLROKEJULIANLOCKHART">@BEEDELLROKEJULIANLOCKHART</a>, is thankful for the articulation of <a href="http://github.com/stamminator">@STAMMINATOR</a> because that is what <a href="http://github.com/BEEDELLROKEJULIANLOCKHART">@BEEDELLROKEJULIANLOCKHART</a> did desire statement of.
		</p>
	</body>
</html>

**Comment by chigy** [comment]
For feature request and feedback, please post your input to https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose
