### ISSUE TITLE
No tutorials, no video how to start

### ISSUE THREAD

**Issue by SmartInteractiveGroup** [MicrosoftDocs/winrt-related#156]
No tutorials, no video how to start also: Do you understand it?  “The main difference is that WinUI 3 APIs are in the Microsoft.UI namespace instead of the Windows.UI namespace, so you might need to update the namespaces when copying and pasting sample code.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1364dd22-66a3-a03b-85a9-eb197698f8e8
* Version Independent ID: b56792ee-a5a6-0d94-75cf-6047382364b5
* Content: [WinUI 3.0 Alpha (November 2019) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/#feedback)
* Content Source: [winrt-related-src/toolkits/winui3/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui3/index.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jesbis
* Microsoft Alias: **kbridge**

**Comment by SmartInteractiveGroup** [comment]
This is not an issue. Just a comment.

**Comment by jesbis** [comment]
Thanks! We'll definitely aim to have more tutorials once WinUI is closer to release.

In the meantime nearly all of the tutorials and examples for UWP will work:

https://docs.microsoft.com/windows/uwp/get-started/create-uwp-apps 

Except for the namespace difference as noted.
