### ISSUE TITLE
const ref / ref const - Whats right?

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-related#162]
There is a code sample with "const ref" here
https://github.com/MicrosoftDocs/winrt-related/blame/docs/winrt-related-src/midl-3/intro.md#L773
And there is a sample code with "ref const" here
https://github.com/MicrosoftDocs/winrt-related/blame/docs/winrt-related-src/midl-3/intro.md#L834

Which is the correct way of using this parameter?
Neither of which does work with Int64 as datatype:
```
void Test(const ref Int64 asd);

MIDL2025	[msg]syntax error [context]: expecting a type specification or a storage specifer or a type qualifier or RuntimeClassAccessory near "ref"
```
```
void Test(ref const Int64 asd);

MIDL4035	[msg]The [in] parameter has a pointer type that is not valid. [context]: __int64 [ Parameter 'asd' of Procedure 'Test' ( Interface 'IInterface' ) ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @AliveDevil, thanks for filing this issue. I've published a fix to the topic, so that's live now. The answer is that `ref const` is correct. You only use that with large value types such as **Matrix4x4**. You don't need it for integral types such as Int64, and in fact it's not valid syntax to do so.

Thanks!
Steve

**Comment by jehumb-havok** [comment]
What's a "large value"? This is a struct isn't it? If this generates an error then this is not a performance optimization, and so this should be called out as such in the docs and here, not some handwavy "large value".
