### ISSUE TITLE
Please clarify and emphasize the status of UWP development with .NET Core 3 and C# 8

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winrt-related#164]
The current docs vaguely states that .NET Core is to be supported in the future, but doesn't clarify that C# 8 isn't supported, and doesn't redirect to a roadmap where we can learn about the schedule.
Please update the docs.

Related: #163.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1364dd22-66a3-a03b-85a9-eb197698f8e8
* Version Independent ID: b56792ee-a5a6-0d94-75cf-6047382364b5
* Content: [WinUI 3.0 Alpha (November 2019) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/)
* Content Source: [winrt-related-src/toolkits/winui3/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui3/index.md)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jnm2** [comment]
@weitzhandler Does https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md answer your questions?

**Comment by weitzhandler** [comment]
Thank you. Kind of. Is there already .NET Core and C#8 support for WinUI apps at the moment with WinUI 3α?

**Comment by jnm2** [comment]
Found the answer by following a link from the roadmap:

> **At this time, C# 8 and .NET Core are not supported.** Future updates are planned that include support for other project types and languages, including .NET Core, C# 8, and the desktop (win32) app model.

https://docs.microsoft.com/en-us/uwp/toolkits/winui3/#alpha-limitations-and-known-issues

**Comment by weitzhandler** [comment]
Oops. Missed it, sorry.
That does answer my question.
Thanks for your effort clarifying this.
