### ISSUE TITLE
This needs to be updated to note that the updater does not currently work with traditional Desktop / Taskbar shortcuts

### ISSUE THREAD

**Issue by stephenjeffreywhite** [MicrosoftDocs/winrt-related#166]
As noted in the title, the OnLaunch settings for ShowPrompt and UpdateBlocksActivation do not get used if you open up the app using a traditional Desktop  / Taskbar shortcut, as was noted in this issue on Github:

https://github.com/MicrosoftDocs/msix-docs/issues/59

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dede6dc-742e-860d-4286-72bbd1406ad4
* Version Independent ID: 5373496b-932f-8c48-723e-2f7b8e27a107
* Content: [OnLaunch - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch#feedback)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-onlaunch.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-onlaunch.md)
* Product: **jken**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I added some remarks and info to the attribute descriptions to clarify this behavior.
