### ISSUE TITLE
Use same "Name" for related Install/Repair/Uninstall actions.

### ISSUE THREAD

**Issue by JeremyRobinson** [MicrosoftDocs/winrt-related#167]
UninstallAction will only be run if an Install (or Repair) action has been run.  The system uses the "Name" property to track this state.  For this reason, it important that the InstallAction/RepairAction/UninstallAction have the same Name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d0afcc-b589-f535-9b93-d6bd9dd9b015
* Version Independent ID: 25c0c704-75c5-991c-9b68-e85c6cd7e45b
* Content: [desktop6:CustomInstall - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall.md)
* Product: **jken**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I added some remarks to this article to clarify this behavior.
