### ISSUE TITLE
Name attribute for UninstallAction should be shared with related InstallAction and RepairAction elements.

### ISSUE THREAD

**Issue by JeremyRobinson** [MicrosoftDocs/winrt-related#168]
UninstallAction will only run if an InstallAction or RepairAction of the same name has been run.  If related actions do not use the name Name, then it is possible that UninstallAction will not be executed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07dafe8b-911d-9323-c3cd-fa87a76b3770
* Version Independent ID: f8f0cc98-6978-bf14-5e3d-84cda0b8e3a0
* Content: [desktop6:UninstallAction - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-uninstallaction)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-uninstallaction.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-uninstallaction.md)
* Product: **jken**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I added some info to the "Name" description to clarify this behavior.
