### ISSUE TITLE
Where on disk do the SDK API contracts reside?

### ISSUE THREAD

**Issue by dkemlage** [MicrosoftDocs/winrt-related#17]
I am using SandCastle (originally created by Microsoft and now managed as an open source project: https://github.com/EWSoftware/SHFB) to document a UWP based API. The problem is that SandCastle cannot figure out where the Windows Universal Platform SDK API contracts live on disk to complete its reflection-type interrogation. I am particularly interested as to where the following Assembly references can be found on disk: Windows.Foundation.FoundationContract, version=3.0 Windows.Foundation.UniversalApiContract, version=5.0. I have the Windows 10 Fall Creators Update Universal SDK (version 10.0.16299.0) installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afdf49d-a4d3-2c25-5146-a74b31e45819
* Version Independent ID: 658615f6-b07b-3186-d042-6fb4b52e0640
* Content: [Windows Universal Platform SDK API contracts - UWP app developer](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk#feedback)
* Content Source: [winrt-related-src/extension-sdks/windows-universal-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-universal-sdk.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by dkemlage** [comment]
I believe I found them at:
C:\Program Files (x86)\Windows Kits\10\References\10.0.16299.0\Windows.Foundation.UniversalApiContract\5.0.0.0\Windows.Foundation.UniversalApiContract.winmd
C:\Program Files (x86)\Windows Kits\10\References\10.0.16299.0\Windows.Foundation.FoundationContract\3.0.0.0\Windows.Foundation.FoundationContract.winmd

**Comment by knicholasa** [comment]
Hi Don, 

I'm looking through some issues that were recently assigned to me and came across this. Thanks for your detailed write up and sorry for the long response time! I hope the solution you found worked!

I encourage you to check out our development resources if you have more questions like this in the future (https://developer.microsoft.com/windows/support) as feedback here is meant primarily for documentation issues. 

Nick
