### ISSUE TITLE
Types typo?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/winrt-related#172]
"... used only by certain *types desktop of PC games* ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb896e70-968c-ea71-37b0-dda349d9543b
* Version Independent ID: 204420b4-33fc-3e1b-da55-56c0dac1534a
* Content: [desktop6:MutablePackageDirectory - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectory)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectory.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectory.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. We have fixed this typo and the updated article will be published later today.
