### ISSUE TITLE
What should we name the document?

### ISSUE THREAD

**Issue by edwardskrod** [MicrosoftDocs/winrt-related#174]
According to the Microsoft Docs, we should name it "StoreManifest.xml."   Does it matter what we name the document?  Are there downstream repercussions if it is named something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b048525e-5b60-18fc-4bdb-7222027769ea
* Version Independent ID: 54dbad6e-c837-7901-0e21-e9ec29433997
* Content: [StoreManifest schema - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/storemanifest/storemanifestschema2015/schema-root#feedback)
* Content Source: [winrt-related-src/schemas/storemanifest/storemanifestschema2015/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/storemanifest/storemanifestschema2015/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to submit an issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
