### ISSUE TITLE
PC games only?

### ISSUE THREAD

**Issue by leonardgoobar** [MicrosoftDocs/winrt-related#179]
"This element is currently INTENDED to be used only by desktop PC games that are packaged in an MSIXVC container."

But is it actually restricted only to games?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67391c9-bd07-e5be-9398-9caab1f671fa
* Version Independent ID: ea663dff-b7e7-36a4-884e-c75fac4fbb88
* Content: [desktop6:InstallAction - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-installaction#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-installaction.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-installaction.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. Yes, this element is currently only supported in for the types of PC games described in the text you quoted. The remarks section of this article indicates that this element requires the customInstallActions capability, and per the links article this capability is "...designed for certain types of desktop PC games that are published by Microsoft and our partners. It will not be granted for other scenarios." In other words, this element isn't supported for use by general 3rd party developers.
