### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by beamazingbiz** [MicrosoftDocs/winrt-related#18]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f322ef7-cc3b-d810-5d27-a36183676640
* Version Independent ID: f5efc866-2cf9-4473-c9a7-7525817da6a1
* Content: [Device Family Extension SDKs and API contracts - UWP app developer](https://docs.microsoft.com/en-us/uwp/extension-sdks/)
* Content Source: [winrt-related-src/extension-sdks/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/index.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
re: "[Enter feedback here]", looks like an accidental comment. Closing.
