### ISSUE TITLE
Missing doc link

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-related#180]
Missing documentation link for RoIsApiContractPresent and RoIsApiContractMajorVersionPresent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8b23f4-f83b-e5fb-076b-f58e7fa8ec5b
* Version Independent ID: 20a237ef-9a49-1786-f00a-df422f8f07bb
* Content: [APIs present on all Windows 10 devices (grouped by module) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-ro-typeresolution-l1-1-1dll)
* Content Source: [winrt-related-src/win32-and-com/win32-apis.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/win32-and-com/win32-apis.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I added these links to the article: https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-ro-typeresolution-l1-1-1dll
