### ISSUE TITLE
How to add a Content URI so that a web page within a WebView can notify...

### ISSUE THREAD

**Issue by jhwheuer** [MicrosoftDocs/winrt-related#181]
I would like to allow the user to submit a search term from the web page into my UWP app...

The web page itself is stored in 'ms-appx-web:///[SomeFolder]/'. 
The WebView can open it, it executes JavaScript, but when I try to call 'window.external.notify', the JS Engine gives me the error "TypeError: Object doesn't support property or method 'notify'"

I have registered 'ms-appx-web:///[SomeFolder]/' as a Content URI in the app manifest and given it "Allow for web only" access, since the app has access to {Known Folders} (Documents, Photos etc)...

Where am I going wrong here???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c20a74-18a7-a0a3-b828-6d2749151255
* Version Independent ID: 1ac0dc95-48ec-4a3b-4455-b8a0b6f094b2
* Content: [Package manifest schema reference for Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us. This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- First, please make review the [Web view](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/web-view) article to confirm whether your question is answered there or in the samples/resources mentioned in it. Based on your brief description, it sounds like [this section](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/web-view#accessing-the-windows-runtime-in-a-web-view) may be relevant. 
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
