### ISSUE TITLE
incorrect sample for attributes

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/winrt-related#183]
The attribute sample can't compile. There are many things wrong with it:

1. It doesn't seem like `[attributeusage(target_runtimeclass_member)]` is valid:
```
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(22): error MIDL2025: [msg]syntax error [context]: expecting AttributeUsageList near "target_runtimeclass_member"
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(23): error MIDL2026: [msg]cannot recover from earlier syntax errors; aborting compilation
1&gt;Done building project "Win32XamlHost.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

2. If I change this to `[attributeusage(target_runtimeclass)]` i get passed this error and hit this:

```
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(25): error MIDL2025: [msg]syntax error [context]: expecting ) near "classUri"
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(25): error MIDL5074: [msg]the only special keyword that may be used in a custom attribute is "version" [context]: HelpAttribute
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(26): error MIDL2025: [msg]syntax error [context]: expecting a declarator
1&gt;D:\dev\src\WinUIPrototype\Win32XamlHost\XamlApplication.idl(26): error MIDL5063: [msg]the custom attribute definition contains a field th
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @stevenbrix, thanks for filing this issue. You're right, that example was showing the wrong syntax. I've tested and published a correction to it, and that's live now.

I'll go ahead and close the issue.

Thanks again!
Steve
