### ISSUE TITLE
Can this template be parameterized on a user-defined type?

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-related#185]
The documentation notes 2 concrete instantiations of this template (`handle` and `file_handle`), but doesn't make it clear, whether this template can be used to declare RAII wrapper types parameterized on user-defined types. My concrete use case is adding ownership semantics to SQLite handles.

To do this with confidence we would need to know the requirements placed on the traits type (the template type argument `T`). Those are nowhere to be found, and we have to rely on compiler diagnostics to deduce the traits type's anatomy.

The question is two-fold:

* Can we use `handle_type` as a template to model our custom RAII wrappers? (`handle_type` is declared in the public-facing `winrt` namespace after all)
* If so, can we get the required documentation on the traits types' requirements published and linked to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6b0a68-57da-adf4-6d4c-d2140808e55c
* Version Independent ID: 92255e0b-929a-261f-978a-5eecd8417896
* Content: [winrt::handle_type struct template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/handle-type#handle_typehandle_type-constructor)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/handle-type.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/handle-type.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tim-weis, thanks for filing this issue. I've updated the topic with info that hopefully helps with your scenario.

Thanks again,
Steve
