### ISSUE TITLE
Add documentation for "makeappx build" schema

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#186]
I don't know of anywhere better to put this, so I might as well ask here.

The PowerToys repository makes use of a [packaging layout XML file](https://github.com/microsoft/PowerToys/blob/master/installer/MSIX/PackagingLayout.xml) that defines an MSIX bundle containing exactly one MSIX package. From reading the source, it appears that this XML file can be used to create far more complex packages and bundles. However, neither the format of this file nor the parameters to "makeappx build" are documented anywhere. Could this please be rectified? I'm looking to use this feature to build an MSIX package in situations where wapproj cannot be used (for example, when using JetBrains Rider instead of Visual Studio). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c20a74-18a7-a0a3-b828-6d2749151255
* Version Independent ID: 1ac0dc95-48ec-4a3b-4455-b8a0b6f094b2
* Content: [Package manifest schema reference for Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I believe the information you're looking for is provided in the [Package creation with the packaging layout](https://docs.microsoft.com/en-us/windows/msix/package/packaging-layout) article in the MSIX docs. If that article doesn't contain the information you're looking for, please open a new issue in that article.
