### ISSUE TITLE
Document winrt::is_guid_of and when to specialize it

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/winrt-related#192]
Developers are apparently expected to specialize the `winrt::is_guid_of` function template when they implement two non-WinRT COM interfaces of which one derives from the other. However, `winrt::is_guid_of` is not currently documented here. Please document it, add an example of when to specialize it, and describe how to avoid C++ ODR violations (e.g. ensure that all definitions of the specialization list the base interfaces in the same order).

* [How do I use C++/WinRT to implement a classic COM interface that derives from another classic COM interface? | The Old New Thing](https://devblogs.microsoft.com/oldnewthing/20200424-00/?p=103702)
* [C++/WinRT: Improved support for COM-style single interface inheritance by kennykerr · Pull Request #107 · microsoft/xlang](https://github.com/microsoft/xlang/pull/107)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b3f5b-e729-300a-eb81-402648520ff3
* Version Independent ID: 40daa692-e9a1-2e27-0c10-c6baf69bc453
* Content: [winrt namespace (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/winrt)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/winrt.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/winrt.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @KalleOlaviNiemitalo, and thanks for filing this issue. I've added a work item to my backlog to take care of this.

Thanks again!
Steve

**Comment by KalleOlaviNiemitalo** [comment]
I wonder whether the `is_guid_of` specialization also needs to list `IDispatch` when implementing a `dual` interface or a `dispinterface`. That seems an uncommon scenario, though. Event interfaces are generally not `dual`, except SENS interfaces such as [ISensLogon](https://docs.microsoft.com/windows/win32/api/sensevts/nn-sensevts-isenslogon), which can nowadays perhaps be replaced with [WTSRegisterSessionNotification](https://docs.microsoft.com/windows/win32/api/wtsapi32/nf-wtsapi32-wtsregistersessionnotification).

**Comment by stevewhims** [comment]
Just a heads up that I'm closing this GitHub issue because I'm tracking it internally in my work items (I don't want to track it, and count it, twice). You'll still be able to leave comments here, and the comments so far will be very helpful. I'll come back and (possibly reopen and) comment when I have a resolution for my work item.

Thanks!
Steve

**Comment by stevewhims** [comment]
Currently working on this, so reactivating.

**Comment by stevewhims** [comment]
Thanks, @KalleOlaviNiemitalo, I've actioned this issue now. Please see [Implement a COM interface that derives from another](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-coclasses#implement-a-com-interface-that-derives-from-another), and [winrt::is_guid_of function template](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/is-guid-of).

-Steve
