### ISSUE TITLE
Not able to use CustomInstall

### ISSUE THREAD

**Issue by ChrisAnd1998** [MicrosoftDocs/winrt-related#194]
Hi,

I'm trying to create a UninstallAction but, after packing the appx i can't install it.
It gives me this error:

> App installation failed with error message: error 0x80080204: While preparing to process the request, the system failed to register the windows.customInstall extension due to the following error: The Appx package's manifest is invalid.

AppxManifest:
```
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" 
xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" 
xmlns:desktop6="http://schemas.microsoft.com/appx/manifest/desktop/windows10/6" 
xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"  
IgnorableNamespaces="uap desktop6 rescap" >

  <Identity Name="40210ChrisAndriessen.FalconX" Publisher="CN=8AB18DA5-65D5-493C-BD78-9F4467A7CDE8" Version="1.5.5.0"  />
  <Properties>
    <DisplayName>TaskbarX</DisplayName>
    <PublisherDisplayName>Chris Andriessen</PublisherDisplayName>
    <Description>Reserved</Description>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Resources>
    <Resource Language="en-us" />
  </Resources>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19041.0" />
  </Dependencies>
  <Capabilities>
  <rescap:Capability Name="runFullTrust" />
   <rescap:Capability Name="customInstallActions"/>
  </Capabilities>
 
 <Applications>
    <Application Id="TaskbarX" Executable="Release\TaskbarX.exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements BackgroundColor="transparent" DisplayName="TaskbarX" Square150x150Logo="Assets\StoreLogo-150.png" Square44x44Logo="Assets\StoreLogo-44.png" Description="TaskbarX">
        <uap:DefaultTile Wide310x150Logo="Assets\StoreLogo.png" Square310x310Logo="Assets\StoreLogo.png" Square71x71Logo="Assets\StoreLogo-71.png" />
      </uap:VisualElements>
    </Application>
	
	<Application Id="TaskbarXGUI" Executable="Release\TaskbarX Configurator.exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements BackgroundColor="transparent" DisplayName="TaskbarX Configurator" Square150x150Logo="Assets\StoreLogo2-150.png" Square44x44Logo="Assets\StoreLogo2-44.png" Description="TaskbarXGui">
        <uap:DefaultTile Wide310x150Logo="Assets\StoreLogo2.png" Square310x310Logo="Assets\StoreLogo2.png" Square71x71Logo="Assets\StoreLogo2-71.png" />
      </uap:VisualElements>
    </Application>
	
	
  </Applications>
  
     <Extensions>
    <desktop6:Extension Category="windows.customInstall">
      <desktop6:CustomInstall Folder="UninstallAPPX">
        <desktop6:UninstallActions>
          <desktop6:UninstallAction File="CleanTaskbarX.exe" Name="Clean TaskbarX" Arguments="none" />
        </desktop6:UninstallActions>
      </desktop6:CustomInstall>
    </desktop6:Extension>
  </Extensions>
	  
	  
 
</Package>
```

On the end the CleanTaskbarX.exe should kill the TaskbarX process and remove it's taskschedule.
Before uninstalling.

**Comment by TopperDEL** [comment]
I have the same problem with an app here - is there any news or something available? @mikben

**Comment by mcleanbyron** [comment]
I'm sorry you're encountering problems trying to use this element. Here are a couple of things you can check:

- The desktop6:CustomInstall element is [supported on Windows 10, version 1903](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/what-s-changed-in-windows-10#windows-10-build-18362-version-1903) and later. Make sure you're trying to use this on a supported OS version.
- This element requires the 'customInstallActions' restricted capability. It doesn't look like the manifest example at the start of this issue thread includes a declaration for this capability, so make sure your manifest has this. See the [example in the article](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall#examples) for more details.

If neither of these suggestions help, I recommend that you post your question to the [MSIX Tech Community](https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX): Lots of MSIX packaging experts can help you with questions there.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by TopperDEL** [comment]
Sorry to reopen this topic. @mcleanbyron Can you confirm that the CustomInstall-Extension is usable by anybody or that the note in the doc is still valid:

_This element is currently intended to be used only by certain types of desktop PC games that are published by Microsoft and our partners._

I've placed a specific question in the MSIX-Deployment techcommunity board here - in case you want to answer there:
https://techcommunity.microsoft.com/t5/msix-deployment/app-manifest-using-custominstall/m-p/1502626/highlight/false#M534

Your comment above sounds like "it should work" and "is allowed" but the reality shows it isn't.

Thank you!

**Comment by mcleanbyron** [comment]
Sorry, I missed that statement in the article and that is the most important piece of information. Yes, per that statement (and the fact that this requires the 'customInstallActions' restricted capability), most developers cannot use this extension. This is currently only supported for certain Microsoft partners who are building desktop PC games. In other words, if you can use this extension, you would already know it. Apologies for any confusion from my earlier reply.

**Comment by TopperDEL** [comment]
That's ok @mcleanbyron - at least I know now that it will not work and therefore can concentrate on a different solution to this.
Thank you!

**Comment by alexfotios** [comment]
You have to also add the repair and uninstall actions for the manifest to be valid. Like this:

`  <Extensions>
    <desktop6:Extension Category="windows.customInstall">
      <desktop6:CustomInstall Folder="assets\vpn\tap-windows">
        <desktop6:InstallActions>
          <desktop6:InstallAction File="some.exe" Name="TAP_9" />
        </desktop6:InstallActions>
        <desktop6:RepairActions>
          <desktop6:RepairAction File="some exe" Name="TAP_9" />
        </desktop6:RepairActions>
        <desktop6:UninstallActions>
          <desktop6:UninstallAction File="seme.exe" Name="TAP_9" Arguments="remove" />
        </desktop6:UninstallActions>		
      </desktop6:CustomInstall>
    </desktop6:Extension>
  </Extensions>  `

Still custominstall actions can only be used by certain MSFT partners only as specified in the docs here: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall

**Comment by TopperDEL** [comment]
It's a while ago that I was in that topic. But as far as I remember Microsoft simply does not allow it to be used by 3rd party developers. So even if the Manifest is technically valid, the Store would not approve it.
If you know more then me let me now - I would be very happy to bring that app with that feature to the store!

**Comment by alexfotios** [comment]
> It's a while ago that I was in that topic. But as far as I remember Microsoft simply does not allow it to be used by 3rd party developers. So even if the Manifest is technically valid, the Store would not approve it.
> If you know more then me let me now - I would be very happy to bring that app with that feature to the store!

Yeah, exactly, if you not in the shortlist of partners you simply can't use it

**Comment by HO-COOH** [comment]
I came across this issue. I noticed there is a little note [here](https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#custom-capabilities) stating that it's possible to use CustomInstall if `Microsoft.classicAppInstaller_8wekyb3d8bbwe` is declared. So I added that, but I got a different error
```
App installation failed with error message: error 0x80070002: While preparing to process the request, the system failed to register the windows.capability extension due to the following error: The system cannot find the file specified.
```
This might indicate this could work, but somehow I package my custom exe incorrectly. (I simply throw that exe into the project, and mark it as Content).
And this is the relevant part of my `package.manifest`
```xml
    <Extensions>
        <desktop6:Extension Category="windows.customInstall">
            <desktop6:CustomInstall Folder="MyInstallers" desktop8:RunAsUser="true">
                <desktop6:InstallActions>
                    <desktop6:InstallAction File="ConsoleCpp.exe" Name="Test"/>
                </desktop6:InstallActions>
                <desktop6:RepairActions>
                    <desktop6:RepairAction File="ConsoleCpp.exe" Name="Test"/>
                </desktop6:RepairActions>
                <desktop6:UninstallActions>
                    <desktop6:UninstallAction File="ConsoleCpp.exe" Name="Test"/>
                </desktop6:UninstallActions>
            </desktop6:CustomInstall>
        </desktop6:Extension>
    </Extensions>
  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
      <rescap:Capability Name="customInstallActions"/>
      <uap4:CustomCapability Name="Microsoft.classicAppInstaller_8wekyb3d8bbwe"/>
  </Capabilities>
```
My app is only intended for internal use, and will not publish to store. Is there any hope for that?

**Comment by psycorp** [comment]
Advanced installer seem to have gotten it working in their later YouTube video.

https://www.youtube.com/watch?v=2kbPLtwGAfU

They appear to be setting customInstallActions and Microsoft.classicAppInstaller_8wekyb3d8bbwe capabilities as can be seen when they install the MSIX package with a custom redistributable inside it.

I've been trying to get this going on and off for ages at it would be very useful.
