### ISSUE TITLE
Didn't clearly mention what minimum OS versions does WinUi-2.4 supports and what visual studio version needed to use WinUi 2.4?

### ISSUE THREAD

**Issue by rahulkps23** [MicrosoftDocs/winrt-related#196]
It is not clearly mentioned anywhere what minimum OS version(like 1703 version) does WinUi-2.4 supports.
Didn't mention whether WinUi-2.4  and WinUI-2.3 supports from version 1703 or not, or is there a difference(eg: winui 2.4 currently won't support 1703 etc)?
Whether all controls excluding animations etc that depend on composition layer(see the attached image for reference) work same on any OS version or will be still any dependency on OS for look, feel, working?
We know that as per winui 2.x series only the 'windows.ui.xaml' that comes with OS is made as nuget package and given, but the animations, graphics etc which depend on 'windows.ui.composition' will still depend on OS version we are using. And we know that from WinUi-3 even this 'windows.ui.composition' layer will also be moved to nuget package and will be made OS independent.
But we want clear documention on whether the normal controls which previously use to depend on 'windows.ui.xaml'(which are now made nuget package) work same on lower OS versions(like 1703) also or not? What is the minimum OS version that winui 2.4 supports?.
Got this doubt because the [Xaml contol gallery sample(which is using winui 2.4)](https://github.com/microsoft/Xaml-Controls-Gallery) is not installing on 1703 version systems. If WinUi-2.4 supports 1703 version why is it not installing?(when i tried to install this 'Xaml contol gallery' on 1703 system through appx file, it throwed a error saying "you need minimum os version of 1803 to install this", this raised this doubt in me)
![Screenshot (135)](https://user-images.githubusercontent.com/29331748/81606002-f5e34300-93ef-11ea-97e1-f9a2169a290c.png)

Also, please tell clearly whether WinUi 2.4 will work on visual studio 2017 or not? Or only visual studio 2019 is needed?(got this doubt because when tried to use winui 2.4 in visual studio 2017, it throwed error in app.xaml. Whereas it worked fine in visual studio 2019).

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @rahulkps23 - I believe this issue has been addressed through the version selector we added to the WinUI API reference a few months ago. See https://docs.microsoft.com/en-us/uwp/api/overview/winui/ and check the version dropdown at the top of the main TOC.

Please open a new issue in the repo for that content if still not satisfactory.
