### ISSUE TITLE
Namespace URL is not accessible.....

### ISSUE THREAD

**Issue by tuttipazzo** [MicrosoftDocs/winrt-related#197]
This link is not found:

http://schemas.microsoft.com/appx/manifest/uap/windows10/3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ce8a68-18ba-b0fa-f575-27d2aa93fd38
* Version Independent ID: 0629c9c3-2c48-4945-8ca3-d812283eb868
* Content: [uap3:AppExecutionAlias - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-appexecutionalias#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-appexecutionalias.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-appexecutionalias.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for your feedback.

Although it looks like a web-accessible URL, this is just a namespace name that Microsoft has devised to uniquely identify XAML elements.
