### ISSUE TITLE
Typo: </com:Extension> should be </com2:Extension>

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/winrt-related#198]
Typo: End tag </com:Extension> should be </com2:Extension>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7534a699-02b1-dc1f-5fce-3592e0d3cf24
* Version Independent ID: 82f555ea-477f-b127-aab9-b302e0a82d22
* Content: [com2:Extension (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com2-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com2-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com2-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
Thanks for reporting this! I have just fixed the issue, and it should be published to the live docs site shortly.
