### ISSUE TITLE
What is uap6:AllowExecution used for?

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#20]
Title really says it all. Why would you want to use this element in your AppX manifest, if it renders that AppX seemingly useless? Some context would be helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19e5a49-35c4-a65a-7145-d195a7eb1fbc
* Version Independent ID: f5a2d6c8-faae-eeae-13c0-8d6e8093196f
* Content: [uap6:AllowExecution - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-allowexecution)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap6-allowexecution.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap6-allowexecution.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
@wjk This is used for more complex packaging scenarios. For example, asset packages typically don't contain any executable files, so by designating an asset package's "uap6:AllowExecution" element to "false" you can save a bit of time when publishing an app in the Store. See [Introduction to asset packages](https://docs.microsoft.com/windows/uwp/packaging/asset-packages) for more details. I'll add the link to the page and provide more context.

Thanks for your feedback!
