### ISSUE TITLE
Remove/deprecate serverpreview AppX elements?

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#201]
The `http://schemas.microsoft.com/appx/manifest/serverpreview/windows10` namespace has been useless for many years, ever since use of Nano Server in bare-metal scenarios was killed off. Should this deprecation be noted in the docs? Alternatively, since the serverpreview features never left beta on Windows Server, and aren‘t supported at all on Windows 10 AFAIK, these pages could simply be removed instead. They will always be in the Git history if someone for some reason needs them. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b5f587-faab-ab4e-8dd5-e7eda88db6e1
* Version Independent ID: 441983ca-5fb9-56d3-0b7a-982fd5069b76
* Content: [Element Hierarchy - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/root-elements)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/root-elements.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/root-elements.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Hello, sorry for the long delay on this. We were able to confirm with the feature team that there is no danger for existing apps if we delete this content, so the pages for the serverpreview schema have been removed from the public site. They can still be viewed in the git history.
