### ISSUE TITLE
I just sent a ping to the email thread I have going. No response yet, but I'll keep investigating.

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/winrt-related#202]
I just sent a ping to the email thread I have going. No response yet, but I'll keep investigating.

_Originally posted by @stevewhims in https://github.com/MicrosoftDocs/winrt-related/issues/200#issuecomment-649767397_

No updates so far, right?

**Comment by stevewhims** [comment]
Hi, @MarcoEnxuto. I'll respond on Issue #200. Closing this.

Thanks!
Steve
