### ISSUE TITLE
Confusing documentation (copy-paste error?)

### ISSUE THREAD

**Issue by kkotte** [MicrosoftDocs/winrt-related#203]
The 'Data Type' column for the 'Executable' attribute states:

A string between 1 and 256 characters in length that must end with ".exe" and cannot contain these characters: <, >, :, ", |, ?, or *. It specifies the default executable for the extension. _**If not specified, the executable defined for the app is used**_. If specified, the EntryPoint property is also used. If that EntryPoint property isn't specified, the EntryPoint defined for the app is used.

The portion highlighted above (in bold and italicized) is self-referencing an appears incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f9a668-94ee-2da4-ec9e-f5ea1913da58
* Version Independent ID: 21f7b49a-1e82-331b-e602-9100caedb8ff
* Content: [Application (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Thanks for catching this. That sentence was copied over from a package extension but is indeed self-referencing and incorrect in an application extension doc. This sentence has been removed.
