### ISSUE TITLE
Confusing documentation for the c_str() member.

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-related#205]
The `c_str()` member is documented to

> return a null-terminated C-style string version of the characters in the `hstring` object.

The word *"version"* suggests, that a new sequence of characters were constructed and returned. I doubt though, that that's what's happening. It would be more reasonable to assume, that `c_str()` returns a pointer into the `hstring`-controlled memory.

Can the documentation be updated to more accurately explain the behavior of `c_str()`? It would certainly help to know who owns the data pointed to, as well as for how long the returned pointer remains valid.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c48d19-39d2-154f-d94c-ff59eeed7939
* Version Independent ID: f52e84e2-9d1f-ba46-049f-30d89c4a861a
* Content: [winrt::hstring struct (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/hstring)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/hstring.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/hstring.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tim-weis, thanks for filing this issue. I've corrected the topic now. It'd be my understanding that the wrapped HSTRING owns the data, and I'd expect that to be valid as long as the winrt::hstring is.

Thanks!
Steve
