### ISSUE TITLE
Statement that interface inheritance is disallowed apparently contradits with actuality

### ISSUE THREAD

**Issue by fghzxm** [MicrosoftDocs/winrt-related#206]
It is stated that

> ([GitHub](https://github.com/MicrosoftDocs/winrt-related/blob/f16a44175c9f929e2f668422884b4a778c17b3e9/winrt-related-src/winrt-cref/winrt-type-system.md#iinspectable-and-iunknown), [Docs](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#iinspectable-and-iunknown)) All WinRT interfaces must inherit directly from IInspectable

> ([GitHub](https://github.com/MicrosoftDocs/winrt-related/blob/f16a44175c9f929e2f668422884b4a778c17b3e9/winrt-related-src/winrt-cref/winrt-type-system.md#interface-requires), [Docs](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#interface-requires)) Adding new functionality by implementing new interfaces that inherit from existing interfaces (for example, **IFoo2** inherits from **IFoo**) is not allowed

This apparently contradicts with actuality, in which interfaces do [inherit](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.iobservablemap-2?view=winrt-19041) [from](https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.iaudioinputnode2?view=winrt-19041) [other](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.irandomaccessstream?view=winrt-19041) [interfaces](https://docs.microsoft.com/en-us/uwp/api/windows.web.syndication.isyndicationtext?view=winrt-19041), at least at the projection level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01097c38-e018-de14-9b92-3f1c06025dc3
* Version Independent ID: a6277ffd-669e-2f00-80ca-f4f352a48b58
* Content: [The Windows Runtime (WinRT) type system - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system)
* Content Source: [winrt-related-src/winrt-cref/winrt-type-system.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/winrt-cref/winrt-type-system.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by DefaultRyan** [comment]
The official guidance of disallowing interface inheritance is accurate for the type system, and it also [applies to MIDL3](https://docs.microsoft.com/en-us/uwp/midl-3/intro#interfaces), which uses the `requires` keyword.

I don't think we need more here than just a simple note clarifying that language projections may use an inheritance relationship for ease of consumption in the language. But continue to make it clear that this is not interface inheritance in the WinRT type system, nor at the ABI.

Runtimeclasses can use inheritance, but interface inheritance simply isn't a thing, in the context of MIDL authoring.

**Comment by stevewhims** [comment]
Thanks, all! I've updated the docs with Ryan's info, and those changes are now live.

I'll go ahead and close the issue.

Thanks again!
-Steve

**Comment by fghzxm** [comment]
Pardon my annoyance but it looks to me like the docs is now inaccurate in the other direction:

> All WinRT interfaces implicitly require IInspectable; and in turn IInspectable requires IUnknown

but WinRT interfaces do actually _inherit_ from IInspectable (their vtables [physically include IInspectable's](https://github.com/microsoft/cppwinrt/blob/e5e1eaac9bfcca3a7cd68e3cc262bcfa93f405eb/cppwinrt/code_writers.h#L756)), and IInspectable similarly does inherit from IUnknown.
