### ISSUE TITLE
Unclear how the DataFormat elements work

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/winrt-related#207]
I find it unclear how the `DataFormat` elements work, whether the options are predefined or whether it is free-text, whether it resolves to a mime type or something else?

Is there any validation on it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f45d3ab-2548-6281-906e-d8a0b259c20e
* Version Independent ID: e3b3d85c-30df-e9a0-2127-95b649c6b128
* Content: [DataFormat - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-dataformat)
* Content Source: [winrt-related-src/schemas/appxpackage/appxmanifestschema/element-dataformat.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appxmanifestschema/element-dataformat.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
