### ISSUE TITLE
S or ST for State or Province?

### ISSUE THREAD

**Issue by ErikApption** [MicrosoftDocs/winrt-related#209]
Are the S and ST interchangeable for State or Province? The RDN link says ST is for state or province but the example at the end has S=Washington

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aebac84-5494-5889-68e4-5dcc7404a71f
* Version Independent ID: 09fdc1d5-9c3b-e5e8-06b5-06dde6f5259a
* Content: [Identity - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-identity)
* Content Source: [winrt-related-src/schemas/appxpackage/appxmanifestschema/element-identity.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appxmanifestschema/element-identity.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. For an answer to your question, see the related discussion [here](https://github.com/MicrosoftDocs/winrt-related/issues/182). For app packaging identity, Microsoft uses a nonstandard 'S' abbreviation for the stateOrProvinceName attribute type. This is also called out at the end of the remarks for the related [CertNameToStr](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certnametostra#remarks) function, which this article refers to for semantic rules for validating the Publisher value.

It also looks like you're commenting on the article for the Windows 8 version of the Identity element. If you're building an app for Windows 10, please make sure you're looking at the [Windows 10 version of this article](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-identity).
