### ISSUE TITLE
What is the purpose of ClassicAppCompatKey?

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/winrt-related#21]
I thought AppCompat keys were thoroughly deprecated starting with Windows 8 (although I can't find the doc mentioning this right now). The fact that this key is in the `rescap4` namespace implies it is not for general use, but on the other hand it is publicly documented here, which implies that might be found useful by a fairly large segment of apps/devs. This article does a good job of explaining what `ClassicAppCompatKey` _is_, but does not discuss at all what it _does_. Could this please be expanded? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb781ee5-9428-073e-2227-179cd2384503
* Version Independent ID: 865d9dca-6230-5b65-bc71-abe01c8c84e8
* Content: [rescap4:ClassicAppCompatKey - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap4-classicappcompatkey)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by bjr1822** [comment]
I assume we are talking about a related but not quite the same element of "rc4:ClassicAppCompatKey" in the appx manifest introduced as part of Windows10 RS4 packages? This answer applies to that, in case I'm mistaken. AppCompat keys in this context allow for Centennial applications packaged as appx packages to advertise registry keys outside the appx bubble for interoperability scenarios where older software that needs to detect or interact with the appx packaged application can find the registry keys exposed as if the package was installed in its pre-Centennial form. Most software will not require such extensions, but if the software supports, for example, add-ins which are installed separately, then there may be cases where those add-ins look for certain registry keys to detect that their targeted product is installed and will fail to install or work correctly if those keys are not found. These AppCompatKeys can help smooth over the transition to Centennial by exposing the keys that these other installers expect, but in a way that is still compatible with the Centennial installation requirements regarding maintainability and installation isolation.

**Comment by wjk** [comment]
@bjr1822 Apologies for the confusion; I was indeed very much discussing the `rc4:ClassicAppCompatKey` AppX manifest element. I thought it was related to something completely different due to similar naming conventions.

Your answer has been very helpful. If you want, I can prepare a PR inserting your answer into the doc page for the manifest element in question. Thanks for your help!

**Comment by bjr1822** [comment]
Sure, if you think that is helpful. It may be a little bit of a ramble, but I'm happy to have helpful info posted.

**Comment by kathampy** [comment]
e.g. For exposing Chromium / Firefox NativeMessagingHosts registry keys for browser extensions to communicate with the app.

**Comment by mcleanbyron** [comment]
It sounds like this issue has been answered, so I am closing it.
