### ISSUE TITLE
Using these contacts in ViewModel?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winrt-related#210]
Are all or some of these contacts abstracted away as empty interfaces in a non-UI assembly so that we can utilize them from the ViewModel too without UI coupling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee96a7be-303f-6a9e-f517-0d87df5d17ce
* Version Independent ID: 9841348b-47be-cb11-75b6-b1971e529600
* Content: [Programming with extension SDKs - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview)
* Content Source: [winrt-related-src/extension-sdks/device-families-overview.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/device-families-overview.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @weitzhandler, are your viewmodels in the same project as your app? Or are they in a separate component?

**Comment by weitzhandler** [comment]
Separate. They have no dependency on any UI library.

**Comment by stevewhims** [comment]
I see. So then when you created the project that contains your viewmodels, you targeted a particular device family. That might have been the Universal device family, or the Desktop device family, or some other. In any case, that decision affects what APIs you can call within the project without writing conditional code. And of course you can change that decision at any time by changing your project's target platform settings, as the topic describes.

Now let's say for example that you targeted the Universal device family, but you want your viewmodels to be able to access a particular Desktop-only API *when your app happens to be running on a desktop device*. In that case you'd add a reference to the Desktop extension SDK, and then you'd write conditional code to confirm that a particular API contract is present before you call the Desktop-only API.

**Comment by weitzhandler** [comment]
Thanks for your replies, Steven,

> So then when you created the project that contains your viewmodels, you targeted a particular device family.

No. The ViewModel project is completely agnostic to any UI or device. It only depends on libraries such as MVVM framework, dependency injection, etc.

> That might have been the Universal device family, or the Desktop device family, or some other.

Both. It's meant to serve desktop and mobile, and in fact even web.

> In any case, that decision affects what APIs you can call within the project without writing conditional code.

True, but had those libraries been written with an abstraction layer, it could have been implemented by other providers and be consumed by any view-model library.

> And of course you can change that decision at any time by changing your project's target platform settings, as the topic describes.

Essentially, any view model project should never be coupled with any UI or UI type.



> Now let's say for example that you targeted the Universal device family, but you want your viewmodels to be able to access a particular Desktop-only API _when your app happens to be running on a desktop device_. In that case you'd add a reference to the Desktop extension SDK, and then you'd write conditional code to confirm that a particular API contract is present before you call the Desktop-only API.

That makes perfect sense. But the way it should be consumed is that there is a contract-library of interfaces of all devices and features that has no hard dependencies and preferrably depend only on .NET Standard etc., then another platform-specifcic API that implements those contracts, per platform.

Anyway I realize that's not the way it was built, and based on your response I can assume this is not going to change. Correct me if I'm wrong.

**Comment by stevewhims** [comment]
You're right that the system was designed this way for Universal Windows Platform (UWP) apps, and that's not going to change for UWP apps.

-Steve

**Comment by weitzhandler** [comment]
Thank you!
