### ISSUE TITLE
Request: Add missing information on how to target only a subset of devices in configuration

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/winrt-related#214]
The current version of the UWP documentation lacks information on how to [Limit apps to a subset of all possible devices](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview#limit-your-app-to-a-subset-of-all-possible-devices) or [Exclude support for a particular version of a device family](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview#exclude-support-for-a-particular-version-of-a-device-family).

Is it done in the app manifest file? How?

Please add the missing information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee96a7be-303f-6a9e-f517-0d87df5d17ce
* Version Independent ID: 9841348b-47be-cb11-75b6-b1971e529600
* Content: [Programming with extension SDKs - Windows UWP applications - Limit your app to a subset of all possible devices](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview#limit-your-app-to-a-subset-of-all-possible-devices)
* Content Source: [winrt-related-src/extension-sdks/device-families-overview.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/device-families-overview.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @SetTrend, I've created a task for myself to investigate this.

In the meantime, if you want to look at [TargetDeviceFamily](https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily), and see whether the info there fills in the gaps.

I'll close this issue since I'm tracking the work internally and I'll get to it in priority order.

Thanks again!
Steve

**Comment by SetTrend** [comment]
Excellent! Thanks, @stevewhims, for pointing me to that valuable information.

I think that linking to such information would perfectly suffice in the docs.

It'd be perfect if such information would be available for the [second, above mentioned, item](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview#exclude-support-for-a-particular-version-of-a-device-family), too.

**Comment by stevewhims** [comment]
Thanks, @SetTrend, I'm glad that looks like it might help. So, for "Limit apps to a subset of all possible devices" - I believe that's covered in the second-to-last example in [TargetDeviceFamily](https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily).

And "Exclude support for a particular version of a device family - I believe that's covered in the last example in [TargetDeviceFamily](https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily).

Just FYI, the work I intend to do here (when I get to it), is to confirm that the info in [TargetDeviceFamily](https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily) is correct, and actionable. And then link to that info from this topic.

Thanks!
Steve

**Comment by SetTrend** [comment]
OK ... Well, now I'm confused, because the examples you mention don't deal with "exclusions".
<br/>

The last example of [`TargetDeviceFamily`](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily) it reads:

> Also note the MaxVersionTested value for the mobile device family dependency in the example. Where z > n, the app will run on version 10.0.z.0 of a mobile device, but it will experience 10.0.n.0-version behavior from the platform on that version.

_(NB: Please note that there's no "z" in the example that follows.)_

The explanation there would result in the following behaviour:

```xml
<Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.2" MaxVersionTested="10.0.1.1"/>
    <TargetDeviceFamily Name="Windows.Mobile" MinVersion="10.0.0.1" MaxVersionTested="10.0.0.3"/>
    <TargetDeviceFamily Name="Windows.Team" MinVersion="10.0.0.2" MaxVersionTested="10.0.0.4"/>
</Dependencies>
```

API|10.0.0.0|10.0.0.1|10.0.0.2|10.0.0.3|10.0.0.4|10.0.1.0|10.0.1.1|10.0.1.2
-|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:
Desktop|-|-|10.0.0.2|10.0.0.3|10.0.0.4|10.0.1.0|10.0.1.1|10.0.1.2
Mobile|-|-|10.0.0.2|10.0.0.3|10.0.0.3|10.0.0.3|10.0.0.3|-
Team|-|-|10.0.0.2|10.0.0.3|10.0.0.4|10.0.0.4|10.0.0.4|-
<br/>
<br/>

The [`Exclude support for a particular version of a device family`](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview#exclude-support-for-a-particular-version-of-a-device-family), however, reads:

> In rare cases, you might want your app to **_run everywhere except_** on devices with a particular version of a particular device family.

So, from this text, I would expect to be able to configure something like this:

API|10.0.0.0|10.0.0.1|10.0.0.2|10.0.0.3|10.0.0.4|10.0.1.0|10.0.1.1|10.0.1.2
-|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:
Desktop|-|10.0.0.1|10.0.0.2|10.0.0.3|10.0.0.4|10.0.1.0|10.0.1.1|10.0.1.2
Mobile|-|10.0.0.1|-|-|10.0.0.4|10.0.0.4|10.0.0.4|-
Team|-|10.0.0.1|-|10.0.0.3|-|-|10.0.1.1|10.0.1.1
<br/>
<br/>

You see, the difference between these two statements on the two document pages is that the first description is just clamping the version range, while the second description claims it to be possible to exclude particular versions in-between.

**Comment by SetTrend** [comment]
@stevewhims : I'm not sure if notifications here are getting disabled when an issue gets closed. Did you get my previous message?

**Comment by stevewhims** [comment]
Hi, @SetTrend, so as mentioned I am tracking an internal work item to get to this workstream in priority order. When I do, I'll take a good look at the TargetDeviceFamily topic, make sure it's correct, set up any necessary links, and make sure I resolve any loose threads here (my work item has a link to this issue, so the two are connected). When I can carve off a good chunk of time to ramp up on this workstream, and get to the bottom of it, that'll be the best time for me to address all the issues here.

Thanks!
Steve
