### ISSUE TITLE
Where's the equivalent page for the "Windows 10 app package manifest schema"?

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/winrt-related#217]
Where's the equivalent page for the "Windows 10 app package manifest schema"?  Why are the links taking me to WIndows 8 documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d3549b-6f25-f819-b917-d921cf635f02
* Version Independent ID: d204096e-ebe1-6436-f51d-b7d27001b1cb
* Content: [Windows 8 app package manifest schema - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/appxpackage/appxmanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appxmanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
The Windows 10 package manifest schema is documented in [this section](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/schema-root). If I have misinterpreted your question, please feel free to reopen this issue with more details.
