### ISSUE TITLE
Does the unsupported service list need's to be updated?

### ISSUE THREAD

**Issue by miker1423** [MicrosoftDocs/winrt-related#22]
I see in the next post (https://support.microsoft.com/en-us/help/10568/windows-10-supported-bluetooth-profiles) that some profiles are now supported, like A/V Remote Control, does the unsupported service list has changed or not?

The list of unsupported services is here -> https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth#support-for-bluetooth-rfcomm-services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d28a9f-49b1-a8c4-8480-22d8963c7be8
* Version Independent ID: c093923a-1cca-ce75-c7ad-645b67d6c331
* Content: [How to specify device capabilities for Bluetooth - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth#support-for-bluetooth-rfcomm-services)
* Content Source: [winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-for-bluetooth.md)
* Service: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by drewbatgit** [comment]
The list has been updated to remove the items that are listed as supported in the support article.
