### ISSUE TITLE
desktop5:ThumbnailTypeOverlay  does not work as described and gets error in Visual Studio 2019 version 16.2 and 16.3 Preview 1

### ISSUE THREAD

**Issue by jimshalo10** [MicrosoftDocs/winrt-related#221]
[Enter feedback here]
Visual Studio 2019 gives an error 
Packaging (UWP (x64-64bit)): 
file:///c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Xml/Schemas/UapManifestSchema.xsd(179): 
The 'http://schemas.microsoft.com/appx/manifest/desktop/windows10/5:ThumbnailTypeOverlay' attribute is not declared.

Yet its described as 

desktop5:ThumbnailTypeOverlay | An image resource for a thumbnail overlay.
Either your documentation is wrong or the product Visual Studio 2019 is not working correctly
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af19dcfd-7147-5b7c-0784-db051145184b
* Version Independent ID: be2ace2f-05cb-b892-76cc-f78da65f488b
* Content: [desktop2:ThumbnailHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-thumbnailhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Sorry for the long delay in the response to this issue. Were you able to resolve this in your app? The desktop5:ThumbnailTypeOverlay attribute is used by the [uap:FileTypeAssociation element](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation). I created a blank app, added the FileTypeAssociation element on the Declarations tab of the manifest editor, and then manually added the namespace and attribute to the app manifest. This compiled successfully on both VS2019 and VS2022,

``` xml

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:desktop5="http://schemas.microsoft.com/appx/manifest/desktop/windows10/5"
  IgnorableNamespaces="uap mp">
...
<Extensions>
        <uap:Extension Category="windows.fileTypeAssociation">
          <uap:FileTypeAssociation Name="_ftaname" desktop5:ThumbnailTypeOverlay="image.jpg" >
            <uap:SupportedFileTypes>
              <uap:FileType>.jpg</uap:FileType>
            </uap:SupportedFileTypes>
            <uap:DisplayName>FileTypeAssociationDisplayName</uap:DisplayName>
          </uap:FileTypeAssociation>
        </uap:Extension>
      </Extensions>
```

**Comment by jimshalo10** [comment]
Thanks I am using VS2022 all the time now
