### ISSUE TITLE
Missing unsupported feature (VPN)

### ISSUE THREAD

**Issue by mogikanin** [MicrosoftDocs/winrt-related#225]
As I know, the vpn api also not available on xbox, but this is not mentioned on given page, or I'm wrong?

namespace is
https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Vpn?view=winrt-19041

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b487e4-704e-7407-dc4e-dbd4787b6b17
* Version Independent ID: b7c66d71-1e06-7758-ca85-1f7b62937025
* Content: [UWP features not supported on Xbox - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/uwp-limitations-on-xbox)
* Content Source: [winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @mogikanin, I've reached out to the feature team for confirmation. I'll update the topic if that turns out to be the case.

-Steve

**Comment by stevewhims** [comment]
I've send another reminder, asking for info. Thanks for your patience.

-Steve

**Comment by stevewhims** [comment]
So, at this stage, it's safest not to assume that Vpn works on Xbox. We're not ready to add Vpn to that topic yet, but as I say, for practical purposes there is no claim nor assurance that Vpn works on Xbox.

Hope that helps, and sorry for the delay in responding.

-Steve
