### ISSUE TITLE
This schema is missing the actions element.

### ISSUE THREAD

**Issue by allenbenz** [MicrosoftDocs/winrt-related#227]
toasts can take an actions element with action element children, this is missing from the schema documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fff893d-cf72-dbef-92c1-9ea3bc37d8f4
* Version Independent ID: f5676d7c-7ca0-d9f9-89ba-1339e82db0cd
* Content: [Toast schema - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/schema-root)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Thanks for the feedback. The toast schema docs have been updated to add several missing elements and undergo a tech review to make sure it is current.
