### ISSUE TITLE
Where is the Holographic Extension SDK?

### ISSUE THREAD

**Issue by CarePackage17** [MicrosoftDocs/winrt-related#23]
The holographic device family is missing. Not only here, I'm also having trouble finding related contracts and headers on disk in the SDK (e.g. Windows.Perception.Automation.Monitoring.PerceptionAutomationMonitoringContract).
Is that intended or a mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f322ef7-cc3b-d810-5d27-a36183676640
* Version Independent ID: f5efc866-2cf9-4473-c9a7-7525817da6a1
* Content: [Device Family Extension SDKs and API contracts - UWP app developer](https://docs.microsoft.com/en-us/uwp/extension-sdks/)
* Content Source: [winrt-related-src/extension-sdks/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/index.md)
* Service: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi,
I haven't received authorization to include their SDK in this list. When I do, I will update this topic.

**Comment by CarePackage17** [comment]
The thing is it's also nowhere in the SDK, so I can't program against it even if I wanted to, see e.g. the PerceptionMonitor API.
