### ISSUE TITLE
Why is this only intended for desktop PC games?

### ISSUE THREAD

**Issue by TopperDEL** [MicrosoftDocs/winrt-related#231]
[Enter feedback here]
I would like to use that feature for a system-near-app (to add another Drive using Dokan). But unfortunately this is not possible for an independent developer.

Any chance that this feature can be opened in any way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d0afcc-b589-f535-9b93-d6bd9dd9b015
* Version Independent ID: 25c0c704-75c5-991c-9b68-e85c6cd7e45b
* Content: [desktop6:CustomInstall - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-custominstall.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by ChrisAnd1998** [comment]
Yeah.. I need this too. My application runs in the background and creates a Taskschedule. People can only properly uninstall it through an option inside the app. I want to properly close the background process and remove the Taskschedule on uninstall.

**Comment by GrantMeStrength** [comment]
Handing this request to our installer expert..

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This feature as it exists today was explicitly designed to address specific scenarios needed by some of our game studio partners. There are no plans to open this feature up more broadly at this time, but I have passed along your feedback to the engineering team that owns this feature.
