### ISSUE TITLE
the docs are missing winrt::try_get_activation_factory, a related function

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-related#232]
we are missing a page for this API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379e5b93-0d3e-1b92-1ffc-c895d452e759
* Version Independent ID: 6eb229d2-f00d-081f-688e-2337efb82852
* Content: [winrt::get_activation_factory function template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/get-activation-factory)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/get-activation-factory.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/get-activation-factory.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Done, topic is at https://docs.microsoft.com/uwp/cpp-ref-for-winrt/try-get-activation-factory.
