### ISSUE TITLE
Document how to use `attribute`

### ISSUE THREAD

**Issue by DHowett** [MicrosoftDocs/winrt-related#235]
The Microsoft.UI.Xaml project (open-source!) uses `attribute`!

https://github.com/microsoft/microsoft-ui-xaml/blob/49c719a86d83b3f8a923761c7d472786c15afcba/idl/Microsoft.UI.Xaml.idl#L23-L29

```
    [attributeusage(target_runtimeclass)]
    [attributename("muxhascustomactivationfactory")]
    [version(0x00000001)]
    [webhosthidden]
    attribute MUXHasCustomActivationFactoryAttribute
    {
    }
```

[MERGING IN THE CONTENTS OF THE RELATED ISSUE 236]

Document how to declare a feature using feature_name and use it with feature()

The Microsoft.UI.Xaml project (open-source!) uses `feature_name` and `feature`.

https://github.com/microsoft/microsoft-ui-xaml/blob/49c719a86d83b3f8a923761c7d472786c15afcba/idl/Microsoft.UI.Xaml.idl#L14

```
feature_name Feature_Experimental = { DisabledByDefault, FALSE };
```

https://github.com/microsoft/microsoft-ui-xaml/blob/49c719a86d83b3f8a923761c7d472786c15afcba/idl/Microsoft.UI.Xaml.idl#L136-L137

```
#define MUX_PREVIEW contract(Microsoft.UI.Xaml.XamlContract, 1), feature(Feature_Experimental)
#define MUX_INTERNAL contract(Microsoft.UI.Xaml.XamlContract, 1), feature(Feature_Experimental)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e7b704-bf3b-deaa-0683-9d0a9c69c5d2
* Version Independent ID: d7cbf72b-0ff0-7e3a-9054-ede01cacff97
* Content: [Reserved keywords (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/reserved-keywords)
* Content Source: [winrt-related-src/midl-3/reserved-keywords.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/reserved-keywords.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e7b704-bf3b-deaa-0683-9d0a9c69c5d2
* Version Independent ID: d7cbf72b-0ff0-7e3a-9054-ede01cacff97
* Content: [Reserved keywords (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/reserved-keywords)
* Content Source: [winrt-related-src/midl-3/reserved-keywords.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/reserved-keywords.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Since we're tracking this workstream over internal email, I'll go ahead and close this issue for the time being (so we're not tracking it twice). I'll reopen this issue once we know what to do, and I'm actively working on it.

Thanks!
Steve

**Comment by stevewhims** [comment]
[HAVE MERGED IN THE CONTENTS OF https://github.com/MicrosoftDocs/winrt-related/issues/235]

**Comment by stevewhims** [comment]
Just updating this to mention that this issue is now resolved (so I'll leave it closed).

So, for `attribute`, that's covered in https://docs.microsoft.com/en-us/uwp/midl-3/intro#attributes.

Internally we discussed the other details, and we're good with the current docs as they stand.

Thanks!
-Steve

**Comment by asklar** [comment]
@stevewhims I'm looking for usage info of `feature_name` as well, it looks like #236 was duped to this bug but I don't see `feature_name` documented, could you take a look?

**Comment by stevewhims** [comment]
Thanks, @asklar, sending you email to discuss plans here.

Thanks!
Steve
