### ISSUE TITLE
Document how to declare a feature using `feature_name` and use it with `feature()`

### ISSUE THREAD

**Issue by DHowett** [MicrosoftDocs/winrt-related#236]
The Microsoft.UI.Xaml project (open-source!) uses `feature_name` and `feature`.

https://github.com/microsoft/microsoft-ui-xaml/blob/49c719a86d83b3f8a923761c7d472786c15afcba/idl/Microsoft.UI.Xaml.idl#L14

```
feature_name Feature_Experimental = { DisabledByDefault, FALSE };
```

https://github.com/microsoft/microsoft-ui-xaml/blob/49c719a86d83b3f8a923761c7d472786c15afcba/idl/Microsoft.UI.Xaml.idl#L136-L137

```
#define MUX_PREVIEW contract(Microsoft.UI.Xaml.XamlContract, 1), feature(Feature_Experimental)
#define MUX_INTERNAL contract(Microsoft.UI.Xaml.XamlContract, 1), feature(Feature_Experimental)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e7b704-bf3b-deaa-0683-9d0a9c69c5d2
* Version Independent ID: d7cbf72b-0ff0-7e3a-9054-ede01cacff97
* Content: [Reserved keywords (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/reserved-keywords)
* Content Source: [winrt-related-src/midl-3/reserved-keywords.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/reserved-keywords.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Since https://github.com/MicrosoftDocs/winrt-related/issues/235 is related to this, I've consolidated both issues into one item. So, closing this as duplicate.

Thanks!
Steve
