### ISSUE TITLE
Lower case t-arget should be upper case

### ISSUE THREAD

**Issue by LaPeste** [MicrosoftDocs/winrt-related#237]
[Enter feedback here]
In the xml example         `<desktop6:MutablePackageDirectory target="ContosoGame"/>`
the attribute "target" has a lower case t(-arget) but should be upper case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a71e850-eb4a-dc6e-38b0-36de29443d90
* Version Independent ID: 887151c4-788b-08c9-0075-b6e8107aba98
* Content: [desktop6:MutablePackageDirectories - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectories)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectories.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-mutablepackagedirectories.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thank you for catching this! I have corrected the issue, and it should go live soon. Thanks! -john
