### ISSUE TITLE
Update custom audio for UWP desktop

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-related#24]
In the "Remarks" section:
"UWP apps that target the desktop platform don't currently support custom sounds; instead, you can choose from the list of winsoundevents."

Proposed change:

"UWP apps that target the desktop platform prior to Version 1511 don't support custom sounds; instead, you can choose from the list of winsoundevents."

Also add that information into the "Attributes & Elements" table at the end of the "src Attribute" description, i.e. below the "On Windows Phone 8.1" part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cdbfc40-a54c-3db0-142e-50ffbad78d8f
* Version Independent ID: 8e31fe4a-5eaa-d824-2f37-58ab5d814de7
* Content: [audio - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-audio)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/element-audio.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/element-audio.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mcleanbyron** [comment]
We apologize for taking so long to reply, and thank you for providing your feedback. I have updated the remarks section with the information you specified, and added a link to a related article for more context.
