### ISSUE TITLE
Is Windows.UI.Xaml available for C#/WinRT projection?

### ISSUE THREAD

**Issue by pontin-pdftron** [MicrosoftDocs/winrt-related#240]
Hello,

This question is related to C#/WinRT projection creation using Microsoft.Windows.CsWinRT (v1.2.6) toolkit, so I'm unsure if this is the best place for it.

I have a runtimeclass defined on my MIDL that has a **ContentControl** inheritance as seeing below (this is a custom UI control). This control is being used for UWP application but I would like to create a C#/WinRT projection for .NET 5 to be used on WinUI 3 apps, which seems to be possible.
```
runtimeclass MyControl: Windows.UI.Xaml.Controls.ContentControl
{
	MyControl();
	void DoSomething();
};
```
When creating the projection I get the following error:

`%path%: error CS0234: The type or namespace name 'Xaml' does not exist in the namespace 'Windows.UI' (are you missing an assembly reference?)`

If I go to the auto generated file this is errored line:

`public sealed class MyControl: global::Windows.UI.Xaml.Controls.ContentControl, global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<MyControl>`

Perhaps I missed something reading the documentation and it means that **Windows.UI.Xaml** is not available for .NET 5 projection? Could someone let me know if this is the case? if it is not possible, is there any namespace where I can create UI controls for .NET 5 projection?

I appreciate your time,
Robson

**Comment by angelazhangmsft** [comment]
Hi Robson, C#/WinRT does not currently support the inbox Windows.UI.Xaml.* namespaces. Instead, you can use WinUI namespaces under Microsoft.UI.Xaml.*, which C#/WinRT provides projection support for. 

This would be the corresponding [WinUI class for ContentControl.](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.contentcontrol?view=winui-3.0)

You should be able to create UI controls using the [C++ Windows Runtime Component (WinUI 3) template](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/winui-project-templates-in-visual-studio#project-templates-for-winui-3) which is available with the Project Reunion VSIX. Then you can create a C#/WinRT projection. Let me know if you have questions about this!

**Comment by pontin-pdftron** [comment]
Thank you for the information Angela,

Just to give you more context :

I'm currently porting our C++/CX component to C++/WinRT and there is only 1 UI control which uses Windows.UI.Xaml.* (ContentControl), so my question would be if I'm still able to use/reuse most of this C++/WinRT component I'm porting (the part that does reference Windows.UI.Xaml.*) and then just create a new UI Control using WIndows.UI.Xaml.* ?
 
The only reason I'm porting the  Windows.UI.Xaml.* UI control right now is to make sure we can support UWP apps with the same API (fast development - just migration with similar APIs) but we also want to support WinUI 3 and Desktop apps without that much of extra work like creating a brand new WinRT component, that's where C#/WinRT projections come into play.

Let me know if my thought makes sense.

**Comment by angelazhangmsft** [comment]
@pontin-pdftron, the recommendation is to create a new WinRT component using Project Reunion, and you should be able to copy over your existing component code to this project. We do not plan to support projections in .NET 5 for Windows.UI.Xaml.* namespaces, so I believe you will need a separate component for these UI controls.

cc @marb2000

**Comment by pontin-pdftron** [comment]
@angelazhangmsft
Yes, that's what I thought. I'm still migrating C++/CX to C++/WinRT using Windows.UI.Xaml.*, once that's done I will start a new UI control using Microsoft.UI.Xaml.*.

On more question, if I create a UI component using Microsoft.UI.Xaml.* can I use this on UWP apps? If so, is there a specific SDK version for it?

Thank you for all your help so far

**Comment by angelazhangmsft** [comment]
UWP is not officially supported, although It should technically be possible to host Microsoft.UI.Xaml.* component in a UWP app - the .NET native toolchain would support it and you could publish that app to the store, with a Reunion framework package reference to resolve native DLLs. 

However, this isn't documented and we haven't done validation on this scenario.

**Comment by pontin-pdftron** [comment]
@angelazhangmsft Thank you for all your help. I will close this ticket as all main questions have been answered.
