### ISSUE TITLE
"You must specify both a Win32Path and a Win64Path" is incorrect

### ISSUE THREAD

**Issue by GangYang2012** [MicrosoftDocs/winrt-related#241]
The "Remarks" section that You must specify both a Win32Path and a Win64Path is incorrect. I confirmed with Windows side Hart Wilson (hartwil). Please revise this part. 

Thanks,
Gang Yang (ganyang)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c0035f-43d3-9516-63c3-8aa2cdc810c3
* Version Independent ID: dd304347-376a-c733-13a5-cdd4ae9e7520
* Content: [com:Version - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com-version?source=docs#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com-version.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com-version.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks, I will confirm and make the update as require!

**Comment by GrantMeStrength** [comment]
Thanks! Confirmed the text should be "You must specify either a Win32Path or a Win64Path, and can specify both. Generating and registering both 32-bit and 64-bit formats for a type library can improve performance if its interfaces are used from client processes of both 32-bit and 64-bit architectures."

**Comment by mcleanbyron** [comment]
Thanks for reporting this. I have updated the article accordingly.
