### ISSUE TITLE
desktop2:Paramters mis-spelled

### ISSUE THREAD

**Issue by LuHuangMSFT** [MicrosoftDocs/winrt-related#244]
The section

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-appurihandler-manual#attributes-and-elements

> desktop2:Paramters

contains a mis-spelling of "Parameters".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ed7b6c2-d539-b03b-8e57-388a0df129fb
* Version Independent ID: f9cc43fb-ff9d-dc3c-68f9-7ebe8c96c83f
* Content: [uap3:AppUriHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-appurihandler-manual)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-appurihandler-manual.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-appurihandler-manual.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks! Correction has been made, should go live soon. -John
