### ISSUE TITLE
missing tag

### ISSUE THREAD

**Issue by chris2crawford** [MicrosoftDocs/winrt-related#245]
the TAG_INK_SPACE_RECTANGLE is missing in the BNF spec

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57b5679-4a44-3284-e545-9d3c83d03592
* Version Independent ID: 7506e27f-d275-ec02-7515-31387b13e915
* Content: [Ink Serialized Format (ISF) Specification - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/specifications/ink-serialized-format)
* Content Source: [winrt-related-src/specifications/ink-serialized-format.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/specifications/ink-serialized-format.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Please see response in https://github.com/MicrosoftDocs/winrt-related/issues/249
