### ISSUE TITLE
list of tags / index / GUID

### ISSUE THREAD

**Issue by chris2crawford** [MicrosoftDocs/winrt-related#249]
It is implied, but not stated that the index number of the Known GUID Tags is equal to 
  KNOWN_GUID_BASE_INDEX + the index of KNOWN_GUIDS
also:  const GUID FAR KNOWN_GUIDS   appears to have to identifiers: FAR and KNOWN_GUIDS (is FAR a modifier?)

The list  "The following is a list of predefined tags used in this document:"  in Appendix
is inconsistent with the header in Appendix A 
 (it would be less confusing to label them Appendix A and Appendix B)
TAG_COMPRESSION_MODE   vs   TAG_COMPRESSION_HEADER
TAG_METRICS_TABLE  vs  TAG_METRIC_TABLE
TAG_METRICS_BLOCK  vs  TAG_METRIC_BLOCK

  none of:
TAG_METRICS_MAXIMUM
TAG_METRICS_MINIMUM
TAG_METRICS_PERCISION             [sic]
TAG_METRICS_PERCISION_UNITS   [sic]
TAG_METRICS_UNIT_DIVISOR
  are not in the description nor defined in the header even without the 'S'

conversely:  Appendix missed the tags which are described in the text:

TAG_TRANSFORM_ISOTROPIC_SCALE
TAG_TRANSFORM_ANISOTROPIC_SCALE
TAG_TRANSFORM_ROTATE
TAG_TRANSFORM_TRANSLATE
TAG_TRANFROM_SCALE_AND_TRANSLATE
[TAG_TRANSFORM_QUAD]

TAG_TRANFROM_SCALE_AND_TRANSLATE  is spelled incorrectly  and
TAG_TRANSFORM_QUAD  is missing
in section "Transform Block"

the tags
const BYTE TAG_MANTISSA = 27;
const BYTE TAG_PERSISTENT_FORMAT = 28;
const BYTE TAG_HIMETRIC_SIZE = 29;
const BYTE TAG_STROKE_IDS = 30;
are not described in the text

It is implied, but not stated that TAG indices 0-30 do not have GUIDS.

In Appdendix, 
GUID_EDGE_SMOOTHING   is not found in the header

the other predefined Guides indexed 26-37 are not discussed in the text
INDEX_GUID_INKMETRICS 26  to  INDEX_GUID_ROP 37
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57b5679-4a44-3284-e545-9d3c83d03592
* Version Independent ID: 7506e27f-d275-ec02-7515-31387b13e915
* Content: [Ink Serialized Format (ISF) Specification - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/specifications/ink-serialized-format)
* Content Source: [winrt-related-src/specifications/ink-serialized-format.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/specifications/ink-serialized-format.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by chris2crawford** [comment]
that is indices 29-37 that are not listed in Appendix, not 26-37. 
 Are they all global ink property GUIDs?

**Comment by zarezkabel** [comment]
jak se mas odkud jsi ?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @chris2crawford - As this topic was just a markdown version of the official, downloadable PDF. I replaced the content with a link to the official doc. Hopefully it contains the details you're referring to.
