### ISSUE TITLE
Incorrect element parameter documented.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#250]
The Resources element does not have any parameters in the FoundationManifest schema.  This appears to be a mistake in this documentation (the description is also a huge clue) and should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df6f6356-1b32-153d-8ede-d35e230fce47
* Version Independent ID: 6a515b67-c3cc-d62c-3261-4bbbd2d17951
* Content: [Resources (Windows 10 package schema) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-resources)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resources.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resources.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
The parameters attribute has been removed from this page.

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-resources
