### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#256]
The rescap4 schema for ExtensionChoice (along with AppXManifest Type ST_PackageExtensinCategory_Restricted4) includes the definition of two categories, however only one is mentioned here:

- windows.primaryInteropAssemblies (missing)
- windows.classicAppCompatKeys (present).

There also appears to be no page for the PrimaryInteropAssemblies element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 981d8a91-769b-4ac9-3591-6c86d2ccc0be
* Version Independent ID: 105a3fcd-5307-d832-4ac8-788e2857da2e
* Content: [rescap4:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap4-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
The windows.primaryInteropAssemblies category and PrimaryInteropeAssemblies element have been added:

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap4-primaryinteropassemblies
