### ISSUE TITLE
Missing documentation on Package Extension uap8:dataprotection

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#257]
The UAP8 schema references ST_ExtensionCatergory_UAP8 in the AppXManifest Types and includes a package level extension with category "winodws.dataProtection".  There is no documentation in the area of this page for this extension 

(Note: Uap7 does include a windows.enterpriseDataProtection, which is presumed to be different).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955e39c1-c468-2323-31d8-dd4cf7b691f4
* Version Independent ID: 0feeea15-a804-baa2-b92a-fedb78d7729b
* Content: [Extensions (in Package) (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-extensions)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extensions.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extensions.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
Thanks for the feedback. The uap8 package extension and the associated DataProtection element have been documented: 

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap8-package-extension
