### ISSUE TITLE
Missing category: windows.mediaContentDecryptionModule

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#258]
UAP10 schema references SP_ExtensionCategory_UAP10 in the AppxManifestTypes that defines three package extension categories.  Two are documented here and windows.mediaContentDecryptionModule is missing.  Also no page the underlying element for this category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9415ad5-fdc8-d898-4cd0-dc8a7b0e489b
* Version Independent ID: aa6ccf50-a369-39a8-6203-ef9259959018
* Content: [uap10:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
A page has been created for the MediaContentDecryptionModule. https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-mediacontentdecryptionmodule
