### ISSUE TITLE
Desktop7 and Desktop8 are missing

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#259]
Documentation for these two newer schemas appear to be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b5f587-faab-ab4e-8dd5-e7eda88db6e1
* Version Independent ID: 441983ca-5fb9-56d3-0b7a-982fd5069b76
* Content: [Element Hierarchy (Windows 10 package schema) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/root-elements)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/root-elements.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/root-elements.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
The desktop7 and desktop8 extensions have been documented.

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-package-extension
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-extension
