### ISSUE TITLE
Missing categories and subelements

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#260]
The DesktopManifestSchema ApplicationExtensionChoice, and AppXManifestTypes ST_ApplicationExtensionCategory_Desktop, define four categories.  This page contains only one and the missing ones lack their own pages for the sub-elements.

- windows.FullTrustProcess (present)
- windows.startupTask (missing)
- windows.toastNotifictionActivation (missing)
- windows.searchProtocolHandler (missing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daca40a6-0caf-8878-ce0f-e244ee88613a
* Version Independent ID: 958ff491-0dc9-0d49-0c95-b704275f0710
* Content: [desktop:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
These categories and subelements have been added:
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-fulltrustprocess
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-startuptasks
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-toastnotificationactivation
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-searchprotocolhandler
