### ISSUE TITLE
Missing/Incorrect documentation

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#261]
Feedback in three parts:

**1.** The example in the remarks section does not seem relevant to this element.

**2.** Quite a number of the extension categories are not documented, other than being in the list here:
- windows.search
- windows.cachedFileUpdater
- windows.cameraSettings
- windows.accountPictureProvider
- windows.printTaskSettings
- windows.lockScreenCall
- windows.alarm
- windows.print3dWorkflow
- windows.aboveLockScreen
- windows.personalAssistantLaunch

It may be possible that these extension categories exist without need for a sub-element, if so that should be made clear. It is also possible that these are not supported, even if still in the schema, and they need to be marked as deprecated here.

**3.**  The category windows.lockScreen is mentioned here but not defined, however there is a defined element uap:LockScreen, however it does not live under the Extension element.  If these are connected the documentation on uap:LockScreen also needs to be updated to show that connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28144bc1-5655-1e60-966f-b46997205ca1
* Version Independent ID: 325650f8-21f5-90b9-6fa8-bbd12c206e1c
* Content: [uap:Extension (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
@TimMangan I have sent email to the subject matter experts to try to get an answer but have not yet been able to get an answer.  I apologize, but as we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool. You can still comment on this issue if you have more info.
