### ISSUE TITLE
Missing pages for uap2:Extensions and windows.webAccountProvider

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#262]
A page like this one for uap2:Extensions is missing.  According to the schema / ManifestTypes schema there is an ApplicationExtensionChoice for category windows.webAccountProvider.  Neither is documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28144bc1-5655-1e60-966f-b46997205ca1
* Version Independent ID: 325650f8-21f5-90b9-6fa8-bbd12c206e1c
* Content: [uap:Extension (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
Pages have been created for the uap2 extension and it child element WebAccountProvider.

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap2-extension

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap2-webaccountprovider
