### ISSUE TITLE
documentation issues on this page

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#263]
1.  There is a typo for windows.appExecutionAlias.  This page has it as windows.app.ExecutionAlias
2. The following items are in the UAP3 manifest and Manifest types but not present in the documentation, both on this page as well as missing pages for the sub-elements needed by these category types:

- windows.protocol
- windows.fileTypeAssociation

While the elements may be similar to other schemas, there are differences (for example the UAP3 version of protocol has an extra parameter over the UAP version that is documented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec848a65-ee50-b9c7-5812-84cb02f6ebd8
* Version Independent ID: 23355ab4-a53a-0889-4254-26dff43a1161
* Content: [uap3:Extension (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
Pages have been created for the uap3 versions of windows.protocol and windows.fileTypeAssociation.

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-protocol
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-filetypeassociations
