### ISSUE TITLE
Missing category on UAP4 application extensions

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#264]
The UAP4 schema, along with the AppxManifestTypes ST_ApplicationExtensionCategory_Uap4 has one additional category not mentioned on this page:

- windows.printWorkflowForegroundTask

Only the printWorkflowBackgroundTask is covered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a836d5bb-dce7-3705-81e6-bac085dc37ad
* Version Independent ID: 9ee4cefb-3b1c-51b2-1fa4-97c9b4f092fd
* Content: [uap4:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
windows.printWorkflowForegroundTask has been added to this page.
