### ISSUE TITLE
missing category on Uap6 application extensions page

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#265]
The UAP6 Schema and AppManifestTypes SP_ExtensionCategory_UAP6 contain an extra application extension not mentioned on this page:

- windows.barcodeScannerPreviewProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5309a65b-6c16-e492-55e0-28f7be2e8638
* Version Independent ID: ca43ca2d-76e0-0fda-e4dd-8748868b2dfa
* Content: [uap6:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap6-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap6-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
This extension category has been added to the [uap6:Extension](/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-extension).
