### ISSUE TITLE
UAP8 Application Extension page, and sub-elements missing in documentation set.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#266]
There is no page for the UAP8 Application extension.
There should be one with category windows.pospaymentConnector and a page for the uap8:PosPaymentConnector element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9415ad5-fdc8-d898-4cd0-dc8a7b0e489b
* Version Independent ID: aa6ccf50-a369-39a8-6203-ef9259959018
* Content: [uap10:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
Thanks for your feedback. We have begun addressing the backlog of issues. The uap8 extension is now documented here: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap8-extension
