### ISSUE TITLE
Missing for Uap10: Application Extensions

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#267]
There is no page for the UAP10 Application Extensions.  The UAP10 Schema, along with the AppXManifestTypes ST_ExtensionCategory_Uap10 shows an application extension category for windows.protocol and a uap10:protocol element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9415ad5-fdc8-d898-4cd0-dc8a7b0e489b
* Version Independent ID: aa6ccf50-a369-39a8-6203-ef9259959018
* Content: [uap10:Extension - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
The windows.protocol category has been added and a page has been added for the uap10:protocol element:

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-protocol
