### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#268]
As the documentation page for Application Extensions, this page mentions uap and desktop schemas, but none of the updated schemas that also have application extensions.  A partial list of the missing that have documentation pages of their own would include:

- Com, Com2, Com4
- Desktop2, 3, 4, and 6
- Rescap2 and 3
- Uap2,3,4,6,8,10
- Wincap2, 3

Missing from here and lacking their own page:

- Desktop7
- Uap12, 13

The package extensions are likewise an issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd8999c-d0a7-5788-883f-8e0aceb1db19
* Version Independent ID: 63285457-6305-9847-2e5f-50b4e07f698a
* Content: [Extensions (in Application) (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extensions)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-1-extensions.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-1-extensions.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
@TimMangan - Thanks for this and all of the other issues you opened against the schema docs. My team will look into all these issues and come up with a plan to address them. I'll reply back when I have more details.

**Comment by drewbatgit** [comment]
This page has been updated in response to a newer github issue. I've updated the child elements list and added supported extension categoaries.
