### ISSUE TITLE
Overrideable or overridable?

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-related#269]
![image](https://user-images.githubusercontent.com/22989529/128828740-b343cc9d-ed9a-49e5-bda0-5aa3c8b74ca2.png)

The code uses `overridable`, but the description uses `overrideable` (with an e). Which one is right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dc10e0-781d-367d-bc47-eef1a4abac87
* Version Independent ID: 4750ae98-e82e-15b7-5f70-c677e051e7ae
* Content: [Synthesizing interfaces (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/synthesizing-interfaces)
* Content Source: [winrt-related-src/midl-3/synthesizing-interfaces.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/synthesizing-interfaces.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @asklar. I've published a fix now. The correct spelling is "overridable".

-Steve
