### ISSUE TITLE
Native / Win32 apps' EntryPoint

### ISSUE THREAD

**Issue by zyndor** [MicrosoftDocs/winrt-related#270]
Re: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-application

It might be worth pointing out that, if the product is not a managed / UWP app, then EntryPoint is simply the name of the actual entry point (vs activatable class ID) - e.g. main, WinMain, wWinMain etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde533b6-6c10-9afe-aa89-d56cf71695d2
* Version Independent ID: 0ee1747c-45c5-7b66-5f8e-54f07539a397
* Content: [Application (package schema for Windows 8) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-application)
* Content Source: [winrt-related-src/schemas/appxpackage/appxmanifestschema/element-application.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appxmanifestschema/element-application.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by drewbatgit** [comment]
Thanks for this helpful suggestion. I've updated the content to include this information.
