### ISSUE TITLE
Incomplete copy/pasted garbled docs

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#273]
This page has missing text and incorrect attribute information:

* The `Default = Boolean` attribute is described as `the name of the capability` which looks like a copy/paste error.
* The remarks section says only `The Default attribute is not` which is obviously incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df6f6356-1b32-153d-8ede-d35e230fce47
* Version Independent ID: 6a515b67-c3cc-d62c-3261-4bbbd2d17951
* Content: [Resources (Windows 10 package schema) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-resources)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resources.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resources.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this error. This page has been updated to clean up the copy/paste garbling.

https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-resources
