### ISSUE TITLE
Docs inconsistent on whether a resource tag is required

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#274]
Compare:

`Note: Beginning in Windows 10, version 1803, the Resource element can be omitted.`

(from the docs for Resources)

with

`Every package must declare at least one language for resources`

(from the docs for Resource)

Both statements can't be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f798e27-5c18-7611-cb89-e2d7bc580b77
* Version Independent ID: 72314c01-61a2-7405-1a0c-9c9f21495f09
* Content: [Resource (Windows 10 package schema) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-resource)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resource.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-resource.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. This page has been updated to remove the contradictory note.
