### ISSUE TITLE
Inaccuracies w.r.t. rules about struct fields

### ISSUE THREAD

**Issue by Lexikos** [MicrosoftDocs/winrt-related#275]
A couple of small inaccuracies could cause a nasty surprise for anyone implementing a language projection:

> Struct fields may only be enums, structs, and fundamental types (including strings).

`Windows.Web.Http.HttpProgress` breaks this rule; it contains two fields of type `` Windows.Foundation.IReference`1<UInt64> ``, which is an interface, not a fundamental type.

> A struct must have at least one field. All of a struct's fields must be public.

Structs are also used in attributes within the metadata; these structs have no fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01097c38-e018-de14-9b92-3f1c06025dc3
* Version Independent ID: a6277ffd-669e-2f00-80ca-f4f352a48b58
* Content: [The Windows Runtime (WinRT) type system - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system)
* Content Source: [winrt-related-src/winrt-cref/winrt-type-system.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/winrt-cref/winrt-type-system.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Lexikos, and thanks for filing this issue. I'll work on it asap.

-Steve

**Comment by stevewhims** [comment]
I've published updates to the topic.

Thanks again!
Steve
