### ISSUE TITLE
After starting the system, the application starts with no arguments

### ISSUE THREAD

**Issue by igor-lukashenya** [MicrosoftDocs/winrt-related#276]
`uap5:StartupTask` don't use parameters.

```
<uap5:Extension Category="windows.startupTask" 
			    Executable="Client\Client.exe"
			    EntryPoint="Windows.FullTrustApplication"
			    uap10:Parameters="-m someArg">
			   <uap5:StartupTask TaskId="TaskId"
							  Enabled="true"
							  DisplayName="name" />
</uap5:Extension>
```
After starting the system, the application starts with no arguments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03ded105-c284-9f7d-f4c3-82781fb291fd
* Version Independent ID: 28603ad2-8595-c918-4db0-f3b72a2cfc20
* Content: [uap5:StartupTask - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-startuptask)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap5-StartupTask.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap5-StartupTask.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, thanks for helping to make the documentation more accurate. The page for uap5:StartupTask element doesn't list uap10:Parameters as a supported child element. Is this something you think needs to be explicitly called out in the documentation?
