### ISSUE TITLE
rescap4:ClassicAppCompatKey is a package level extension, not application level extension

### ISSUE THREAD

**Issue by ChaowenYu** [MicrosoftDocs/winrt-related#277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb781ee5-9428-073e-2227-179cd2384503
* Version Independent ID: 865d9dca-6230-5b65-bc71-abe01c8c84e8
* Content: [rescap4:ClassicAppCompatKey - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap4-classicappcompatkey)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap4-ClassicAppCompatKey.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This page has been updated to reflect that rescap4:ClassicAppCompatKey goes under Extensions in the element hierarchy.
