### ISSUE TITLE
Syntax seems to be incorrect on this page.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#279]
The Syntax and Example portions of this page are inconsistent.  Similarly, the Attributes section does not belong here, and a Child Elements section should be here.

I believe that the Syntax section is incorrect and that the parameters do not belong to this element but to the child element "Extension Handler".

I also believe (that to be consistent with other schema documentation) there is a missing page for the desktop9:ExtensionHandler element which would include these parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23e5b7b-3a2a-c122-9a0e-fd7a97e4cd20
* Version Independent ID: baed8ba5-589a-916e-371a-f372dda39adb
* Content: [desktop9:FileExplorerClassicContextMenuHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by TimMangan** [comment]
While looking at this issue, please also verify the syntax restrictions on the Type parameter.  As the Type seems to match a file extension, it likely has additional restrictions on allowed characters.

**Comment by drewbatgit** [comment]
Thanks for reporting this error in the documentation. Both FileExplorerClassicContextMenuHandler and FileExplorerClassicDragDropContextMenuHandler have been updated to move those attributes in the child [ExtensionHandler](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-extensionhandler) element. 
As to the restrictions on the Type parameter, it's declared as type ST_NonEmptyString with a MaxLength of 64. So, it seems the only requirement is that it not begin or end with a whitespace. 

'''
<xs:simpleType name="ST_NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="32767"/>
      <xs:pattern value="[^\s]|([^\s].*[^\s])"/>
    </xs:restriction>
  </xs:simpleType>
'''
