### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by rave991** [MicrosoftDocs/winrt-related#28]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b26b439-4abf-bfd7-681c-51930f503e88
* Version Independent ID: 4d8d1692-44a6-0531-8277-923125eb57eb
* Content: [App package manifest - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appx-package-manifest)
* Content Source: [winrt-related-src/schemas/appxpackage/appx-package-manifest.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/appx-package-manifest.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by ginami** [comment]
Hi @rave991--please let us know if you have any feedback for our docs. Thank you!
