### ISSUE TITLE
Also incorrect documentation

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#280]
This page suffers from the exact same issues as issue #279 (desktop9:FileExplorerClassicContextMenuHandler)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02731c52-0ccf-492a-2175-d98f7bec4f5c
* Version Independent ID: 80354066-30d4-d670-313d-8b0d25e55d1b
* Content: [desktop9:FileExplorerClassicDragDropContextMenuHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassicdragdropcontextmenuhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassicdragdropcontextmenuhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassicdragdropcontextmenuhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this error in the documentation. Both FileExplorerClassicContextMenuHandler and FileExplorerClassicDragDropContextMenuHandler have been updated to move those attributes in the child [ExtensionHandler](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-extensionhandler) element.
