### ISSUE TITLE
Minimum OS Requirement

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#281]
Please add a note to this page in regard to the requirement stated in https://docs.microsoft.com/en-us/windows/msix/packaging-tool/support-legacy-context-menus.  I think it should appear here as

- AppXManifest file must have the Dependency MaxTested set to at least 10.0.21300.0
- Support on OS builds of at least 10.0.21300.0

This requirement note should also be placed on the page https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassicdragdropcontextmenuhandler 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23e5b7b-3a2a-c122-9a0e-fd7a97e4cd20
* Version Independent ID: baed8ba5-589a-916e-371a-f372dda39adb
* Content: [desktop9:FileExplorerClassicContextMenuHandler - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop9-fileexplorerclassiccontextmenuhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
These requirements appear to have been added at some point in the past.
