### ISSUE TITLE
Update Bundle Schema Documentation

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#282]
The documentation for the Bundle in this page (and sub-pages) refer only to the 2013 version of the bundle schema.  I am aware of versions for 2014, 2016, 2017, 2018, and 2019.  These should also be documented, along with information regarding minimim OS versions supporting the changes in newer schema versions.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31af4ec6-3feb-e461-3593-505e8fffdf0b
* Version Independent ID: 8277485f-ab00-16c0-08ef-d81322afb7bd
* Content: [Bundle manifest schema reference - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/bundlemanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/bundlemanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/bundlemanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
A bulleted list has been added to the page at some point in the past that explains these previously undocumented categories.
