### ISSUE TITLE
Missing schemas

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#283]
The documentation for the Bundle in this page (and sub-pages) refer only to the 2013 version of the bundle schema.  I am aware of versions for 2014, 2016, 2017, 2018, and 2019.  These should also be documented, along with information regarding minimim OS versions supporting the changes in newer schema versions.

[Enter feedback here]
The VirtualizationManifestSchema is missing from this page (as documented at https://docs.microsoft.com/en-us/windows/msix/desktop/flexible-virtualization) , probably associated with 21H1.

There also seem to exist some schemas for "WindowsCapabilitiesManifestSchema" (3 known versions) however without any documentation it isn't clear if these are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31af4ec6-3feb-e461-3593-505e8fffdf0b
* Version Independent ID: 8277485f-ab00-16c0-08ef-d81322afb7bd
* Content: [Bundle manifest schema reference - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/bundlemanifestschema/schema-root)
* Content Source: [winrt-related-src/schemas/bundlemanifestschema/schema-root.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/bundlemanifestschema/schema-root.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I have sent email to the subject matter experts to ask about these undocumented bundle schemas, but I haven't been able to get a response.  I apologize, but as we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool. You can still comment on this issue if you have more info.
