### ISSUE TITLE
Probably wrong description for LibraryFlag 

### ISSUE THREAD

**Issue by rwrc** [MicrosoftDocs/winrt-related#288]
Based on XSD LibraryFlag should be HEX value like LocaleId:
```
<xs:simpleType name="ST_LibFlagCom">
      <xs:restriction base="xs:string">
          <xs:pattern value="[0-9a-fA-F]"/>
      </xs:restriction>
  </xs:simpleType> 
```

https://github.com/microsoft/msix-packaging/blob/master/resources/AppxPackaging/Manifest/Schema/2015/AppxManifestTypes.xsd
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c0035f-43d3-9516-63c3-8aa2cdc810c3
* Version Independent ID: dd304347-376a-c733-13a5-cdd4ae9e7520
* Content: [com:Version - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com-version)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com-version.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com-version.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. The format for this attribute has been corrected in the documentation.
