### ISSUE TITLE
Does not say where in the manifest file we put the permissions.

### ISSUE THREAD

**Issue by curelom** [MicrosoftDocs/winrt-related#289]
I've placed the code snippets everywhere in the manifest and they don't work.  One example of a full manifest file would make all the difference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02a280f-6a8a-81c7-584f-7825c18272f9
* Version Independent ID: 2762cad0-c205-af68-7b19-e5f168af5358
* Content: [How to specify device capabilities in a package manifest - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest)
* Content Source: [winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@curelom Are you using a project template with an existing app manifest?  If so, which project type are you using? I would like to take a look at what the default manifest file has in it, to make sure that our docs are targeted to the initial state of the manifest file. To unblock you right away, you can view full manifest files in the Windows Universal Samples repo. Here's one example:

https://github.com/microsoft/Windows-universal-samples/blob/ca74baf5c9e53955e8d749733b8e3e4839afd472/Samples/CameraVideoStabilization/cs/Package.appxmanifest

**Comment by drewbatgit** [comment]
Closing as inactive.
