### ISSUE TITLE
Adding arbitrary XML elements

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/winrt-related#29]
The schema doesn't include mention of adding arbitrary XML elements.

If I add arbitrary XML data to the toast payload (for example, adding a &lt;data&gt;Foo&lt;/data&gt; element inside &lt;toast&gt;), I've found that it will successfully be passed through the OS and on to the app. Is this undefined behavior or can we rely on it? It's potentially useful for including metadata that client apps can process further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a9d44e-b5d2-9da9-1d9a-d2450b549572
* Version Independent ID: 3fc3283d-fe01-5536-3e31-e1213fae3ad5
* Content: [toast - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-toast)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/element-toast.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/element-toast.md)
* Product: **windows**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mijacobs** [comment]
@andrewleader Can you take a look?

**Comment by andrewleader** [comment]
Hi @aschultz, adding arbitrary XML elements to toast or tile payloads is not an officially supported scenario. It is undefined behavior as you suggested. We can not make any guarantee that we won't change that behavior in the future.

We don't have any changes in mind for the near future that would affect this, but the nature of non-supported scenarios is that they could change and any critical behaviors shouldn't rely on them.

The officially supported place for arbitrary data is within the `launch` attribute... `<toast launch="you-can-put-anything-here">`.

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
