### ISSUE TITLE
Please include information on appinstaller schema version 2021

### ISSUE THREAD

**Issue by paulirwin** [MicrosoftDocs/winrt-related#292]
This page does not include which OS versions are supported by schema version 2021 (http://schemas.microsoft.com/appx/appinstaller/2021) as mentioned in other articles. Please update this page to include 2021 as well as the other schema versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005fc6a6-9327-61b5-7fac-ce77fef2490d
* Version Independent ID: 2488a987-dede-9e52-9054-816599869da5
* Content: [AppInstaller - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-appinstaller)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-appinstaller.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-appinstaller.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by jbennink** [comment]
Have been caught by this as well. It seems schema version 2021 does not work on Windows 10, even after the 22H2 update

**Comment by drewbatgit** [comment]
We have updated the documentation to include the elements introduced in later schemas:

https://learn.microsoft.com/en-us/uwp/schemas/appinstallerschema/schema-root

And we have added some details as to how the versioning works here:

https://learn.microsoft.com/en-us/uwp/schemas/appinstallerschema/app-installer-file
