### ISSUE TITLE
win32dependencies:ExternalDependency

### ISSUE THREAD

**Issue by florelis** [MicrosoftDocs/winrt-related#295]
> For the list of allowed dependency packages, see TBD.

Can this be expanded?

> This feature requires that the latest version of the Microsoft App Installer app be installed on the target machine.

Is there a specific version number? I assume it's already not only in the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e681648-a95a-772b-ad09-f745748dc4f1
* Version Independent ID: 9e681648-a95a-772b-ad09-f745748dc4f1
* Content: [win32dependencies:ExternalDependency (Windows 10, Windows 11) - Windows UWP applications](https://review.docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency?branch=drewbat%2FExternalDependency)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for the feedback. This remark has been updated: This feature requires that Microsoft App Installer version 1.16.12651.0 or later be installed on the target machine.
