### ISSUE TITLE
Is "override" a correct modifier ?

### ISSUE THREAD

**Issue by rlaf99** [MicrosoftDocs/winrt-related#300]
According to <https://docs.microsoft.com/en-us/uwp/midl-3/intro#protected-and-override-methods>

> A method can be overridden in a derived class. When an instance method declaration includes an override modifier, the method overrides an inherited virtual method with the same signature. Whereas a method declaration ordinarily introduces a new method, an override method declaration specializes an existing inherited virtual method by providing a new implementation of that method.

As I tried it out, "override" doesn't seem to be a valid modifier .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @zh4ui! I'm investigating.

**Comment by stevewhims** [comment]
I've updated the docs in line with how we expect the keyword to work. You're right, `override` isn't a valid keyword; it's `overridable`.

-Steve
