### ISSUE TITLE
UAP13:AutoUpdate child element is missing from the Package level Extension element.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#301]
The uap13:AutoUpdate element documented here: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-autoupdate indicates that the parent element should be the package level Extension element.  The AutoUpdate is not listed as a child element on this page.

This is particularly confusing as I have seen information that AutoUpdate should be a child of the Properties element (it is not listed in the documentation under that element either).

Please confirm correct location and update appropriate parent element.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62762880-6dfc-c9a0-f040-92a359de913e
* Version Independent ID: 47f6f79b-4c35-9075-c566-3eeda412ba1f
* Content: [Extension (in Package/Extensions) (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by TimMangan** [comment]
Update:  I found a reference in the FoundationManifest schema that shows CT_Properties as having uap13:AutoUpdate as a child.  

If you confirm that Properties is the correct parent, then the PackageExtension page is correct and both Properties, uap13:AutoUpdate, and uap13:AppInstaller pages need updating instead.

**Comment by drewbatgit** [comment]
@TimMangan Good catch. uap13:AutoUpdate is a child of Package/Properties. I updated the element hierarchies for uap13:AutoUpdate and uap13:AppInstaller. It looks like uap13:AutoUpdate had already been added to the Package/Properties page in the long span between when you opened the issue and today, so it didn't need to be updated.
