### ISSUE TITLE
Please specify minimum version for the requirement.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#302]
The statement "This feature requires that the latest version of the Microsoft App Installer app be installed on the target machine. The app can be obtained from the [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows)." should include a minimum version number for App Installer app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e681648-a95a-772b-ad09-f745748dc4f1
* Version Independent ID: 9e681648-a95a-772b-ad09-f745748dc4f1
* Content: [win32dependencies:ExternalDependency (Windows 10, Windows 11) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the suggestion. This remark has be updated: This feature requires that Microsoft App Installer version 1.16.12651.0 or later be installed on the target machine.
