### ISSUE TITLE
Copy/paste error in docs for uap:FileTypeAssociation

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#303]
The first property here has the following description:

"DesiredView: The desired amount of screen space to use when the appointment launches."

Huh? This tag has nothing to do with appointments, right? Looks like a copy/paste error from some other documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10bedc7-7a98-c539-8bb6-cc7d258ec400
* Version Independent ID: f7cde4ec-6c81-bf49-458c-42e8521a1191
* Content: [uap:FileTypeAssociation (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. The description has been updated to the following:

"DesiredView = 'An optional string that can have one of the following values: "default", "useLess", "useHalf", "useMore", or "useMinimum".'"
