### ISSUE TITLE
missing <desktop4:DesktopIconOverlayHandlers>

### ISSUE THREAD

**Issue by leonzhu1985** [MicrosoftDocs/winrt-related#309]
Looks like <desktop4:DesktopIconOverlayHandlers> is missing from the child element list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9100f1fb-81f7-ca2d-5b9b-54c2f1a4ebe5
* Version Independent ID: 64d4ac3c-ee5a-84c6-f70e-e9aa994de791
* Content: [desktop3:CloudFiles - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop3-cloudfiles)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-cloudfiles.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop3-cloudfiles.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The desktop4:DesktopIconOverlayHandlers child element has been added.
