### ISSUE TITLE
desktop7:Logo docs are ambiguous and seems to have copy/paste errors

### ISSUE THREAD

**Issue by mikehearn** [MicrosoftDocs/winrt-related#310]
The `desktop7:Logo` AppxManifest element is, according to #306, a way to use .ico files for file type associations. The docs don't make this clear:

1. ICO files aren't mentioned anywhere. It's described only as "A path to a file that contains an image." but doesn't say what formats the images can be in.
2. The ResourceId attribute is described as `The string table ID of the string Infotip string within the resource module`. This doesn't make any sense to me. ICO files don't have string tables. If the file is meant to be a RES file, EXE or DLL instead of an ICO then it still doesn't make sense because icons can be identified numerically in these files, and usually are?
3. The parent element is wrong. It's talking about control panel extensions - another copy/paste error?

It seems like the AppxManifest tags quite frequently have copy/paste errors in them where the docs don't make sense because they seem to be talking about an unrelated area of the schema. Maybe some tooling here could help - like a little script or program that generates a fresh page from scratch, so nothing can be forgotten?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24976451-35a0-7362-ed44-7ce381614356
* Version Independent ID: 24976451-35a0-7362-ed44-7ce381614356
* Content: [desktop7:Logo - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-logo)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop7-logo.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop7-logo.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
We are working through our backlog of stale github issues. Thank you for catching this. The page has been updated to reflect that .ico (and .dll and .exe) files are supported. And the parent element link has been updated.
