### ISSUE TITLE
video declared as private

### ISSUE THREAD

**Issue by githubgoucho** [MicrosoftDocs/winrt-related#311]
video is declared as private, so how can I watch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee96a7be-303f-6a9e-f517-0d87df5d17ce
* Version Independent ID: 9841348b-47be-cb11-75b6-b1971e529600
* Content: [Programming with extension SDKs - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview)
* Content Source: [winrt-related-src/extension-sdks/device-families-overview.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/device-families-overview.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @githubgoucho! I've fixed the video.

-Steve
