### ISSUE TITLE
I am trying to add a shortcut to my appxmanifest using desktop7:Shortcut and it does not work

### ISSUE THREAD

**Issue by jbennink** [MicrosoftDocs/winrt-related#312]
I added 
```
  xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7"
```
 to the Package tag and  tried to add this

```
			<Extensions>
				<desktop7:Extension>
					<desktop7:Shortcut>
						
					</desktop7:Shortcut>
				</desktop7:Extension>

			</Extensions>
```

inside an Application tag. The Docs don't give any meaningful examples but VS gives me a squigle on desktop7:Extension saying thet desktop7:Extensuion is invalid.
![image](https://user-images.githubusercontent.com/49071903/190394528-00c80c88-4ec5-446d-b369-9feed5cb93ae.png)

---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e571f7-162d-5c72-64b6-ab1075f4e875
* Version Independent ID: 72e571f7-162d-5c72-64b6-ab1075f4e875
* Content: [desktop7:Shortcut - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-shortcut)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop7-shortcut.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop7-shortcut.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by jhiggs15** [comment]
^^^

**Comment by drewbatgit** [comment]
@jbennink @jhiggs15 I am investigating this issue. One thing I wanted to confirm. Have you tried to create the shortcut using this syntax and it failed, or is this just about the squiggles in the editor? I plan to try an implementation of this myself, but I wanted to verify that you two were both unable to actually create the shortcut.

**Comment by jhiggs15** [comment]
@drewbatgit I have tried to create it. I'm bundling into an appinstaller file and running the file it says "Cannot open app package", and the reason is Error in Parsing the app package. When I remove the xmlns desktop7 and Extensions tag it runs no problem. My AppxManifest.xml looks like this...

```<?xml version="1.0" encoding="utf-8"?>
<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7"
>
  <Identity Name="Example" Version="0.1.0.0" Publisher="CN=Example Inc, O=Example, L=Example, S=Example, C=US" ProcessorArchitecture="x64" />
  <Properties>
    <DisplayName>Example</DisplayName>
    <PublisherDisplayName>Example</PublisherDisplayName>
    <Description>Example</Description>
    <Logo>images\icon.png</Logo>
  </Properties>
  <Resources>
    <Resource Language="en-us" />
  </Resources>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.18362.900" MaxVersionTested="10.0.19044.1889" />
  </Dependencies>
  <Capabilities>
    <rescap:Capability Name="runFullTrust"/>
    <uap:Capability Name="documentsLibrary"/>
  </Capabilities>
  <Applications>
    <Application Id="Example" Executable="Example.exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements DisplayName="Example" Description="Example" Square150x150Logo="images\icon.png"
        Square44x44Logo="images\icon.png" BackgroundColor="#000000" />
      <Extensions>
        <desktop7:Extension Category="windows.shortcut">
          <desktop7:Shortcut File="Example.exe" Icon="images\icon.png" />
        </desktop7:Extension>
      </Extensions>
    </Application>
  </Applications>
</Package>

**Comment by jhiggs15** [comment]
@drewbatgit Any luck recreating the issue?

**Comment by drewbatgit** [comment]
@jhiggs15 - Hi, I was able to get this to build and install. But, having never done it before, it took a few tries. I don't see it in your code sample above, but do you have the IgnorableNamespaces attribute declared?

&lt;Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7"
  **IgnorableNamespaces="uap rescap desktop7"**&gt;

**Comment by TimMangan** [comment]
If I can add some clarity here.  The current Windows SDK (as of Feb17 2023) only includes up to Desktop6 in the schemas supplied in the SDK.  Use of newer schemas is what triggers the need for the IgnorableNamespaces, so that the build tool knows it is OK to ignore what it doesn't know.  As long as the package is deployed to a system that supports this Desktop7 extension, it should work (and be ignored on back-rev OSs).

This is why it is so important for documentation of the requirements for these elements, which has been a longstanding (and understandably difficult to achieve) request.  

But yeah, the Windows SDK should also get upgraded.

**Comment by drewbatgit** [comment]
@TimMangan It looks like desktop7 was supported by the OS starting with build 20348, but due to timing issues, the schema wasn't included in the SDK until the following release. I am seeing desktop7 in SDK version 22000. Can you confirm that you are seeing it as well? 
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt

**Comment by TimMangan** [comment]
Confirmed that the SDK now includes desktop7 now.  I believe this issue should be closed now.
