### ISSUE TITLE
Extension has inconsistent casing in the text "windows.PhoneCallActivation" should be "windows.phoneCallActivation"

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-related#315]
Extension has inconsistent casing in the text "windows.PhoneCallActivation" should be "windows.phoneCallActivation"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1150ea5-ed5b-4811-d525-319b2d537a8d
* Version Independent ID: b1150ea5-ed5b-4811-d525-319b2d537a8d
* Content: [uap13:Extension - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap13-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap13-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for reporting this. The casing for phoneCallActivation has been updated.
