### ISSUE TITLE
More detail required.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#318]
This article should clarify whether the effect is only to files directly in the program's root folder or if it is recursive to subfolders, including potential VFS folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a70149a5-20e2-4092-56e3-9853dbc79c0b
* Version Independent ID: 915d8e54-3807-03d3-2d07-dddaa201b340
* Content: [uap10:InstalledLocationVirtualization - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-installedlocationvirtualization)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-installedlocationvirtualization.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-installedlocationvirtualization.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I asked a subject matter expert for guidance on this issue and they referred me to your white paper. In the hopes of making this page technically accurate without going into the level of detail of your paper, I've added the following clarifying statement:
"This path redirection applies recursively to folders underneath the root folder. The extension has limited support for virtual file system (VFS) paths."
