### ISSUE TITLE
Doesn't seem to work. :(

### ISSUE THREAD

**Issue by christoph-fer** [MicrosoftDocs/winrt-related#32]
I followed all the steps mentioned in this doc. But building the project in Creators Update still gives me an error that says NavigationView is not supported in API version 4.0.0.0. Am I missing anything? 

Project built on Windows 10 version 1803.
MinTarget: 1703
MaxTarget: 1803

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@christoph-fer: I believe you either need to download the latest Windows Insider Preview (Build 1807) OR download the new Windows UI Library, which also contains the NavigationView (in a different namespace though, Microsoft.UI.Xaml.Controls.NavigationView). Here are the instructions: https://docs.microsoft.com/en-us/uwp/toolkits/winui/ 

I'll be updating the docs with this info.

**Comment by mijacobs** [comment]
@christoph-fer: Are you trying to use the platform version of the NavigationView (Windows.UI.Xaml.Controls.NavigationView) or the Windows UI Library version (Microsoft.UI.Xaml.Controls.NavigationView)?

**Comment by christoph-fer** [comment]
@mijacobs: Hi. I tried using <controls:NavigationView/> and that worked perfectly fine.

**Comment by mijacobs** [comment]
@christoph-fer: Great! We're in the process of updating the docs with examples that show how to use the Windows UI Library versions.

**Comment by christoph-fer** [comment]
@mijacobs That's awesome! Looking forward to that. :)
