### ISSUE TITLE
Unable to write eventlog after configuring desktop2:DesktopEventLogging

### ISSUE THREAD

**Issue by chiluap** [MicrosoftDocs/winrt-related#321]
I configuered the following section in in my Package.appxmanifest:

```
<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  xmlns:desktop2="http://schemas.microsoft.com/appx/manifest/desktop/windows10/2"
  IgnorableNamespaces="uap rescap desktop2">
<Extensions>
		<desktop2:Extension Category="windows.desktopEventLogging">
			<desktop2:DesktopEventLogging AppName="MyApp">
				<desktop2:EventMessageFiles>
					<desktop2:File Path="logfolder\myapp.log"/>
				</desktop2:EventMessageFiles>
				<desktop2:TypesSupported>
					<desktop2:TypeSupported Value="EVENTLOG_ERROR_TYPE"/>
					<desktop2:TypeSupported Value="EVENTLOG_WARNING_TYPE"/>
					<desktop2:TypeSupported Value="EVENTLOG_INFORMATION_TYPE"/>
				</desktop2:TypesSupported>
			</desktop2:DesktopEventLogging>
		</desktop2:Extension>
	</Extensions>
```
	
when I try to write to the eventlog i get the following errors (after installation of the package)
	
`Ausnahme ausgelöst: "System.Security.SecurityException" in Microsoft.Win32.Registry.dll
Ausnahme ausgelöst: "System.Security.SecurityException" in Microsoft.Win32.Registry.dll
Ausnahme ausgelöst: "System.Security.SecurityException" in System.Diagnostics.EventLog.dll`

`System.Security.SecurityException: "The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security, State."`

Am I missing something here? The documentation is not very clear about how to configure event log access.

Also, the documentation states the extension belongs under Package>Applications>Application>Extensions>desktop2:Extension>desktop2:DesktopEventLogging>
but when I put it there I get an validation error:

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Validierungsfehler. error 80080204: App manifest validation error: Line 40, Column 29, Reason: The "windows.desktopEventLogging" extension should be declared under <Package> extensions.	MyApp	C:\[snip]\bin\x64\Debug\AppxManifest.xml	1	

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5942c669-05b8-12f6-5e6b-3df75690e6cb
* Version Independent ID: 2ce7db3f-ed30-9fbe-caac-7b644df6ca7c
* Content: [desktop2:DesktopEventLogging - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-desktopeventlogging)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-desktopeventlogging.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop2-desktopeventlogging.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A site](https://learn.microsoft.com/en-us/answers/questions/), where your issue may have already been discussed.
