### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#327]
The following elements are defined in the current desktop10 documentation set as having desktop10:extension as the parent, but are missing from this page:
   Desktop10:IconHandler
   Desktop10:PredefinedTriggerEvents
   Desktop10:SupportedProtocols

Additionally, the parameter CurrentDirectoryPath is new.  Everything else under desktop10 is a package extension, so if this is something only applicable to an application extension that should be clarified, or explained what it is applicable to.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 313ffab1-f654-f1b1-14e3-ea8b72a4e76e
* Version Independent ID: 313ffab1-f654-f1b1-14e3-ea8b72a4e76e
* Content: [desktop10:Extension (in Package/Extensions) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop10-extension?source=docs)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by TimMangan** [comment]
@drewbatgit  Please close this item.  The documentation is correct.

It seems I was wrong.  The three desktop10 elements that I referenced turn out to be used in Application Extensions and not Package Extensions (and they are buried at a deeper level so that wasn't obvious).  Sorry for the confusion.

**Comment by drewbatgit** [comment]
Thanks @TimMangan
