### ISSUE TITLE
Desktop10 missing from this page.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#328]
Add reference to the new Desktop10 extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efd8999c-d0a7-5788-883f-8e0aceb1db19
* Version Independent ID: 63285457-6305-9847-2e5f-50b4e07f698a
* Content: [Extensions (in Application) (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extensions)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-1-extensions.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-1-extensions.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan - I went down the rabbit hole on this issue and have two thoughts about this page: 

1. The elements listed on this page aren't really "child" elements defined in the schema. Rather, the SubstitutionGroup attribute allows elements to be placed inside an Extension element. Some Extensions are defined as ApplicationExtensionChoice, which means they are only application extensions, but other extensions are defined as ExtensionChoice and have both application and package extensions. 
2. The real validation of which elements are "allowed" under Package or Application is done in code, and is evaluated based on the category attribute. 

As part of this investigation, I was pointed to the source code that defines which *categories* are considered to be application vs. package extensions. I think this information is more valuable that a list of "child" elements that include both kinds of extension categories. I was able to parse the source code and generate a table of categories supported as application extensions. I'm proposing replacing the Child element section with a table in the remarks section of this page. Here is what that table would look like. As a frequent user of these docs, I am interested in your opinion of my proposed change to this page. Theoretically, I would go and make a similar table for the package extension page as well.

**Remarks**
The following extension categories are valid application extensions. 

| Extension category | Extension |
|-----------------------|--------------------------|
| windows.backgroundTasks | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extension.md) |
| windows.preInstalledConfigTask | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extension.md) |
| windows.updateTask | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extension.md) |
| windows.restrictedLaunch | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-extension.md) |
| windows.cloudFiles | [cloudFiles:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-cloudfiles-extension.md) |
| windows.comServer | [com:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com-extension.md) |
| windows.comInterface | [com:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com-extension.md) |
| windows.comServer | [com2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com2-extension.md) |
| windows.comInterface | [com2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com2-extension.md) |
| windows.comServer | [com4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-extension.md) |
| windows.comInterface | [com4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-extension.md) |
| windows.fullTrustProcess | [desktop:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md) |
| windows.startupTask | [desktop:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md) |
| windows.toastNotificationActivation | [desktop:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md) |
| windows.searchProtocolHandler | [desktop:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension.md) |
| windows.appPrinter | [desktop2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-extension.md) |
| windows.searchFilterHandler | [desktop2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-extension.md) |
| windows.searchPropertyHandler | [desktop2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-extension.md) |
| windows.mailProvider | [desktop2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop2-extension.md) |
| windows.autoPlayHandler | [desktop3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop3-extension.md) |
| windows.cloudFiles | [desktop3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop3-extension.md) |
| windows.fileExplorerContextMenus | [desktop4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop4-extension.md) |
| windows.service | [desktop6:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-extension.md) |
| windows.approvedShellExtension | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.controlPanelItem | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.service | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.mailProvider | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.shortcut | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.applicationRegistration | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.desktopAppMigration | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.systemFileAssociation | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.shadowCopyExcludeFiles | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-extension.md) |
| windows.shadowCopyExcludeFiles | [desktop7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop7-package-extension.md) |
| windows.fileExplorerClassicContextMenuHandler | [desktop9:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-extension.md) |
| windows.fileExplorerClassicDragDropContextMenuHandler | [desktop9:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop9-extension.md) |
| windows.activatableClass.outOfProcessServer | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-extension.md) |
| windows.comInterface | [Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-extension.md) |
| windows.aowApp | [mobile:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-mobile-extension-manual.md) |
| windows.mobileMultiScreenProperties | [mobile:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-mobile-extension-manual.md) |
| windows.communicationBlockingProvider | [mobile:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-mobile-extension-manual.md) |
| windows.phoneCallOriginProvider | [mobile:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-mobile-extension-manual.md) |
| windows.printSupportSettingsUI | [ printSupport:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-printsupport-extension.md) |
| windows.printSupportExtension | [ printSupport:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-printsupport-extension.md) |
| windows.printSupportJobUI | [ printSupport:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-printsupport-extension.md) |
| windows.settingsApp | [rescap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap-extension.md) |
| windows.desktopAppMigration | [rescap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap3-extension.md) |
| windows.lockScreenComponent | [rescap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap3-extension.md) |
| windows.fileTypeAssociation | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.protocol | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.autoPlayContent | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.autoPlayDevice | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.shareTarget | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.search | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.fileOpenPicker | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.fileSavePicker | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.cachedFileUpdater | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.cameraSettings | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.accountPictureProvider | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.printTaskSettings | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.lockScreenCall | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.appointmentsProvider | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.alarm | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.webAccountProvider | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.dialProtocol | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.appService | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.mediaPlayback | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.print3DWorkflow | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.lockScreen | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.aboveLockScreen | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.personalAssistantLaunch | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.voipCall | [uap:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-extension.md) |
| windows.protocol | [uap10:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-extension.md) |
| windows.printSupportSettingsUI | [uap12:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap12-extension.md) |
| windows.printSupportExtension | [uap12:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap12-extension.md) |
| windows.printSupportJobUI | [uap12:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap12-extension.md) |
| windows.phoneCallActivation | [uap13:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-extension.md) |
| windows.webAccountProvider | [uap2:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap2-extension.md) |
| windows.appointmentDataProvider | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.emailDataProvider | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.contactDataProvider | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.appUriHandler | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.appExtensionHost | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.appExtension | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.protocol | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.fileTypeAssociation | [uap3:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md) |
| windows.sharedFonts | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.userDataTaskDataProvider | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.mediaCodec | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.contactPanel | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.loopbackAccessRules | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.devicePortalProvider | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.printWorkflowBackgroundTask | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.printWorkflowForegroundTask | [uap4:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap4-extension.md) |
| windows.userActivity | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.mediaSource | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.videoRendererEffect | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.activatableClass.outOfProcessServer | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.startupTask | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.appExecutionAlias | [uap5:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-extension.md) |
| windows.barcodeScannerProvider | [uap6:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-extension.md) |
| windows.barcodeScannerPreviewProvider | [uap6:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-extension.md) |
| windows.localExperiencePack | [uap6:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap6-extension.md) |
| windows.sharedFonts | [uap7:Extension](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap7-extension.md) |

**Comment by TimMangan** [comment]
YEAH!!!!!   Figuring out which ones are package and which are application extensions has so far been an act of trying to find a copy of the schema file and looking for possible comments, and trial and error in creating/testing packages.  A clear table depicting this in the documentation is well needed.

**Comment by drewbatgit** [comment]
Ok, great. I'll go ahead and remove the child elements and add this table instead to the remarks instead. I'll add creating a version of this for Package/Extensions to my to-do list.

**Comment by drewbatgit** [comment]
I've completed this update. I didn't feel brave enough to delete the child elements list, so I updated it instead. I'll see what kind of response this update gets and then revisit whether it makes sense to leave those there.

**Comment by TimMangan** [comment]
I view it as appropriate.  The reader wants to know what to put in an XML file. You wouldn't remove the framework Extension as a child element, so someone reading this knows exactly what can be placed as a child of Extensions, even if the others are technically a substitution group in the schema sets.
