### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#329]
Under the heading "Parent Elements", the link is to the "Application Elements" page and I think it should be the "Package Elements" page (or possibly both?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 313ffab1-f654-f1b1-14e3-ea8b72a4e76e
* Version Independent ID: 313ffab1-f654-f1b1-14e3-ea8b72a4e76e
* Content: [desktop10:Extension (in Package/Extensions) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop10-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan Thanks again for reporting these errors. I confirmed that the types in desktop 10 are all under Package Elements and have updated the page accordingly.
