### ISSUE TITLE
Is this meant to be used alongside Windows.UI.Xaml.Controls, or instead of Windows.UI.Xaml.Controls?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/winrt-related#33]
I understand this library is meant to "fill the gap" for developers wanting to use newer controls on older Windows 10 builds (so that they get a larger audience).

Looking at the features mentioned at https://docs.microsoft.com/en-us/uwp/toolkits/winui/, one could draw the conclusion to use all controls from these Nuget packages instead of directly referencing the Windows controls and only using these Nuget packages as a fallback for older OS builds, since this seems much easier than using the version checks to decide what control or features to use.

Could you please clarify in what cases one would still use the built-in Windows controls and rely on version checks, rather than using this library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
The “Windows UI Library” (currently in preview) contains the most up-to-date versions of many of the same controls and UI features that exist in the UWP Platform SDK, but packaged in a way that they can be used against in-market OS versions.  

If your app needs to run against older versions of the OS, then using the versions of the controls in The Windows UI Library (Microsoft.UI.\*) will let you take advantage of the latest versions of controls and UI features sooner.  You can continue to use the version of the control in the OS, through the Windows.UI.\* namespace, but then you’ll need to handle platform version differences.

Keep in mind that the Windows UI Library is a preview version and will continue to evolve before it RTMs.

**Comment by hansmbakker** [comment]
Thank you!

I understand, but what I meant to ask was in what case you would still want to use the original Windows.UI namespace?

Will the nuget-distributed Microsoft.UI versions eventually replace them in newer windows versions when the nuget packages are mature enough?

**Comment by mijacobs** [comment]
For the foreseeable, you'll need to use certain controls from the Windows.UI.* namespace--for example, Button, RadioButton, Checkbox, etc. So far, our plan has focused on adding new controls to the Windows UI Library--we haven't  had any discussion about porting our older controls.

**Comment by hansmbakker** [comment]
Ok, that’s clear :)
