### ISSUE TITLE
uap:FileType specification is incomplete

### ISSUE THREAD

**Issue by leo-hydraulic** [MicrosoftDocs/winrt-related#330]
The docs for the uap:FileType are missing the most important part, which is the text content of the tag.
What I mean is, in examples you find things like:

```xml
<uap3:FileTypeAssociation Name="mediafiles">
  <uap:SupportedFileTypes>
    <uap:FileType>.avi</uap:FileType>
  </uap:SupportedFileTypes>
</uap3:FileTypeAssociation>
```

Where the `.avi` text inside the `uap:FileType` tag is clearly the thing I need to include to say that my app supports .avi files.
However, that part is nowhere to be seen in the [specification of the tag](
https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetype).

For comparison, the [specification of the uap:Logo element](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-1-uap-logo) contains the following snippet in the syntax:

```xml
<uap:Logo>
  <!-- A string between 1 and 256 characters in length that ends with ".jpg", ".png", or ".jpeg" that can't contain these characters: <, >, :, ", |, ?, or *. In this string, the / and \ characters can't be the first or last characters. Also, the string can contain / or \ but not both. -->
</uap:Logo>
```

**Comment by drewbatgit** [comment]
Thanks for catching this. This info has been missing for a long time! I've added the format restrictions for the value to the xml syntax block:

`<!-- A string between 1 and 64 characters in length that must begin with a period ("."), cannot have additional periods, and cannot contain these characters: <, >, :, ", /, \, |, ?, or *. -->`
