### ISSUE TITLE
Makeappx Publisher regex

### ISSUE THREAD

**Issue by smashingpks** [MicrosoftDocs/winrt-related#331]
[Enter feedback here]

I'm trying to make an appx file properly signed with a legit code signing certificate.  However I got an error while running "makeappx pack ...". 

MakeAppx : error: Failure at appxFactory->CreateManifestReader(manifestStream, &manifestReader) - 0x80080204 - The specified package format is not valid: The package manifest is not valid.
MakeAppx : error: Error info: error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 9, Column 15, Reason: CN=Super Technology Co., Ltd., O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR'?(?) '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*"? ?? ?? pattern? ?????.
?? 'CN=Super Technology Co., Ltd., O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR'? 'Publisher' ???  ?? ???? ? ??????.

It looks like the regex that filter Publisher string does not cover a CN string like this.
Publisher="CN=Super Technology Co., Ltd., O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR"
And my code signing certificate's subject is also "Super Technology Co., Ltd.".

Taking out the period in the middle of the CN and comma will produce appx without any errors. Then it causes signing problem when trying to sign the appx file. Since publisher and signing certificate's subject have to be the same.

Is there any workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0ee0144-02b5-0e97-f13e-210482937f30
* Version Independent ID: 40e5abbb-a25d-1a34-eb12-32b63a065260
* Content: [Identity (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-identity)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-identity.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-identity.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by florelis** [comment]
For that you have to use quotes on the field with a comma. So instead of

`CN=Super Technology Co., Ltd., O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR`

It has to be

`CN="Super Technology Co., Ltd.", O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR`

Then, when you put that in XML, you have to escape the quotes like this

`Publisher="CN=&quot;Super Technology Co., Ltd.&quot;, O=Super Lab, L=Seoul, S=Gangnam-gu, C=KR"`

**Comment by drewbatgit** [comment]
Closing as answered.
