### ISSUE TITLE
Missing new schemas (e.g. uap13)

### ISSUE THREAD

**Issue by emmasab** [MicrosoftDocs/winrt-related#334]
There are multiple new schemas that are missing from the [list of schemas and related Windows version](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/what-s-changed-in-windows-10). 

For example, [uap13](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap13-autoupdate).

**Comment by drewbatgit** [comment]
Thanks for catching this. This page has been neglected for a while. I've updated the list with the most recent schemas and verified the releases against the source code.
