### ISSUE TITLE
is http://schemas.microsoft.com/appx/manifest/uap/windows10/10 still valid ?

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/winrt-related#335]
is http://schemas.microsoft.com/appx/manifest/uap/windows10/10 still valid ?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla witryny learn.microsoft.com ➟ Linkowanie do problemu w usłudze GitHub.*

* ID: 3927d7ad-f999-51d1-e513-b934da793152
* Version Independent ID: 7f7e4b7c-8469-287c-ec9b-7f6016f8443e
* Content: [uap10:PackageIntegrity - Windows UWP applications](https://learn.microsoft.com/pl-pl/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-packageintegrity)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-packageintegrity.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap10-packageintegrity.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@KWodarczyk Hello, I can look into this for you. Can you explain what it is that is making you question whether this schema is still valid?

**Comment by KWodarczyk** [comment]
Yes I need to use PackageIntegrity flag for my WinUI 3 app and it does not build with this namespace and URL when browsed says that content has been removed.

**Comment by drewbatgit** [comment]
@KWodarczyk XML namespaces aren't necessarily actual URLs that you can browse to. You can view the actual schema here: https://github.com/microsoft/msix-packaging/blob/master/resources/AppxPackaging/Manifest/Schema/2019/UapManifestSchema_v10.xsd

I quickly tried to repo your issue with a blank app using the WinUI 3 Packaged Desktop app project template in VS2022 and I was able to compile and deploy the app using this PackageIntegrity element. Here is how it appears in my app manifest:
```xml
 <Properties>
    <DisplayName>PackageIdentityTest</DisplayName>
    <PublisherDisplayName>drewbat</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
	  <uap10:PackageIntegrity>

		  <!-- Child elements -->
		  <uap10:Content
			Enforcement = "on" />

	  </uap10:PackageIntegrity>
  </Properties>
```

Unfortunately, the issues in this repo are intended specifically for documentation issues and we can't provide individual developer support here. I recommend you post your issue at [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/). I'm going to close this issue, but if you discover that there is indeed an issue with incorrect documentation, you can still reply to this thread and I will investigate and update the documentation as needed. Thanks!

**Comment by KWodarczyk** [comment]
Hi thank you for the help, it  turned out that I was using the PackageIntegrity directly under Package node and not inside 'Properties" node once moved it works fine,. Perhaps it would be good to mention that those namespace urls are not viewable in the browser and provide a url to the readable urls.
