### ISSUE TITLE
Element Hierarchy

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#336]
The element hierarchy on this page should say uap7 instead of uap6.

Additionally, some guidance should be provided as to why the uap7 variant of this extension should be used instead of the uap4 variant.   Presumably, the uap7 should be preferred over the uap4 as the shared fonts are typically applicable to any application in the package.  As the uap7 variant is applied at the package level and uap4 is applied at the application level, the behavior is more clear when placed at the package level.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6170c0-cb6e-34f0-a6bd-2106ca8aa8d4
* Version Independent ID: 80f676f0-d887-96ff-3b43-4f5d766291ad
* Content: [uap7:Extension - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap7-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap7-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap7-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I have fixed the issue with the element hierarchy. With regard to the question of uap4 vs. uap7, I have sent email to the subject matter experts to try to get an answer but have not yet been able to get an answer.  I apologize, but as we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool. You can still comment on this issue if you have more info.
