### ISSUE TITLE
windows.fullTrustApplication must be upper camel case

### ISSUE THREAD

**Issue by anpozd** [MicrosoftDocs/winrt-related#338]
I receive the below error unless I change EntryPoint="windows.fullTrustApplication" to EntryPoint="Windows.FullTrustApplication"

`
Error | APPX0501 | Validation error. error 80080204: App manifest validation error: Line 39, Column 29, Reason: The "windows.service" Extension can't be declared outside of Full Trust EntryPoint(either inherited from Application or declared in the Extension).
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55f9a668-94ee-2da4-ec9e-f5ea1913da58
* Version Independent ID: 21f7b49a-1e82-331b-e602-9100caedb8ff
* Content: [Application (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. It appears that PartialTrustApplication also requires upper camel case. The docs have been updated accordingly.
