### ISSUE TITLE
Microsoft.UI.Xaml.dll calls an unsupported API

### ISSUE THREAD

**Issue by DL444** [MicrosoftDocs/winrt-related#34]
Submitted my app using Windows UI Library for certification. But certification failed saying that "API CoIncrementMTAUsage in ole32.dll is not supported for this application type. Microsoft.UI.Xaml.dll calls this API". Is there anything I missed? I saw the doc says the library is ready for store submission. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @DL444, 
Thank you for letting us know about this issue--our development team is working on a fix.

**Comment by kmahone** [comment]
@DL444, Thanks for reporting the issue. We've fixed this problem and published an updated package: 2.0.180724003-prerelease. If you pick up the new version you should no longer see this error.
