### ISSUE TITLE
Uap5:AppExecutionAlias

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#344]
https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-appexecutionalias
shows an example of uap5:appexecutionalias with either desktop4 or uap10 subsystem.

1) Information/guidance should be provided on reasons for using one or the other.
2) What is the behaviour/effect if subsystem is/isnot specified?
3) Specifying either subsystem in a packaged win32 app (FullTrust)  produces on error in MakeAppX.  From the event log AppXPackaging/Operational:

error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 360, Column 35, Reason: The attribute '{http://schemas.microsoft.com/appx/manifest/desktop/windows10/4}SubSystem' on the element '{http://schemas.microsoft.com/appx/manifest/uap/windows10/5}AppExecutionAlias' is not defined in the DTD/Schema.

or

error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 360, Column 35, Reason: The attribute '{http://schemas.microsoft.com/appx/manifest/uap/windows10/10}SubSystem' on the element '{http://schemas.microsoft.com/appx/manifest/uap/windows10/5}AppExecutionAlias' is not defined in the DTD/Schema.

**Comment by drewbatgit** [comment]
@TimMangan I have sent email to the subject matter experts to try to get an answer but have not yet been able to get an answer.  I apologize, but as we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool. You can still comment on this issue if you have more info.
