### ISSUE TITLE
desktop6:Service typo

### ISSUE THREAD

**Issue by dqanxy** [MicrosoftDocs/winrt-related#347]
In the attributes table, under StartAccount, I believe "localServices" is a typo and should be "localService". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3de3b3-dc0d-f24d-d19c-61db7cd7f8b8
* Version Independent ID: 02be2566-6070-f7d0-79a4-72a97fc57437
* Content: [desktop6:Service - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-service)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-service.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop6-service.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@dqanxy Thank you for reporting this. It has been fixed.
