### ISSUE TITLE
XamlDirect link needs updating

### ISSUE THREAD

**Issue by leonio** [MicrosoftDocs/winrt-related#35]
Does link need to point to https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.core.direct.xamldirect rather than the old windows.ui.xaml... namespace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716795b6-2bcc-8ff5-f999-5e1de88a04e0
* Version Independent ID: 590dd55a-a259-e6dc-972e-531dda080cd9
* Content: [NuGet package list for the Windows UI Library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/nuget-packages)
* Content Source: [winrt-related-src/toolkits/winui/nuget-packages.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/nuget-packages.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
@jesbis can you help fix the links? And maybe add a link for the MUX nuget documentation as well in the first row?

**Comment by mijacobs** [comment]
I updated the link to point to microsoft.ui.xaml a while back, but didn't close the issue.

**Comment by jevansaks** [comment]
The link isn't formatted correctly though:

>  [XamlDirect] (/uwp/api/microsoft.ui.xaml.core.direct.xamldirect) 

Might as well also add a link to the root of the [Microsoft.UI.Xaml.Controls](/uwp/api/microsoft.ui.xaml.controls) docs as well.

**Comment by mijacobs** [comment]
updated/added links
