### ISSUE TITLE
Improved phrasing

### ISSUE THREAD

**Issue by DrusTheAxe** [MicrosoftDocs/winrt-related#350]
[Enter feedback here]

>But it's redundant to specify both uap10:RuntimeBehavior/uap10:TrustLevel and EntryPoint at the same time. But if you do that, then it's an error if they contradict.

SUGGESTION: ~But~ It's redundant to specify both uap10:RuntimeBehavior/uap10:TrustLevel and EntryPoint at the same time. But if you do ~that,~ then it's an error if they contradict.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55f9a668-94ee-2da4-ec9e-f5ea1913da58
* Version Independent ID: 21f7b49a-1e82-331b-e602-9100caedb8ff
* Content: [Application (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application?source=docs)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Fixed.
