### ISSUE TITLE
Cortona deprecation

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#353]
It was recently announced that Cortona is being removed from WIn10/11 later this year (2023).  So it would make sense that at a minimum a note should be added here, and on similar pages, noting the deprecation of these APIs.  Also helpful might be information on whether inclusion of these APIs must be removed from code **_prior_** to the removal from the OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd86f224-3a44-d4ea-4267-b85b15ca122d
* Version Independent ID: 08de37da-0403-7569-3c76-7f931f955a47
* Content: [Voice command (VCD) schemas - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/voicecommands/vcd-xml-schema-portal)
* Content Source: [winrt-related-src/schemas/voicecommands/vcd-xml-schema-portal.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/voicecommands/vcd-xml-schema-portal.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by drewbatgit** [comment]
Thanks for calling this out. I consulted with the writer who worked on the Cortana content and his recommendatiion was to add this minimal boilerplate:

"The Cortana Skills Kit for consumer and enterprise, and the skills built on these platforms, have been deprecated."
