### ISSUE TITLE
Provide programming guidance for cloudfiles:ExtendedPropertyHandler

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-related#355]
There is absolutely zero documentation how to implement or use the ExtendedPropertyHandler.

How is it implemented correctly?
Implementing and registering that class in a com-server block isn't enough, because I don't see queries for that class anywhere.

Is it supposed to be adding/extending the Details-tab of the Properties-window?
Does it add viewable columns to the explorer details view?

Previous tickets:
https://github.com/microsoft/Windows-classic-samples/issues/198
https://github.com/MicrosoftDocs/winrt-related/issues/139

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e19de2-85bd-487f-27ce-22d8461b47fd
* Version Independent ID: 51e19de2-85bd-487f-27ce-22d8461b47fd
* Content: [cloudFiles:ExtendedPropertyHandler - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-cloudfiles-extendedpropertyhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-cloudfiles-extendedpropertyhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-cloudfiles-extendedpropertyhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@AliveDevil Sorry for the long delay responding to your issue. I have updated the page to note that the CLSID is for an implementation of [IStorageProviderPropertyCapabilities Interface](https://learn.microsoft.com/en-us/uwp/api/windows.storage.provider.istorageproviderpropertycapabilities?view=winrt-22621), which was intended to allow cloud providers to disambiguate between properties that are supported but not present vs. properties that are unsupported. The developer I contacted noted that, while this feature is *supported*, it's not currently leveraged by the OS. So, cloud providers aren't encouraged to implement this feature.
