### ISSUE TITLE
com_ptr::com_ptr constructor has an overload that takes a `T*` pointer, but that's not listed in the documentation.

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/winrt-related#357]
It's important to be complete.

The missing constructor is implicit and AddRef's the given pointer. All of this is important to include in the documentation (besides its existence, of course).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c580f286-b224-a1d5-8102-1679f309d545
* Version Independent ID: 8d3e325f-2b87-7c88-aed5-e414d4cd4f42
* Content: [winrt::com_ptr struct template (C++/WinRT) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-ptr)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/com-ptr.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/com-ptr.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, I've published an update to the topic now.

-Steve
