### ISSUE TITLE
Controls with *Reveal* Background have just white background with both light and dark themes

### ISSUE THREAD

**Issue by Mr1Penguin** [MicrosoftDocs/winrt-related#36]
Project settings: 15063-17713/17134

I added a button with one of the *Reveal* backgrounds.

This bug appears on desktop(17713.1000) after I add some items to controls:NavigationView(settings item doesn't have any effect in this case).
This situation always exists on mobile(15254.490) even if there is only button with reveal background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by Mr1Penguin** [comment]
Looks like problem exists only for c++/winrt projects.

C# + desktop is fine. But C# + mobile gives same result.

**Comment by jevansaks** [comment]
Good issue. Could you attach a repro project? I haven't heard of this problem before.
