### ISSUE TITLE
It would be nice to specify OS version that supports this and other APPX manifest features.

### ISSUE THREAD

**Issue by sshilov7** [MicrosoftDocs/winrt-related#360]
It would be nice if this and other APPX manifest elements pages would specify Windows versions where the described element is supported. desktop10:PredefinedTriggerEvents is a new feature. How would developers know on what Windows version it works?
Requirements say desktop10 namespace. But on what OS version desktop10 is supported?

I had to figure it out from source code commits when I was asked about OS version. External developers cannot do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db51cf7a-b3db-1ac7-7733-ca3a230ff6be
* Version Independent ID: db51cf7a-b3db-1ac7-7733-ca3a230ff6be
* Content: [desktop10:PredefinedTriggerEvents - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop10-predefinedtriggerevents?source=docs)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-predefinedtriggerevents.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-predefinedtriggerevents.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@sshilov7 Hello, thank you for helping to improve the documentation. We have made a pass through the appx manifest docs and added supported OS version for each element.
