### ISSUE TITLE
White Spaces in VisualGroup

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#361]
A reading of the schema validation seems to indicate that the VisualGroup element may not have any whitespace.  Putting a string like "This Name" in the element value does not seem to cause a validation error in MakeAppX/MakeMsix, however when installing the package the start menu items appear without a folder (whereas leaving the space creates the start menu folder).

After investigation, this page should reflect what is supported, possibly after product changes.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 793ed722-2599-556a-bb14-126445910540
* Version Independent ID: 2b72ee78-7baa-5f76-299d-042e669d5cab
* Content: [uap3:VisualElements (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-visualelements-manual)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-visualelements-manual.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-visualelements-manual.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I don't understand why the regular expression for that element does not allow for whitespace, but the feature team confirmed this is the current behavior. I've updated the page to indicate that spaces aren't allowed.

**Comment by TimMangan** [comment]
That wasn't the desired outcome, unless temporary.  A partner developer that depends on these 3rd party libraries is stuck and cannot release as MSIX.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
