### ISSUE TITLE
[DOCS] uap10:RuntimeBehavior	

### ISSUE THREAD

**Issue by rednoah** [MicrosoftDocs/winrt-related#364]
```
An optional string value. If specified, it can be one of the following values: windowsApp, packagedClassicApp, or win32App.
```
So what does `windowsApp`, `packagedClassicApp` and `win32App` mean exactly? What differences in runtime behaviour can I expect depending on this choice? Which one should I pick for my package and why? Example use case for each option? Since none is required, which one is the default?

**Comment by MagnusJohansson** [comment]
The 3 choices are documented [here in section Attributes -> uap10:RuntimeBehavior](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application#attributes). 

> "packagedClassicApp"—a WinUI 3 app, or a Desktop Bridge app (Centennial). For a WinUI 3 app, usually goes with a TrustLevel of "mediumIL" (but "appContainer" is also an option).
> 
> "win32App"—any other kind of Win32 app, including an app packaged with external location. Usually goes with a TrustLevel of "mediumIL" (but "appContainer" is also an option).
> 
> "windowsApp"—a Universal Windows Platform (UWP) app. Always goes with a TrustLevel of "appContainer".

One can also [learn that](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application#combinations-of-activation-info-attributes) :

> "EntryPoint, RuntimeBehavior, and TrustLevel have overlapping meaning, and they're specified (and/or inherited) in combinations. Here are some valid combinations of activation info attributes."

Where is also states that :

> Executable, uap10:RuntimeBehavior="packagedClassicApp", uap10:TrustLevel=["mediumIL", or "appContainer" (**_the default if omitted_**)]

That article has a lot of information that might or might not be relevant four your application and/or use case, so please read it in full.

Some related info that might be useful: [Advantages and disadvantages of packaging your app](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/#advantages-and-disadvantages-of-packaging-your-app) and  [Types of desktop apps](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#types-of-desktop-app)

**Comment by drewbatgit** [comment]
Resolving this issue as answered.
