### ISSUE TITLE
Minimum OS version

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#365]
Please add minimum OS runtime version for using a package containing the uap7:extension to this page.  By detection (event log warnings of unsupported namespace after installing the package), I can see that it is not supported on Windows 1022h2 but is on Windows 1122h2 (I didn't test earlier Windows  11 versions).

Ideally, these minimums would be completed for other namespaces as well.  For example, 1022h2 doesn't allow uap11 but does support (at least some of) uap10.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6170c0-cb6e-34f0-a6bd-2106ca8aa8d4
* Version Independent ID: 80f676f0-d887-96ff-3b43-4f5d766291ad
* Content: [uap7:Extension - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap7-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap7-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap7-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@timmangan In August of last year we updated the OS version for all pages in the schema reference section based on a list provided by the feature team.
