### ISSUE TITLE
Desktop10:Extension Category does not seem to exist for this element.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#366]
The Desktop10:IconHandler element claims to be a child of the Desktop10:Extension, however none of the documented categories work for this element, and a "windows.iconHandler" category does not exist.  There seems no way to use this element.

So this is both a documentation and schema problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4f9cad-6b93-7470-8dab-2dd410409a82
* Version Independent ID: 9c4f9cad-6b93-7470-8dab-2dd410409a82
* Content: [desktop10:IconHandler - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop10-iconhandler)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-iconhandler.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop10-iconhandler.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan It looks like somebody (probably me) reflexively made this a child of desktop10:Extension, but even though it's declared in that namespace, it's a child of [uap:FileTypeAssociation](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation?branch=pr-en-us-503). I've updated the files to reflect this.
