### ISSUE TITLE
Attributes not required

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#367]
A reading of the schema seems to indicate that only the "Id" parameter is required and all others are optional.

Additionally, in the CT_NewClass there are 8 additional child elements listed that are missing from this page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Version Independent ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Content: [com4:Class (in InProcessServer) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan Thanks for catching this! Somehow I got turned around and treated the default for attributes as required instead of optional. I've fixed the attribute tables and added the missing child elements for all of the elements of type CT_NewClass.
