### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#368]
It seems logical that either the Path Attribute, or InProcessServerDll child element would be required.

Similarly, it would be logical that either the Class or ClassReference element would be required as well.

I'm not sure that the schema specifies this, but it seems logical that you have to have a path and CLSID GUID defined at a minimum.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Version Independent ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Content: [com4:Class (in InProcessServer) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I assume you are talking about InProcessServer here. Just to make sure I understand, are you suggesting that we call out that this element doesn't make any sense if you don't reference an actual dll? First, I think it's important that we keep the definition of "required" to what is enforced by the schema - or in some cases the OS code that processes the schema. It may not make sense to have an element with no contents, but I'm not sure that's something we need to call out in the docs. I think the right thing to do is to assume that developers using this extension are doing so with a purpose in mind. I'm going to close this one as "won't fix". Maybe I've misunderstood what you are suggesting. As always feel free to continue the discussion in the comments.
