### ISSUE TITLE
Overall hierarchy isn't right

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#369]
The required hierarchy to define a COM4 based com server is not well defined in the documentation (not only on this page, but several others under Com4).

Consider the following AppXManifest example:
``  <Applications>``
``     <Application ... >``
``         <Extensions>``
``             <Com4:Extension Category="windows.ComServer">``
``                 <Com4:ComServer>``
``                     <Com4:InProcessServer>``
``                         <Com4:InProcessClass id="guid" ThreadingModel="Both" />``
``                         <Com4:InProcessServerDll Path="relative path" Architecture="x86"/>``
``                         <Com4:InProcessServerDll Path="relative path" Architecture="x64"/>``
``                     </Com4:InprocessServer>``
``                 </Com4:ComServer>``
``             </Com4:Extension>``
``         </Extensions>``
``     </Application>``
`` </Applications>``

This manifest validates against the schema via MakeAppx, but is not obvious via the documentation in the COM4 space.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Version Independent ID: 5b9899c3-e4cf-9f45-5a6c-d1f5d42911a3
* Content: [com4:Class (in InProcessServer) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-com4-inprocessserver-class.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I'm not seeing an element defined in the com4 schema with a *name* of "InProcessClass". The definition of the complex type for InProcessServer, CT_InProcessServer allows for a choice of three types of child elements. One of them has a *type* of CT_InProcessServerClass, but it is named "Class". 

```xml
<xs:complexType name="CT_InProcessServer">
        <xs:choice minOccurs="0" maxOccurs="4000">
            <xs:element name="Class" type="CT_InProcessServerClass"/>
            <xs:element name="InProcessServerDll" type="CT_InProcessServerDll"/>
            <xs:element name="ClassReference" type="CT_InProcessServerClassReference"/>
        </xs:choice>
        <xs:attribute name="Path" type="t:ST_DllFile" use="optional"/>
    </xs:complexType>
```
I do see that CT_InProcessHandler, the complex type for InProcessHandler does have a child of *type* CT_InProcessClass, but again, with the name "Class".

```xml
<xs:complexType name="CT_InProcessHandler">
        <xs:choice minOccurs="0" maxOccurs="4000">
            <xs:element name="Class" type="CT_InProcessClass"/>
            <xs:element name="InProcessHandlerDll" type="CT_InProcessServerDll" />
            <xs:element name="ClassReference" type="CT_InProcessClassReference"/>
        </xs:choice>
        <xs:attribute name="Path" type="t:ST_DllFile" use="optional"/>
    </xs:complexType>
```
Am I misinterpreting the schema here? Maybe you mistyped while you were writing up the issue text - these names are easy to mix up. Let me know if I'm just missing the issue here or if I can close this.

**Comment by drewbatgit** [comment]
@TimMangan - We are trying to close out our backlog of stale issues as we move to a new feedback system. I took another look and it seems to me that the .xsd file seems to restrict the child elements of InProcessHandler to exclude InProcessClass. I'm going to close this issue. If you think I should open a bug for the feature team, please reply and let me know whether you think the ideal fix would be to update the schema to reflect the actual behavior of MakeAppX or whether you think MakeAppX should enforce the restrictions defined by the schema..
