### ISSUE TITLE
Mising Remarks Section

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#370]
The description for parameters desktop7:CompatMode and desktop7:Scope in both the Desktop8:Extension and Desktop7:Extension documentation have a note to see the "Remarks" section.  This section does not appear on either page.

Hopefully the fix will be to add the remarks (rather than remove the notes to look for them) as we are having difficulty in determining when these parameters are required, what minimum requirements might exist, etc.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5bcc83-8fd9-4c8a-f669-618face262a4
* Version Independent ID: 3c5bcc83-8fd9-4c8a-f669-618face262a4
* Content: [desktop8:Extension (in Package/Extensions) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop8-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop8-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop8-extension.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan Thanks for catching this. It turns out the missing remarks for these attributes are:

CompatMode="classic" requires the Microsoft.classicAppCompat_8wekyb3d8bbwe capability.
Scope="machine" requires the Microsoft.classicAppCompatElevated_8wekyb3d8bbwe capability.

I've updated all of the pages that include these attributes to include this information, but I put them inline in the attribute descriptions rather than in the remarks section.

**Comment by TimMangan** [comment]
Drew,

I think some additional cleanup might be needed on the attribute.  It is unclear how to specify the capability.  I am guessing that this is actually a Uap4:CustomCapability.  THe only other reasonable choice is rescap:Capability, but I am guessing this is a custom capability.  In either case, the notation should be indicated on the several pages referencing these two capabilities.

Also, I'd like to confirm that it starts with a capital M.  It seems like a lower case microsoft. would be more consistent with the pascal case style generally used.

Please let me know if I need to open a new issue on this.
