### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#372]
A few mistakes on this page:

-  The example should start with Uap3:Verb, not Uap2:Verb
-  The parameters in the sample labeled as Uap3: (such as uap3:Parameters should just be unadorned (i.e. just Parameters)
-  The table with definition of the parameters should similarly drop the uap3 adornment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b826703-042f-7cf4-6973-20923b1373d7
* Version Independent ID: b18204a7-4920-8d16-3d05-60ea49a4a8db
* Content: [uap3:Verb - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-verb)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-verb.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-verb.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks! These have been fixed.
