### ISSUE TITLE
RefreshContainer throws exception

### ISSUE THREAD

**Issue by JohnnyWestlake** [MicrosoftDocs/winrt-related#38]
Attempting to use RefreshContainer via this library results in `Could not find Windows Runtime type 'Microsoft.UI.Private.Controls.IRefreshInfoProvider` when using the RefreshContainer via XAML.

I assume this *should* be supported given I can see nothing to say it shouldn't be

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-gb/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for reporting this, @JohnnyWestlake! The team is investigating the issue.

**Comment by DL444** [comment]
Same issue here.

**Comment by mijacobs** [comment]
The issue should be fixed in the latest bits--please let us know if you're encountering the error.
