### ISSUE TITLE
lfhsize when using AppAttach

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#381]
When an MSIX file is written to a format for App Attach (e.g.: Vhd/Vhdx/Cim) the AppxBlockMap.xml contents must be updated if any files are changed (such as package name or version) to match the actual files in the package.

As these formats are not "zip" compression based, there no longer is a lfhsize value.  Perhaps this attribute should actually be optional for these use cases, but even as a required field it seems that the description on this page should call this out and recommend a value to be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52cbb5d5-7462-6295-b7cc-4b4fdc61d2f9
* Version Independent ID: a7acc6d6-06db-a595-1361-4ada74c62c9c
* Content: [File (package block map schema) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/blockmapschema/element-file)
* Content Source: [winrt-related-src/schemas/blockmapschema/element-file.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/blockmapschema/element-file.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
