### ISSUE TITLE
Missing ExternalDependency in Syntax block of page

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#382]
The child win32Dependencies:ExternalDependency is missing from the Syntax block on this page (it is mentioned later).  The maximum number of these appears to be 1000 in the foundation schema.

Also, it looks like the limit for PackageDependency is 129, not 128.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 255711d5-f7d0-6cd5-a3b2-d97e6217ff5f
* Version Independent ID: e073be81-7b37-e32b-4dbc-fae8271886a8
* Content: [Dependencies (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-dependencies)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-dependencies.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-dependencies.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan With this small comment about 129 vs 128, you have pulled a thread that has unraveled to reveal some larger issues. You are right that the limit is 129, but apparently that is a bug. Some other, unrelated issues were also discovered with this ExternalDependency element, and a workstream has been spun up to address these issues. So, for now, I have added the element to the syntax block. When the internal resolution for the element count issue is resolved, I will update the page as appropriate. Thanks for keeping an eye out for problems in the docs.

**Comment by drewbatgit** [comment]
@TimMangan The feature team also wanted me to pass along their thanks to you for catching this. The limit will be changed back to 128, as apparently that is the actual limit enforced by the OS. The schema was changed to 129 in error and will be reverted.
