### ISSUE TITLE
CloudFilesContextMenus sorted randomly

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-related#384]
With these entries:
```
<desktop3:Verb Id="Item1" Clsid="20000000-0000-0000-0000-000000000001" />
<desktop3:Verb Id="Item2" Clsid="20000000-0000-0000-0000-000000000002" />
<desktop3:Verb Id="Item3" Clsid="20000000-0000-0000-0000-000000000003" />
<desktop3:Verb Id="Item4" Clsid="20000000-0000-0000-0000-000000000004" />
<desktop3:Verb Id="Item5" Clsid="20000000-0000-0000-0000-000000000005" />
<desktop3:Verb Id="Item6" Clsid="20000000-0000-0000-0000-000000000006" />
<desktop3:Verb Id="Item7" Clsid="20000000-0000-0000-0000-000000000007" />
<desktop3:Verb Id="Item8" Clsid="20000000-0000-0000-0000-000000000008" />
<desktop3:Verb Id="Item9" Clsid="20000000-0000-0000-0000-000000000009" />
<desktop3:Verb Id="ItemA" Clsid="20000000-0000-0000-0000-00000000000A" />
<desktop3:Verb Id="ItemB" Clsid="20000000-0000-0000-0000-00000000000B" />
<desktop3:Verb Id="ItemC" Clsid="20000000-0000-0000-0000-00000000000C" />
```

in the path `Package.Applications.Application.Extensions.(cloudFiles:Extension).(cloudFiles:CloudFiles).(cloudFiles:CloudFilesContextMenu)` results in random sorting of entries in the file explorer context menu:

```
Item1
ItemA
Item7
Item9
Item5
ItemC
Item8
Item4
Item6
Item2
ItemB
Item3
```

Please clarify how we - as developers - are supposed to make any sense of this.

The sorting order is not influenced by:
- order of appearance in CloudFilesContextMenu-element
- alphabetically sorting the verb Clsid
- alphabetically sorting the Title
- alphabetically sorting the verb Id

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97385097-5941-d306-0d9f-85113fa4cc59
* Version Independent ID: 97385097-5941-d306-0d9f-85113fa4cc59
* Content: [cloudFiles:CloudFilesContextMenus - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-cloudfiles-cloudfilescontextmenus)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-cloudfiles-cloudfilescontextmenus.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-cloudfiles-cloudfilescontextmenus.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A site](https://learn.microsoft.com/en-us/answers/questions/), where your issue may have already been discussed.
