### ISSUE TITLE
Wrong link in schemas/tiles/toastschema/element-text.md

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftDocs/winrt-related#386]
Wrong link in `placement` and `hint-callScenarioCenterAlign`. And missing `hint-style`. I found the attribute in the [community toolkit here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/6bfe8a5d21feb8818a8048b9fc41a84a70af8b0f/Microsoft.Toolkit.Uwp.Notifications/Adaptive/AdaptiveTextEnums.cs#L45)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e92f6f0f-ab42-eab2-0678-ceb777e2f0df
* Version Independent ID: dbbb8cc4-2a99-e3f8-b5da-9f3ad533893f
* Content: [text (Toast schema) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-text)
* Content Source: [winrt-related-src/schemas/tiles/toastschema/element-text.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/tiles/toastschema/element-text.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by drewbatgit** [comment]
Thanks for calling our attention to these issues. I have fixed the malformed link in the text. As for the *hint_style* attribute, I did some investigation, and it appears that even though this attribute is implemented in the AdaptiveTextStyle enumeration, this value isn't actually included in the generated XML.

![image](https://github.com/MicrosoftDocs/winrt-related/assets/16842221/fff48440-c519-45e7-a6c8-a119226fe6e1)

Also, it looks like in the new WIndows App SDK API [AppNotificationTextProperties](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.appnotifications.builder.appnotificationtextproperties?view=windows-app-sdk-1.4), hint-style isn't supported either. I believe that the Community Toolkit code has not been updated to reflect the properties that are currently supported by the notification framework. I have raised the issue with the feature team, and we will continue to investigate if doc changes are needed moving forward.
