### ISSUE TITLE
Incorrect element name

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#387]
It seems hard to believe I never noticed the mistakes here before!

The UAP3 schema lists the name of the child element as "FileTypeAssociation" and not "FileTypeAssociations".  This page should be corrected, as well as all downstream references.

In the downstream reference for uap3:FileTypeAssociation, the schema also shows that the element is an extension of the uap:FileTypeAssociation, which adds a slew of possible child elements not mentioned on the current uap3:FileTypeAssociations page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec848a65-ee50-b9c7-5812-84cb02f6ebd8
* Version Independent ID: 23355ab4-a53a-0889-4254-26dff43a1161
* Content: [uap3:Extension (Windows 10) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap3-extension-manual.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan Thanks for catching this. I've updated all occurrences to "FileTypeAssociation" and added the inherited attributes and child elements: https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-filetypeassociation
