### ISSUE TITLE
How do I get an HSTRING from a winrt:hstring?

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-related#388]
I would have thought the whole point of this class is to encapsulate a Windows HSTRING, and yet that is not described here, or anywhere that I can find.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76c48d19-39d2-154f-d94c-ff59eeed7939
* Version Independent ID: f52e84e2-9d1f-ba46-049f-30d89c4a861a
* Content: [winrt::hstring struct (C++/WinRT) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/hstring)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/hstring.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/hstring.md)
* Service: **uwp**
* Sub-service: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Yes, good point and question. I've added a second paragraph in the description here (at the start of the topic). It links to the info that discusses how to do it.

-Steve
