### ISSUE TITLE
AcrylycBrush FallbackColor Warning

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/winrt-related#39]
I have warning when I use Microsoft.UI.Xaml.Media.AcrilicBrush:
` <winui:AcrylicBrush TintColor="{ThemeResource PopupsBackgroundColor}" FallbackColor="#d8000000" BackgroundSource="Backdrop" TintOpacity="0.5"/>`

`The property ‘FallbackColor’ on type ‘AcrylicBrush’ is not available in the target platform minimum version (10.0.14393.0) supported by this project.`

Is this suppose to work this way?

**Comment by jevansaks** [comment]
Yes, unfortunately that is a limitation of the FallbackColor property.
