### ISSUE TITLE
Docs for Manifest Application attributes is self contradictory

### ISSUE THREAD

**Issue by smaillet-ms** [MicrosoftDocs/winrt-related#390]
In the [APPx Manifest Application element](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-application.md) docs page there is a glaring contradiction, and it is unclear what is officially supported or not. 

In the table row on `uap10:RuntimeBehavior` `Description` column it says, for `win32App` - "usually goes with a TrustLevel of "mediumIL" (but "appContainer" is also an option)."

However, later on down in the `Remarks` section it says: "Setting uap10:RuntimeBehavior="win32App" and uap10:TrustLevel="appContainer" isn't supported."

So, which one is right? One says it is allowed and supported, the other says the exact opposite... :confounded:
This needs to be corrected so it is clear.

**Comment by drewbatgit** [comment]
win32App must go with a TrustLevel of "mediumIL". The remarks were correct and the information in the attribute description was wrong. It has now been corrected.
