### ISSUE TITLE
Cant create APPX with Microsoft.UI.Xaml

### ISSUE THREAD

**Issue by RomanGL** [MicrosoftDocs/winrt-related#41]
Hello!

I using Windows Application Packaging Project for pack UWP-application with native background app service. UWP application uses Microsoft.UI.Xaml.
When i try to create APPX of my Package project I get these errors:

![image](https://user-images.githubusercontent.com/7839481/43511058-a8f7d52c-95a1-11e8-905a-b26cbc84af3e.png)

Debug appx creates successfully but Release no. Can you help me to fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
Sorry I didn't know about this github repo until now. If you're still seeing this on latest Visual Studio 2019 and latest WinUI (now on 2.1 release package), please let me know either on this issue or at https://github.com/Microsoft/microsoft-ui-xaml. Thanks!
