### ISSUE TITLE
Microsoft.UI.Xaml breaks down RevealBackgroundBrush

### ISSUE THREAD

**Issue by RomanGL** [MicrosoftDocs/winrt-related#42]
Hello!
I try to use Microsoft.UI.Xaml in my project, however I found some bugs: RevealBackgroundBrush isn't working properly in a custom ControlTemplate.

XamlControlsResources is disabled in App.xaml.cs:
![image](https://user-images.githubusercontent.com/7839481/43566064-5a78e45c-9657-11e8-9137-14aecfeb9bcb.png)
And enabled:
![image](https://user-images.githubusercontent.com/7839481/43566216-e62bad04-9657-11e8-9569-a8e466b8282d.png)

I created the example project for this bug.
[RevealBug.zip](https://github.com/MicrosoftDocs/winrt-related/files/2252379/RevealBug.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@RomanGL Thank you for taking the time to create this issue! Our team is investigating. What build are you running?

**Comment by mijacobs** [comment]
@kikisaints

**Comment by kikisaints** [comment]
There's nothing wrong with your control templates - there appears to be a bug in the XAMLControlsResources library that's causing an issue with Reveal's hover brush only (border is working correctly). Thanks for reporting! We'll get on that 👍

**Comment by RomanGL** [comment]
@kikisaints Thanks for your reply! 
I'll wait for the problem is fixed.

**Comment by mijacobs** [comment]
@kikisaints Has this issue been fixed?

**Comment by jevansaks** [comment]
Sorry for showing up late. If you're still seeing this, can you file a bug with a repro app in https://github.com/Microsoft/microsoft-ui-xaml ? Thanks!
