### ISSUE TITLE
Updates and Changelogs

### ISSUE THREAD

**Issue by mdtauk** [MicrosoftDocs/winrt-related#43]
Would it be possible to include the latest versioning for the Windows UI Library here?  And include changelogs detailing what has changed.  As these are not open source right now, it is important to find a way to detail new features in the future, or breaking changes.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-gb/uwp/toolkits/winui/#feedback)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
The WinUI Library is now on GitHub, so you should be able to find the info you need there:
https://github.com/Microsoft/microsoft-ui-xaml
