### ISSUE TITLE
Namespace Requirements incorrect.

### ISSUE THREAD

**Issue by edwardskrod** [MicrosoftDocs/winrt-related#45]
It looks like the Namespace is incorrect. It should be rescap3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc57c32-ceb3-65b6-3685-c22ac71bbb1c
* Version Independent ID: c52c5de2-3c0f-beac-2786-d17786e38277
* Content: [rescap3:MigrationProgIds - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-rescap3-migrationprogids)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap3-migrationprogids.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-rescap3-migrationprogids.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
Thanks for the catch! This will be updated shortly.
