### ISSUE TITLE
Namespace link is broken

### ISSUE THREAD

**Issue by danielgary** [MicrosoftDocs/winrt-related#47]
Namespace links here: http://schemas.microsoft.com/appx/manifest/desktop/windows10/4 but is a broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8c86a67-b2c6-f67d-db41-98739541590c
* Version Independent ID: 1d0274d9-50e9-e8dc-cb27-f1ffe3e5de81
* Content: [desktop4:Extension - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop4-extension)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop4-extension.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-desktop4-extension.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
This namespace is no longer rendering as a link in the article, so I am closing this issue.
