### ISSUE TITLE
Formatting on ISF page did not translate well from PDF

### ISSUE THREAD

**Issue by ChumpChief** [MicrosoftDocs/winrt-related#49]
Table format is significantly more difficult to read in the HTML documentation than the original PDF, including some errors e.g. in the Word Example under the TAG_DRAW_ATTRS_TABLE, TAG_PEN_WIDTH, the value 3 is displayed with confusing bullet points and disconnected from its tag.

Also the syntax highlighting was lost in several locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f57b5679-4a44-3284-e545-9d3c83d03592
* Version Independent ID: 7506e27f-d275-ec02-7515-31387b13e915
* Content: [Ink Serialized Format (ISF) Specification - UWP app developer](https://docs.microsoft.com/en-us/uwp/specifications/ink-serialized-format)
* Content Source: [winrt-related-src/specifications/ink-serialized-format.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/specifications/ink-serialized-format.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback @ChumpChief. I've updated the topic and hopefully fixed the issues you noticed.
