### ISSUE TITLE
__forceinline 

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/winrt-related#50]
cppWINRT is using always the latest MSVC C++17,  is __forceinline  actually necessary? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61423daf-d885-6ea0-9117-fcdaf7d89360
* Version Independent ID: 580ad3d5-d812-f811-30dc-5ae21b30037b
* Content: [winrt::check_hresult function (C++/WinRT) - UWP app developer](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/error-handling/check-hresult)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/error-handling/check-hresult.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/error-handling/check-hresult.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for raising the issue, @DBJDBJ! In this case, __forceinline is definitely by design. However, it's a hint to the compiler that consumers of C++/WinRT aren't helped by knowing. In light of that, I've removed it from the syntax block. Thanks! ~Steve

**Comment by DBJDBJ** [comment]
I was thinking (not writing sorry), each and every MSVC C++17  '__froceinlne' can be now changed to standard C++ 'inline', for the same effect.

But and also thanks to @stevewhims for the quick reaction!

**Comment by stevewhims** [comment]
Thanks, @DBJDBJ, I'll pass that info along, that's good to know. ~Steve
