### ISSUE TITLE
Description in "Command"-Section is wrong.

### ISSUE THREAD

**Issue by christian-becker-ta** [MicrosoftDocs/winrt-related#51]
A Command can contain 1 up until 20 ListenFor-Statements, like descriped in "ListenFor"-Section.
Also the error in the Code show's that a Command can only contain 10 ListeFor-Statements, if you add 21 Listen-For Statements. Please fix in new Version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ed5459-3f38-da0c-e168-f1203e2e8c35
* Version Independent ID: aeaec504-72ce-d4d0-358f-ddb88a829bcb
* Content: [Voice Command Definition (VCD) elements and attributes v1.2 - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/voicecommands/voice-command-elements-and-attributes-1-2)
* Content Source: [winrt-related-src/schemas/voicecommands/voice-command-elements-and-attributes-1-2.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/voicecommands/voice-command-elements-and-attributes-1-2.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @TiMeJuMp. I've updated the topic and informed the feature team of the erroneous error message.
