### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by LivefromRaleighwood** [MicrosoftDocs/winrt-related#52]
This level of details is great - thanks for posting it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started?WT.mc_id=windowsdocs-twitter)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you for your feedback, we appreciate it!
