### ISSUE TITLE
Windows.Foundation.Metadata.ApiInformation.IsEventPresent("Windows.UI.Xaml.Controls.TextBox", "CopyingToClipboard") is returning true even though the event is not available in ApiContract v3.0.0 (i.e.,Windows SDK v 10.0.14393)

### ISSUE THREAD

**Issue by nandavelugoti** [MicrosoftDocs/winrt-related#53]
Hello,

I am developing an UWP Application with **Visual Studio Community 2015** installed in a machine with **Windows 10 OS build 17134.228 (version 1803)**. I have install only one sdk which is 10.0.14393.33. The application is targeted to 14393 as max version and 10240 as min version.

In MainPage.xaml.cs, I am simply invoking the below code inside MainPage constructor after InitializeComponent:

```
public MainPage()
{
    this.InitializeComponent();
    if (Windows.Foundation.Metadata.ApiInformation.IsEventPresent("Windows.UI.Xaml.Controls.TextBox", "CopyingToClipboard"))
    {
       System.Diagnostics.Debug.WriteLine("TextBox.CopyingToClipboard event is present");
    }
    else
    {
       System.Diagnostics.Debug.WriteLine("TextBox.CopyingToClipboard event is not  present");
    }
}
```
In the above case if statement should fail as the application is targeted to 14393 where the CopyingToClipboard event is not present and "TextBox.CopyingToClipboard event is not present" should be printed to output console.

But, that is not happening, the if statement is being passed and "TextBox.CopyingToClipboard event is present" is being printed to output console.

Can anyone please help me with this issue?

**Comment by ginami** [comment]
Hi @nandavelugoti --what page in our docs are you referring to? This will help me route your question to the correct author. Thanks!

**Comment by nandavelugoti** [comment]
I am not referring to any doc in particular. It is a generic issue which I came across in one my UWP projects.
If you really want some reference please check https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk.

Also I have raised the same issue in MSDN Forum. You can refer that for more context :https://social.msdn.microsoft.com/Forums/en-US/3dd6ac3f-a34f-448c-bf56-b489e6035caf/windowsfoundationmetadataapiinformationiseventpresentwindowsuixamlcontrolstextbox?forum=wpdevelop

**Comment by ginami** [comment]
HI @nandavelugoti -- unfortunately this feedback avenue is only for issues with our docs. I think your best spot for surfacing this issue is the Windows Developer Feedback channel on User Voice: https://wpdev.uservoice.com/. You should get responses from both the dev community and Microsoft employees. Thank you!
