### ISSUE TITLE
Using this library overrides custom accent colors

### ISSUE THREAD

**Issue by lhak** [MicrosoftDocs/winrt-related#58]
Adding the required line to the App.xaml file overrides any changes made to the accent color by setting the SystemAccentColor resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
I've sent a query to the feature team. I'll let you know when I hear back!

**Comment by jevansaks** [comment]
Do you have more information? A repro app, perhaps?

There are some resources that are supplied by the XamlControlsResources type and so the order of the resource in the app.xaml resources matters. We've recently updated the documentation to be more clear in this regard.
