### ISSUE TITLE
Updated content?

### ISSUE THREAD

**Issue by K-O-N-E** [MicrosoftDocs/winrt-related#59]
Is this limitations doc still valid in October 2018?
No progresses for these missing features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b487e4-704e-7407-dc4e-dbd4787b6b17
* Version Independent ID: b7c66d71-1e06-7758-ca85-1f7b62937025
* Content: [UWP features not yet supported on Xbox - UWP app developer](https://docs.microsoft.com/en-us/uwp/extension-sdks/uwp-limitations-on-xbox)
* Content Source: [winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/uwp-limitations-on-xbox.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by iamdroppy** [comment]
I also wonder the same. There was no updates for quite a while now. I was hoping for Kinect Skeleton tracking, even though Kinect is officially discontinued.

**Comment by knicholasa** [comment]
Hi - I've reached out to the developers that own this area, and it sounds like this page is still accurate. 

If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
