### ISSUE TITLE
a few problem of NavigationView with winui library

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/winrt-related#61]
a few problems with the new NavigationView control on winui library :
1. No Acrylic.
2. No way to manually set acrylic because there is no "PaneBackground" property.
3. No way to edit its template in blend either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a36d9da-7510-64b5-f937-cc3d9f0c2325
* Version Independent ID: 43badf5d-f042-1bad-6e50-7a42100dbada
* Content: [Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/)
* Content Source: [winrt-related-src/toolkits/winui/index.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by lukeblevins** [comment]
Hello,
According to the new documentation for 1809, you must set the pane’s background from a theme resource. Read more here: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#navigation-view-customization

**Comment by jevansaks** [comment]
The change to move away from acrylic in the pane background was intentional. 

The blend edit-copy-of-template feature should be working again. It was broken in VS for a while but is fixed now, I believe.
