### ISSUE TITLE
Incomplete 1809 AppInstaller documentation

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/winrt-related#64]
1809 AppInstaller content is incomplete as of commit 3d27b6cfc313013efe99306db615ceafea70ce9a

* AutomaticBackgroundTask, ForceUpdateFromAnyVersion are not documented correctly (e.g. wrong namespace)
* AutomaticBackgroundTask, ForceUpdateFromAnyVersion link to the wrong content
* HoursBetweenUpdateChecks is confusingly a String (0-255) inclusive in some spots and Integer (0-24) with unknown (ex|in)clusivity – which is it?
* Examples are unusable, have code formatting issues (https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch#examples)

cc: @mikematteson

**Comment by cheles** [comment]
any updates on this?

**Comment by mijacobs** [comment]
This had fallen off our radar... investigating.

**Comment by mcleanbyron** [comment]
Hi @riverar - We apologize for not responding to this issue sooner. The code formatting issues you pointed out were fixed several weeks ago as part of a separate round of fixes to this area of the docs. As to the other issues, I am in the process of fixing those issues and the docs should up updated on the live site in the next few days. For what it's worth, HoursBetweenUpdateChecks is defined as an unsigned byte (0-255) with a default value of 24.

**Comment by mcleanbyron** [comment]
The docs have been updated with fixes for the rest of the issues you called out. Please feel free to reopen or open a new issue if you see any other issues! And thanks again for submitting your feedback.
