### ISSUE TITLE
Manifest documents should link back to feature documentation

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-related#67]
Each manifest page should have a related topics section which links back to the corresponding feature page.  These manifest schema pages are pretty useless to actually understand how to use the feature, but they usually come up first in search results.  For instance, this file type association schema page should link to the feature docs [here](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-file-activation) (it should also link back to this schema page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10bedc7-7a98-c539-8bb6-cc7d258ec400
* Version Independent ID: f7cde4ec-6c81-bf49-458c-42e8521a1191
* Content: [uap:FileTypeAssociation (Windows 10) - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-filetypeassociation.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by MatchaMatch** [comment]
Hi - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.

**Comment by michael-hawker** [comment]
@mikben can understanding de-prioritizing certain issues, but why not leave it open if the work still needs to be done? Closing it means folks won't see it when they click 'see the feedback for this page' at the bottom of the doc.

(It's also really annoying that showing the GitHub issues inline with the bottom of the article was removed, really kills the great doc experience we had with GitHub feedback.)
