### ISSUE TITLE
Contradiction between schema version and Windows version

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/winrt-related#68]
In the Attributes and Elements section, you say the 2017 schema is between 1709 and 1803 and in the Requirements section you say the 2017 schema is for version 1709 and later (no upper limit). Which one is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005fc6a6-9327-61b5-7fac-ce77fef2490d
* Version Independent ID: 2488a987-dede-9e52-9054-816599869da5
* Content: [AppInstaller - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-appinstaller#attributes-and-elements)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-appinstaller.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-appinstaller.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. The text has been updated to clarify how the namespaces correspond to Windows 10 releases.
