### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by toughengineer** [MicrosoftDocs/winrt-related#69]
[Interfaces; how to implement them in C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/implement-an-interface) in **See also** section is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874a0da5-0b91-d4c5-354d-1a91a3af2fcc
* Version Independent ID: e8d4dba3-7a82-debc-eadb-6fe93d699021
* Content: [winrt::implements struct template (C++/WinRT) - UWP app developer](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/implements)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/implements.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/implements.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
@toughengineer, thanks for letting me know: I just merged a fix for that into master; that'll be live in 24 hours. Meanwhile, this is what the link should be:

[Author APIs with C++/WinRT](/windows/uwp/cpp-and-winrt-apis/author-apis)

Thanks again!
~Steve

**Comment by toughengineer** [comment]
@stevewhims, sure, no problem :smile:

**Comment by stevewhims** [comment]
I'll go ahead and close this, since it's resolved. Thanks! ~Steve
