### ISSUE TITLE
Confusion between Windows.UI.Xaml and Microsoft.UI.Xaml

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/winrt-related#70]
The Windows UI Library has a nuget package called Microsoft.UI.Xaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716795b6-2bcc-8ff5-f999-5e1de88a04e0
* Version Independent ID: 590dd55a-a259-e6dc-972e-531dda080cd9
* Content: [NuGet package list for the Windows UI Library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/nuget-packages)
* Content Source: [winrt-related-src/toolkits/winui/nuget-packages.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/nuget-packages.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by michael-hawker** [comment]
@kgreed the Windows.UI.Xaml namespace is for the inbox controls.  The new Windows UI Library now ships some of these controls in the NuGet package to provide updates to these controls down-level but are in a new Microsoft.UI.Xaml namespace.
