### ISSUE TITLE
What "Remarks section"

### ISSUE THREAD

**Issue by SoundersFan** [MicrosoftDocs/winrt-related#71]
The description of the Name element refers to the "Remarks section" but there is no remarks section. Please add a remarks section with further explanation of what the Name element is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c19f439-22c9-25fe-784c-31b0c95318e6
* Version Independent ID: 768d6905-013e-ffdc-3866-b0494dbbff08
* Content: [TargetDeviceFamily (Windows 10) - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily#feedback)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. This text has been updated to refer to the "Examples" section along with a direct link to the section.
