### ISSUE TITLE
Windows.ApplicationModel.Calls.CallsPhoneContract is available in desktop mode, but it isnt considered at documentation

### ISSUE THREAD

**Issue by Quico20** [MicrosoftDocs/winrt-related#72]
I'm developing an app for Windows 10 Mobile and Desktop devices, and I just found out that if you do have Skype installed on your desktop and  also have a microphone this contract is available in Desktop mode, so the only exclusive contract for a windows phone is "Windows.Phone.PhoneContract".

I'm posting here this because it seems that in you documentation "Windows.ApplicationModel.Calls.CallsPhoneContract" is also exclusive for mobile devices. I'm just testing my app and this line of code "ApiInformation.IsApiContractPresent("Windows.ApplicationModel.Calls.CallsPhoneContract");" is throwing me a true boolean value.

Hope this feedback get updated!!!

If you need more information dont hesitate to contact me "quico20@hotmail.com" i'll be glad to help!!!

I'm also adding this screenshot of my desktop app, where i'm showing how checking if the api is present in my desktop, I assume because my laptop has a microphone integrated and also have skype installed.

I thought this contract was exclusively to windows phone, I changed my code to the following contract to ensure my adaptative code work just on windows phone. in the screenshot i show the results of my debugging also the information of my OS and Laptop.

![image](https://user-images.githubusercontent.com/13721058/48305342-994b5300-e4ee-11e8-9f18-0c93deb675a4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e4929c-6492-6cdc-c59a-bb2ce1954151
* Version Independent ID: 1ce4ade6-ec7d-c3ee-a5dc-95dbf90cb9e9
* Content: [Windows Desktop Extension SDK API contracts for UWP - UWP app developer](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-desktop-extension-sdk)
* Content Source: [winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by Quico20** [comment]
@mcleblanc are you watching this issue???, how long do you think its gonna take to solve it???

**Comment by knicholasa** [comment]
Hi Quico20, thanks for the thorough feedback! I will follow up with the team that owns this content area and update the thread when I have an answer.

**Comment by Quico20** [comment]
@knicholasa thanks man, looking forward to see the result of this issue.

**Comment by knicholasa** [comment]
Hi @Quico20, I have an answer for you. In the October 2018 Update, the CallsPhoneContract was moved from the Mobile Extension SDK to the Universal SDK. I believe the behavior of your code reflects that change.

The Contract List for the October 2018 Update has not yet been added to the page. The most recent version (Version 10.0.17134.1) corresponds to the April 2018 Update. I am going to be working on updating these extension pages. 

I can only respond to feedback about the docs themselves here. If you want further help or have technical feedback, you can find the proper channel here: https://developer.microsoft.com/en-us/windows/support. 

Thanks for bringing this to my attention and I hope that helps!

**Comment by Quico20** [comment]
@knicholasa thanks for the answer, I was on vacations, I'm glad to understand the issue, this update changed the behavior of my app, so i was force to use another Contract exclusively to Windows.Phone since I'm aming to Windows.Phone, Tablets and Desktops.

Do you know out of this topic where can I contact the responsible for Store.Services I'm kind stuck trying to make work the subscription in-App Purchase of UWP.

I'll be glad if you could point me in the right direction.

**Comment by knicholasa** [comment]
Sure. Feedback left here is meant for documentation issues, but if you need help with a development issue, you should be able to find what you need through this site: https://developer.microsoft.com/windows/support. That site links to a forum for asking questions about developing apps: https://social.msdn.microsoft.com/Forums/windowsapps. You can choose which forum is relevant to your question and ask there. Hope that helps!
