### ISSUE TITLE
Invalid Cast Runtime Exception

### ISSUE THREAD

**Issue by seanocali** [MicrosoftDocs/winrt-related#74]
I just installed the nuget packages and added the resource dictionary. I have a method that returns a Brush:
return (AcrylicBrush)Application.Current.Resources["SystemControlAltMediumLowAcrylicElementMediumBrush"]

It throws: "System.InvalidCastException: 'Unable to cast object of type 'Microsoft.UI.Xaml.Media.AcrylicBrush' to type 'Windows.UI.Xaml.Media.AcrylicBrush'.'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e77fe7-6970-8c3b-09f9-47986e2010c2
* Version Independent ID: 25715011-c3c8-ce15-a1fc-db2bd62a58cf
* Content: [Getting started with the Windows UI library - UWP app developer](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started)
* Content Source: [winrt-related-src/toolkits/winui/getting-started.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/toolkits/winui/getting-started.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by seanocali** [comment]
Obviously I can just specify the namespace in the cast (Microsoft.UI.Xaml.Media.AcrylicBrush), but will that kill backward compatibility for the project?

**Comment by jevansaks** [comment]
If you switch to using the Microsoft.UI.Xaml nuget package then the project should use MUX.Media.AcrylicBrush. MUX nuget package supports back to Anniversary update and newer (14393+) so it should still be backwards compatible.
