### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-related#75]
Would be nice to see an example in C++/winrt showing an array_view being constructed, loaded with data, accessed. The above example merely shows the templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994c31dc-f794-f22d-a4eb-3c561d1d3341
* Version Independent ID: 1c50bc13-77f1-14d4-3cf1-6ff32a6b834a
* Content: [winrt::array_view struct template (C++/WinRT) - UWP app developer](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/array-view#arrayviewarrayview-constructor)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/array-view.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/array-view.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jevansAN, the code example right at the end of the [array_view::array_view constructor](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/array-view#arrayviewarrayview-constructor) section shows an example per constructor overload (the overload is specified in the comment immediately above each construction). There are other (implicit and explicit) examples showing the usage of array_view in [Standard C++ data types and C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/std-cpp-data-types). Note that an array_view is initialized with a range, but not loaded with data, per se.

**Comment by jevansAN** [comment]
Thanks very much Steven,

	I've kind of lost track of which comment this relates to, but I remember asking about array_view one time with regard to something I had read about it having "died." In any event, I'm now OK on that score since C++/winrt can use a std::vector<unsigned char> where a byte array is wanted. 
	Since that comment I've confined myself to ask for more code examples in C++/winrt for such things as loading binary data from a series of files, etc. Gradually getting these worked out.

	Jeff

On Dec 3, 2018, at 3:11 PM, Steven White wrote:

Hi, @jevansAN, the code example right at the end of the array_view::array_view constructor section shows an example per constructor overload (the overload is specified in the comment immediately above each construction). There are other (implicit and explicit) examples showing the usage of array_view in Standard C++ data types and C++/WinRT. Note that an array_view is initialized with a range, but not loaded with data, per se.

—

**Comment by stevewhims** [comment]
I'll close this one for now, then. ~Steve
