### ISSUE TITLE
Please provide XSD Schema files also.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/winrt-related#76]
Thanks for documenting the BlockMap and other schema reference documentation.  But if you want third party developers to correctly use this documented interfaces, also providing a consumable XSD file is the way to go.  

Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea2a2fd-ea8a-e99e-4826-2b2e69eb6124
* Version Independent ID: 2a0f744a-5cf6-af99-39a5-7a2ddb77a871
* Content: [App package block map - UWP app developer](https://docs.microsoft.com/en-us/uwp/schemas/blockmapschema/app-package-block-map)
* Content Source: [winrt-related-src/schemas/blockmapschema/app-package-block-map.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/blockmapschema/app-package-block-map.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by wjk** [comment]
@TimMangan Some (albeit not all) of the AppX/MSIX XSD files can be found in the [MSIX packaging SDK repo](https://github.com/Microsoft/msix-packaging/tree/master/resources/AppxPackaging/Manifest/Schema). I have https://github.com/Microsoft/msix-packaging/issues/32 open to track adding the rest of the schemas to that repo. Microsoft says the remaining files will be added once 19H1 ships. Hope this helps!

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback, and I apologize for the delay in posting an official response on this issue. As the earlier reply indicated, many of the schemas (including the package manifest schemas) are now available in the [MSIX SDK](https://github.com/microsoft/msix-packaging/tree/master/resources/AppxPackaging/Manifest/Schema) repo. Many schemas (including the package manifest schemas and the block manifest schema) are also included in the following folder of the Windows SDK: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt. I plan to add this information to the schema docs.
