### ISSUE TITLE
array_view constructor documentation is confusing - it suggests it copies data

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-related#78]
Currently the array_view constructor documentation says

&gt; Initializes a new instance of the array_view struct with a copy of the input data.

However, an important property of the array_view is that it doesn't create a copy of the input data, it only creates a 'view' into it. Please could the documentation be updated to be less confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994c31dc-f794-f22d-a4eb-3c561d1d3341
* Version Independent ID: 1c50bc13-77f1-14d4-3cf1-6ff32a6b834a
* Content: [winrt::array_view struct template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/array-view)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/array-view.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/array-view.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @benstevens48, that's a good point. I've changed the language to be more consistent with the description at the top of the topic, which does describe the type correctly (and in line with how you describe it). That change should be live within 24 hours. ~Steve

**Comment by benstevens48** [comment]
Thanks, I can see the docs have been updated, so I'm closing this.
