### ISSUE TITLE
UWP App Native build in Store behaving differently from Native Build on local machine

### ISSUE THREAD

**Issue by gidevbr** [MicrosoftDocs/winrt-related#80]
We have an issue where UWP App **Native build in Store** behaving differently from Native Build on local machine (**side loaded native build**) . Store version app crashes on load, while sideloaded is working as expected. To note we only observe this behavior in UWP applications that are using _OData_ client. The debug output for store version doesn't not provide any information that could help identify issues.  Error from Event Viewer  :App failed. **Error code: Unknown HResult Error code: 0x80040904. Activation phase: COM App activation**

**Comment by mijacobs** [comment]
Hi Gidevbr, 
This GitHub issues account is for issues with the docs. I recommend going to 
https://developer.microsoft.com/en-us/windows/support and checking the forums. I did a search for the error code, and I found this thread:
https://social.technet.microsoft.com/Forums/en-US/f9d803e6-cd7b-4acb-ac4d-6fc6111569f4/windows-10-apps-fail-to-run?forum=win10itprogeneral
