### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by duncanmacmichael** [MicrosoftDocs/winrt-related#81]
test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35118798-8f23-27b0-8d63-642dba40b0a0
* Version Independent ID: e56d787a-1de8-422c-fed4-c0e257611b77
* Content: [winrt::make_self function template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/make-self)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/make-self.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/make-self.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Confirming successful assignment of test issue to myself. :)
