### ISSUE TITLE
Need an MIDL 3.0 language reference area

### ISSUE THREAD

**Issue by sichbo** [MicrosoftDocs/winrt-related#82]
This narrative walkthrough is a great start, but what we actually need is an exhaustive list of MIDL 3.0 syntax like we had for 1.0: https://docs.microsoft.com/en-au/windows/desktop/Midl/midl-language-reference.

Additionally we need a way in MIDL 3.0 to specify comments for intellisense. I don't see any way to actually document a .winmd component for consumption by 3rd party developers (ie an intellisense .xml file that matches the public winmd objects.) The first inclination is to try the old 1.0 `[helpstring("..")]` attribute, but expectedly that's unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dacbdf2-172f-dd41-829f-94295cd0c621
* Version Independent ID: b511accc-e0b1-9b30-d044-231d5204024d
* Content: [Introduction to Microsoft Interface Definition Language 3.0 - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/intro)
* Content Source: [winrt-related-src/midl-3/intro.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/intro.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @sichbo, I've reached out for help in addressing these issues and I'll get back to you asap. ~Steve

**Comment by sichbo** [comment]
Thanks @stevewhims — you the man 👍

**Comment by stevewhims** [comment]
Cool, so I'm still waiting on the first question. But regarding IntelliSense, a new work item has been created to track that (because the IDL language has never had syntax for IntelliSense comments, and supporting doc comment generation is a feature request). For the IntelliSense engine in Visual Studio to operate on IDL files and give syntax color coding is another feature request we've filed and are tracking.

**Comment by stevewhims** [comment]
Simon, for the first issue above (exhaustive list of MIDL 3.0 syntax), I've added a new topic: https://docs.microsoft.com/uwp/midl-3/reserved-keywords. That, together with the info in the MIDL Reference section (which is still applicable to MIDL 3.0), and the info in the MIDL 3.0 docs (https://docs.microsoft.com/uwp/midl-3/), should be enough to unblock you, I hope. If there are specific keywords, or specific syntax, that block you in practice, then please let me know and I'll spot-fix the docs. I'm not, any time soon, going to have bandwidth to reproduce that comprehensive MIDL Reference for MIDL 3.0. Cheers! ~Steve

**Comment by sichbo** [comment]
Cheers, Steve. Many thanks. Let's put this issue out of its misery.

**Comment by stevewhims** [comment]
Thanks, Simon! :)
