### ISSUE TITLE
Guidance on how to "winrt::make" a projection from an existing implementation pointer.

### ISSUE THREAD

**Issue by sichbo** [MicrosoftDocs/winrt-related#83]
It's well documented how we can instantiate new projected objects for returning to public API callers:
```
NS::MyClass GetNewInstance() { 
      NS::MyClass projection = winrt::make&lt;NS::implementation::MyClass&gt;();
      return projection;
}
```

We also have a million examples on how easy it is to get the *implementation* from a projection:
```
void DoSomethingFromClientInstance(NS::MyClass fromClient) {
    auto impl = winrt::make_self&lt;NS::implementation::MyClass&gt;(fromClient);
    impl.DoSomethingInternal();
}
```

What we don't seem to have is guidance on how to wrap our implementation ("this") into a projection for handing off to other projected API objects, which may or may not be external. Consider the following IDL:
```
runtimeclass Class1 {
	void DoThingWithClass2(Class2 fromClient);
}

runtimeclass Class2 {
	void DoThing(Class1 sender);
}
```

It might be something blindingly obvious I've missed, but achieving the implementation of `Class1::DoThingWithClass2` has so far eluded me on winrt documentation alone:
```
void Class1::DoThingWithClass2(Class2 fromClient) {	
	auto projection = /* how do we get a projection from "this"? */
	fromClient.DoThing(projection);
}
```

Clearly for performance reasons an implementation *probably shouldn't* make calls to a projected instance, but my mental model of how the winrt jigsaw puzzle pieces together feels incomplete without an answer on how to derive a projection from an implementation pointer. Intuitively I want to simply go `winrt::make&lt;Class1&gt;(this)` and get back a projection to my own implementation instance.

Any hints appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5b6081-b8a1-f93e-7fbc-cff3f8174963
* Version Independent ID: c2dfd768-7ecf-1b85-8bb6-378bd0b8b9ef
* Content: [winrt::make function template (C++/WinRT) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/make)
* Content Source: [winrt-related-src/cpp-ref-for-winrt/make.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/make.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @sichbo, it's really about the conversion operator that's mentioned in the very last sentence of this section: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-apis#instantiating-and-returning-implementation-types-and-interfaces. The code in this case is:

```cppwinrt
void Class1::DoThingWithClass2(SomeNamespace::Class2 const& fromClient) {	
	fromClient.DoThing(*this);
}
```

I'll update that section to make this a lot clearer. Thanks for filing the issue, and I hope that helps! ~Steve

**Comment by sichbo** [comment]
Thanks @stevewhims! That's magic. Maybe we could drop your example in after the last sentence there for somebody. 

Thanks again.

**Comment by stevewhims** [comment]
I added a new scenario there after that sentence, with a little bit of code. The change is live now. I believe it covers your scenario, but if it needs more work, please let me know! ~Steve

**Comment by sichbo** [comment]
Nice work @stevewhims, that section's a lot more informative now. Many thanks.

**Comment by stevewhims** [comment]
Great, thanks, Simon!
