### ISSUE TITLE
Error: 'HoursBetweenUpdateChecks' attribute is not defined in the DTD/Schema

### ISSUE THREAD

**Issue by Marse1** [MicrosoftDocs/winrt-related#86]
It is specified that that "UpdateSettings" element could have the "HoursBetweenUpdateChecks" attribute. But, during installing the created AppInstaller file I get the validation error despite the entered namespace definition in "xmlns". Is this attribute supported here?

"The app manifest must be valid as per schema: Line 14, Column 21, Reason: The attribute 'HoursBetweenUpdateChecks' on the element '{http://schemas.microsoft.com/appx/appinstaller/2017/2}UpdateSettings' is not defined in the DTD/Schema. (0xc00ce015)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7ce943-631c-600e-c5ef-7ecd95f70aeb
* Version Independent ID: 95c6d06d-92c3-8900-e44f-8300644f12ee
* Content: [UpdateSettings - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-update-settings.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-update-settings.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by driesvandamme** [comment]
You have to use the 2018 schema:
http://schemas.microsoft.com/appx/appinstaller/2018

**Comment by Marse1** [comment]
Before posting my feedback I have double checked with the 2017, 2017/2 and 2018 schemas and result was the same. Note that exactly the 2017/2 schema is specified in the **Requirements** section of the https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings page.

Information from the Event Viewer with the use of 2018 schema:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-AppXDeployment-Server" Guid="{3f471139-acb7-4a01-b7a7-ff5da4ba2d43}" /> 
  <EventID>404</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>3</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000000000000001</Keywords> 
  <TimeCreated SystemTime="2019-01-22T22:47:39.779179200Z" /> 
  <EventRecordID>6820</EventRecordID> 
  <Correlation ActivityID="{9806855f-b2a3-0000-41d1-0798a3b2d401}" /> 
  <Execution ProcessID="3528" ThreadID="7620" /> 
  <Channel>Microsoft-Windows-AppXDeploymentServer/Operational</Channel> 
  <Computer>DESKTOP-QHJI5KC</Computer> 
  <Security UserID="S-1-5-21-2344913609-2079414755-2616629637-1001" /> 
  </System>
- <EventData>
  <Data Name="SummaryError">error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 14, Column 19, Reason: The attribute 'HoursBetweenUpdateChecks' on the element '{http://schemas.microsoft.com/appx/appinstaller/2018}UpdateSettings' is not defined in the DTD/Schema.</Data> 
  <Data Name="PackageFullName">file:///C:/Users/User/Desktop/pkg/test%20appinstaller.appinstaller</Data> 
  <Data Name="ErrorCode">0x8008020c</Data> 
  <Data Name="MountPoint" /> 
  <Data Name="TargetPlatform">0x0</Data> 
  <Data Name="CallingProcess">RuntimeBroker.exe</Data> 
  </EventData>
  </Event>
```

I am using Windows 10, 1809.

**Comment by driesvandamme** [comment]
It is specified that that "UpdateSettings" element could have the "HoursBetweenUpdateChecks" attribute. - Where did you find that?

`  <UpdateSettings>
              <OnLaunch HoursBetweenUpdateChecks="0" />
	<AutomaticBackgroundTask/>
	<ForceUpdateFromAnyVersion>true</ForceUpdateFromAnyVersion>
  </UpdateSettings>
`

**Comment by Marse1** [comment]
On the https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings page. 
![image](https://user-images.githubusercontent.com/41452433/51537926-90fd8580-1e58-11e9-9007-673f4aab6997.png)

**Comment by Marse1** [comment]
The '**HoursBetweenUpdateChecks**' attribute of the '**OnLaunch**' element is described separately at https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch and accepts values in wide range from 0 to 255, when the '**HoursBetweenUpdateChecks**' attribute of the '**UpdateSettings**' element accepts values only from 0 to 24.

**Comment by mcleanbyron** [comment]
Thanks for bringing this documentation error to our attention. I checked the schemas and confirmed that **HoursBetweenUpdateChecks** is an attribute of the [OnLaunch](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-onlaunch) element, not [UpdateSettings](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings) (note that **OnLaunch** is a child element of **UpdateSettings**). The example near the bottom of [this article](https://docs.microsoft.com/en-us/windows/uwp/packaging/install-related-set) shows correct usage.

I am removing **HoursBetweenUpdateChecks** from the [UpdateSettings](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings) article, and this fix should be published to the live docs site in the next day or two.
