### ISSUE TITLE
wrong link?

### ISSUE THREAD

**Issue by BogdanMitrache** [MicrosoftDocs/winrt-related#92]
ForceUpdateFromAnyVersion element has the same docs link as the OnLaunch element. I assume this is just a copy-paste mistake that needs to be corrected? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7ce943-631c-600e-c5ef-7ecd95f70aeb
* Version Independent ID: 95c6d06d-92c3-8900-e44f-8300644f12ee
* Content: [UpdateSettings - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings#feedback)
* Content Source: [winrt-related-src/schemas/appinstallerschema/element-update-settings.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/schemas/appinstallerschema/element-update-settings.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for reporting the link issue. This has now been fixed.
