### ISSUE TITLE
This page does not provide enough information

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#96]
Please describe what is in these contracts.
I am trying to find IDXGISwapChain in what contract is it, no success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e4929c-6492-6cdc-c59a-bb2ce1954151
* Version Independent ID: 1ce4ade6-ec7d-c3ee-a5dc-95dbf90cb9e9
* Content: [Windows Desktop Extension SDK API contracts for UWP - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-desktop-extension-sdk)
* Content Source: [winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/extension-sdks/windows-desktop-extension-sdk.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by knicholasa** [comment]
Hi, thanks for leaving feedback. I'll look into updating these docs. In the meantime, if you are having trouble using IDXGISwapChain in your code, try consulting our developer support pages or forums: https://developer.microsoft.com/en-us/windows/support
