### ISSUE TITLE
not enough documentation

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#97]
No description which winodws namespaces are included.
what about dxgi.idl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a66bde-e2d3-c8f9-1818-711aa502c063
* Version Independent ID: 95673030-90b8-601c-8f82-dbf29357f538
* Content: [Troubleshooting Microsoft Interface Definition Language 3.0 issues - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/troubleshooting)
* Content Source: [winrt-related-src/midl-3/troubleshooting.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/troubleshooting.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, thanks for filing this issue!

So, the purpose of MIDL 3.0 is to declare Windows Runtime types inside .idl files (see https://docs.microsoft.com/uwp/midl-3/). DXGI is a Desktop/Win32/COM technology. So, while it *does* use .idl files (as COM APIs do), it's not a Windows Runtime technology, so MIDL 3.0 isn't applicable to it. MIDL 3.0 applies to all of the current Windows Runtime APIs as well as to any third-party Windows Runtime APIs.

Please let me know if I can add any further info. ~Steve

**Comment by kingofthebongo2008** [comment]
Thank you.

Well this distinction needs to be made explicit then.

I want to expose IDXGISwapChain to a runtime component actually.

**Comment by stevewhims** [comment]
I hear your feedback, so in response I've just completed a Pull-Request to add more clarification to this Troubleshooting topic. And I added a link from this Troubleshooting topic to the introductory topic. That change should be live either today or tomorrow, but I'll keep an eye on it.

I am interested in understanding your scenario, in case I can add any info/help...

> I want to expose IDXGISwapChain to a [Windows Runtime Component (WRC)], actually.

Am I correct in understanding that you want to expose the IDXGISwapChain COM interface (which is IUnknown-derived) *from* a WRC? In other words, to expose that interface *from* the WRC *to* a consuming application? Is that the scenario? If you're writing Windows Runtime code in C++ (whether that's a WRC, or an application), then of course you can consume a COM interface such as IDXGISwapChain *from within that code; from within that built binary*. But COM and WinRT are sufficiently different at the binary interface level that you wouldn't/couldn't expose a COM interface as a return type or a parameter type for any part of the Windows Runtime API surface that you expose from your WRC (you'd need to create a WinRT type that wrapped the COM interface). So, you can use COM interfaces (such as DirectX and DXGI, for example), *from within* the C++ code of a WinRT app/component, but not across the binary interfaces between WinRT binaries. Very few languages (primarily C and C++) would know what to do with that COM interface; whereas the WinRT binary interface needs to work with all language projections.

I don't know whether I understood the scenario or not, so please correct me if I'm mistaken. But, FYI, there is a precedent for wrapping the functionality of a (IUnknown-derived) COM interface within a (IInspectable-derived) WinRT interface, and that's this type: https://docs.microsoft.com/windows/desktop/api/windows.ui.xaml.media.dxinterop/nn-windows-ui-xaml-media-dxinterop-iswapchainpanelnative. So it's possible that you could use that interface, or do something similar. Or just expose whatever properties of the swapchain that you want to be configurable as properties and methods on one of your own WinRT types.

~Steve

**Comment by kingofthebongo2008** [comment]
Thank you i would look in it.  Now that you explain to me looks logical,
may be this should be put in msdn to be more visible somehow.

The scenario that we have is as following.
We have written small renderer above dx12 and i want to expose this to
users that work with C#. The initial initialization wants swap chain
interface.

We have evaluated several options, but windows runtime components looks to
me the way to go and we want to test it.
Now they probably will be UWP code bases and the will have a swap chain
panels, but i wanted to avoid passing SwapChainPanels and just
IDXGISwapChain interface, because it is the minmum for initalization.

Other options that we have evaluated were sharpgen or working in C++
directly, but the people are not very familiar with and they need it just
for prototyping ideas fast.

May be also, midl that is used in winrt and com should be distinguished
somehow also making explicit that com and winrt are not the same.

All the best

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008. Yes, I'll make the changes that you suggest to the docs to add clarification.

Regarding your investigation of your design (for exposing the swap chain via WinRT), it sounds to me like you're on the right tracks, and evaluating some good options. But replicating the minimum facilities of the swap chain out via WinRT sounds like the way to go (whether that's something that's already part of WInRT, like the swap chain panel, or something that you create custom for your applicaiton). And, I agree that for prototyping, a programming interface that's higher level than C++ is needed.

~Steve

**Comment by stevewhims** [comment]
I just want to correct my mistake on one thing that I said in the thread above. I basically said that it's not possible to "expose a COM interface as a return type or a parameter type for any part of the Windows Runtime API surface." Clearly, I was wrong about that. The ISwapChainPanelNative::SetSwapChain method is itself an example of a WinRT API that takes a raw COM pointer. However, that doesn't change the fact that you wouldn't be able to call such a WinRT API from C#. So even correcting my mistake doesn't help you, because authoring an API like that would require your prototypers to use C++, which we said wasn't desirable. However, if you like, I can investigate how to declare a method such as ISwapChainPanelNative::SetSwapChain in MIDL 3.0. As I say, I don't think that'd help you in this particular scenario, but I'll do that if you like. ~Steve

**Comment by kingofthebongo2008** [comment]
I have designed my custom c++ interfaces, exactly as ISwapChainNative is done.
So in general a documentation can be added, that exposing native com interfaces can be exposed only from c++ and consumed only by c++.
Usually one defines IMyInteface and IMyNativeInterface, IMyInterface is passed around in the functions between native code and in the native code one can query IMyNativeInterface.

**Comment by stevewhims** [comment]
Thanks for the update, @kingofthebongo2008. I've done as you suggest and added that info in https://docs.microsoft.com/uwp/midl-3/intro#use-cases-for-midl-30. I'll go ahead and close this issue now, since it feels resolve. But please re-open it if necessary.

~Steve
