### ISSUE TITLE
Put descriptions here, what is what.

### ISSUE THREAD

**Issue by kingofthebongo2008** [MicrosoftDocs/winrt-related#98]
Seems only people in ms know what is this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e7b704-bf3b-deaa-0683-9d0a9c69c5d2
* Version Independent ID: d7cbf72b-0ff0-7e3a-9054-ede01cacff97
* Content: [Reserved keywords (MIDL 3.0) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/midl-3/reserved-keywords)
* Content Source: [winrt-related-src/midl-3/reserved-keywords.md](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/midl-3/reserved-keywords.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, for the keywords that overlap with MIDL 1.0, please see the reference here: https://docs.microsoft.com/windows/desktop/midl/midl-language-reference. I'll update this topic with some info and a link to the MIDL 1.0 reference.

Thanks for filing the issue!
~Steve

**Comment by stevewhims** [comment]
Hi, @kingofthebongo2008, the change is live, so I'll go ahead and close this issue now. ~Steve
